### ISSUE TITLE
Get embeded object by filter email

### ISSUE THREAD

**Issue by Ivan8R** [rethinkdb/rethinkdb-go#142]
How I can get embeded object `user` from `userRegistration` by filter email?
How I can update field `email` in `userRegistration` struct?

```
type user struct {
    name  string
    email string
}

type userRegistration struct {
    user     user
    password string
    listoffavorites []favorites

}
```

With Best Regards

**Comment by dancannon** [comment]
Hi, In answer to your questions:
1. To get the fields in a struct you should ensure that the fields are exported, if they are not exported when inserting your record the document will be empty. For example you should change your type definitions to:

``` go
type user struct {
    Name  string
    Email string
}

type userRegistration struct {
    User     user
    Password string
    ListOfFavorites []favorites
}
```

Then when you fetch the results from the database you simply scan the result into `userRegistration` and access the `User` field.
1. To update a single field in a document I recommend simply using a map. For example:

``` go
r.Table("userRegistration").Update(map[string]interface{}{
    "User": map[string]interface{}{
        "email": "new.email@example.com",
    },
})
```

Hope that helps, if you have any other questions I try to be active in https://gitter.im/dancannon/gorethink

**Comment by Ivan8R** [comment]
@dancannon Thanks. How i can Filter objects by email with structure  userRegistration in db?

**Comment by dancannon** [comment]
Maybe something like this...?

``` go
r.Table("userRegistration").Filter(r.Row.Field("User").Field("Email").Eq("??"))
```

**Comment by Ivan8R** [comment]
@dancannon I'm found:
If struct looks like this, with small letters

```
type user struct {
    name  string
    email string
}
```

Query not working or return nothing. Why?

**Comment by dancannon** [comment]
As mentioned above struct fields need to be exported to work in queries. See https://golang.org/ref/spec#Exported_identifiers

**Comment by Ivan8R** [comment]
@dancannon Thanks, now It's clear

**Comment by Ivan8R** [comment]
@dancannon Thanks, now it's clear for me
