### ISSUE TITLE
Marshaler/Unmarshaler Example? 

### ISSUE THREAD

**Issue by nullboundary** [rethinkdb/rethinkdb-go#145]
Hi Nice work on the new release! Yesterday I updated to 0.6 and to the latest RethinkDB in order to use your Marshaler/Unmarshaler interfaces, but so far I haven't had much luck getting them to work. Basically I have a value in my data struct that is sometimes an Int and sometimes a string so marshaler would come in handy. I haven't had any problems getting it working with Json.unmarshaler but I can't seem to figure out the same for gorethink. 

The gorethink marshaler seems to be working so I must be close. When I attempt something similar with gorethink unmarshaler I always get this error:

```
gorethink: UnmarshalRQL(non-pointer interface {})
```

Though I am not sure what that means exactly or how I can make it a pointer interface. 

Here is a gist: https://gist.github.com/nullboundary/4d572ca0beb5443f1c8b

Sorry this is not really much of an issue, more of a plea for help. So if we can figure out the bug, I can add my gist as an example for the marshaler/unmarshaler interface. Thanks!

**Comment by dancannon** [comment]
Hey, thanks for reporting this issue, I have found a small bug in the decoder code which caused pointers to `Unmarshaler`s to not be properly handled.

I have pushed a fix to the `develop` branch and I will probably merge this to master in a week or so. Could you let me know if this fixes your issue?

**Comment by nullboundary** [comment]
Thanks! Sure I will test with develop branch right now and get back to you soon.

**Comment by nullboundary** [comment]
Ok that fixed it, thanks a lot! If you want to use that gist as an example you are more then welcome.

**Comment by dancannon** [comment]
This fix has now been merged to master.
