### ISSUE TITLE
Cursor.All: The slice may be previously allocated

### ISSUE THREAD

**Issue by tp** [rethinkdb/rethinkdb-go#148]
When reading the documentation for Cursor.All I wondered what happened if I pass in a previously allocated slice.

From reading [the code](https://github.com/dancannon/gorethink/blob/2e7684d7ac636f4ea39a909b624c9298252d5122/cursor.go#L199) I got the understanding that your implementation tries to reuse the slice and either appends to it or returns a "sub slice" if there less than len(s) return values.

I think this is a great solution and should probably be reflected in the functions documentation so far as that the user does not have to fear for the slice containing previously included items.

**Comment by dancannon** [comment]
I intend to redo most of the API documentation soon (hopefully) but I will look into updating the documentation for `All` over the weekend.
