### ISSUE TITLE
ForEach: Function argument is not of type Term

### ISSUE THREAD

**Issue by tp** [rethinkdb/rethinkdb-go#149]
When trying to convert the following ReQL to create missing tables to gorethink, I always a panic stating `Function argument is not of type Term`.

ReQL

``` js
r.expr(["table1", "table2"]).setDifference(r.db("dev").tableList()).forEach(function (tableToCreate) {
    return  r.db("dev").tableCreate(tableToCreate)
});
```

gorethink:

``` go
var objectKinds = []string{"attribute", "culture"}
r.Expr(objectKinds).SetDifference(r.Db(rethinkDatabaseName).TableList()).ForEach(func(args ...interface{}) {
    r.Db(rethinkDatabaseName).TableCreate(args[0])
}).RunWrite(session)
```

(I couldn't find an example / test for this, so that's the conversion I came up with)

**Comment by dancannon** [comment]
Hi Timm,

You should try using `r.Term` instead of `interface{}` as the function arguments. For example:

``` go
var objectKinds = []string{"attribute", "culture"}
r.Expr(objectKinds).SetDifference(r.Db(rethinkDatabaseName).TableList()).ForEach(func(args ...r.Term) {
    r.Db(rethinkDatabaseName).TableCreate(args[0])
}).RunWrite(session)
```

Hope this helps, if not let me know.

**Comment by tp** [comment]
Thanks for the correction regarding the ForEach func parameters.

Sadly this does still not work with the change.

**Comment by dancannon** [comment]
Ok, I will have a closer look at this issue later tonight.

**Comment by tp** [comment]
This works:

``` go
r.Expr(objectKinds).SetDifference(r.Db(rethinkDatabaseName).TableList()).ForEach(func(tableName r.Term) r.Term {
    return r.Db(rethinkDatabaseName).TableCreate(tableName)
}).RunWrite(session)
```

Seems like ForEach is just expecting the function to only have 1 parameter.

Should probably close this and create an issue for a better error message / documentation.

**Comment by dancannon** [comment]
Ideally I would like `ForEach` to support variadic arguments. At the very least the function should not panic.

If you could create a new issue reporting this bug that would be great, Thanks

**Comment by dancannon** [comment]
Unfortunately it looks like variadic arguments will not be possible because of how rethinkdb callbacks work. 

I have updated the documentation so hopefully it is now a bit clearer. Let me know if you have any further questions.

**Comment by tp** [comment]
Given the [ReQL forEach documentation](http://www.rethinkdb.com/api/javascript/for_each/) I think it would suffice to have ForEach only accept one `func (r.Term) r.Term` function instead of the variadic arguments.

As a bonus we would get compile time errors if the passed function does not conform to this.

**Comment by dancannon** [comment]
The issue with trying to do this is that this function is valid ReQL, originally I tried doing as you suggested but moved to the current solution:

``` go
r.Expr([1,2,3]).Map(r.Expr(func(row r.Term) interface{} {
    return row; 
}))
```
