### ISSUE TITLE
Question about `Filter`

### ISSUE THREAD

**Issue by alimoeeny** [rethinkdb/rethinkdb-go#154]
Does the `Filter` function runs the `func` it accepts as its argument on the client? or it sends it to the server? 
I assume it does send it to the server, then isn't there any restrictions on the kind of code in the function? I looked around the docs and didn't find anything about this, hope I haven't been careless.

**Comment by AtnNn** [comment]
Hello,

Functions in ReQL queries are called once on the client to build an AST,
which the server can then evaluate multiple times.

How it works is described in this blog post:

http://rethinkdb.com/blog/lambda-functions/

Hope that helps.

Etienne Laurin

2015-02-19 19:59 GMT+00:00 Ali Moeeny notifications@github.com:

**Comment by alimoeeny** [comment]
Yes, thanks @AtnNn
