### ISSUE TITLE
Strange behavior on int64

### ISSUE THREAD

**Issue by alimoeeny** [rethinkdb/rethinkdb-go#156]
I have a struct like this:

``` go
type concept struct {
   MYID int64
}
```

If I set `MYID` to `9223372036854775807` when I retrieve it I get `-9223372036854775808` back.
Cross validating it with the webui, is not possible because of the known javascript issue with large integers, it basically shows `9223372036854776000` 

Any comments?

**Comment by ghost** [comment]
Hey, @alimoeeny, [possible values](http://golang.org/ref/spec#Numeric_types) of `int64` are in range from -9223372036854775808 to 9223372036854775807. So, the value you are using for your `MYID` looks correct. Don't you by chance increment it somewhere? Or do you think gorethink driver itself causes the overflow?

**Comment by alimoeeny** [comment]
huh! I have been debugging this for like an hour and had all sorts of values, chose this one just at random, and in this particular case there maybe some other issues involved. 
Basically, I create a large int64 value (which is a valid int64 within range) but cannot get it back, after I insert it into the db.
If I convert it to `string` using `strconv` and change the type on my struct to `string` all is fine. 
My guess would be that RethinkDB either uses V8 or some other javascript engine, or some other intermediate language that cannot deal with large `int64`, the same problem javascript in the browser cannot deal with these large numbers and replaces the two right digits with 00 .
Thanks, @anonx , For now, I am using `string`

**Comment by neumino** [comment]
RethinkDB supports double precision float only, not integers, which is probably it somewhere overflows.

**Comment by alimoeeny** [comment]
mmmm, thanks @neumino . 
So I guess the driver should warn about this? 
or maybe `int64` should not be accepted as a supported type?

**Comment by tp** [comment]
I tried to find anything to handle this at the database layer, but couldn't find a solution.

It seems that integers are only save up until 2^53 ([see StackOverflow](http://stackoverflow.com/a/23479778/856403)).

So until RethinkDB can't error on insert (which I find really odd, given that different data will be saved than what was given), I would also propose an error from the driver at the very least.

**Comment by alimoeeny** [comment]
Thanks @tp (wow you have two character username!). 
I created an issue on the main rethink repo pointing to our discussion here, just in case the core developers have any comments or suggestions. (https://github.com/rethinkdb/rethinkdb/issues/3834)

**Comment by dancannon** [comment]
I am closing this issue since its more of a "Nice to have" feature, if rethinkdb/rethinkdb/#3835 does not go anywhere I will revisit this.
