### ISSUE TITLE
unmarshaler error:  invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by nullboundary** [rethinkdb/rethinkdb-go#161]
Hi, it seems the a new unmarshaler bug has surfaced. I now get the error message: 

```
    panic: runtime error: invalid memory address or nil pointer dereference
```

However this only seems to occur if I am using a pointer to a type in the struct,
for example with this struct below `*Value` or `*Time` will cause the error:

``` go
type userModel struct {
    ID            *Value     `json:"id" gorethink:"id"`
    Email         string     `json:"email" gorethink:"email"`                          //Email is ID of user
    Organization  string     `json:"org,omitempty" gorethink:"organization,omitempty"` //User organization name
    OAuthProvider string     `json:"oauth,omitempty" gorethink:"oauth,omitempty"`      //User is using OAuth
    Created       *Time      `json:"created,omitempty" gorethink:"created,omitempty"`  //Account Created time/date
    LastLogin     *Time      `json:"login,omitempty" gorethink:"lastLogin,omitempty"`  //Last login time

}

/*************************************************************************
Value type

Used with json.Unmarshal interface to assign either string, float or int to value
************************************************************************/
type Value struct {
    ValueInt    int64  `json:"valueint,omitempty" gorethink:"valueint,omitempty"`
    ValueString string `json:"valuestring,omitempty" gorethink:"valuestring,omitempty"`
}
```

If I change it to:

``` go
type userModel struct {
    ID            Value     `json:"id" gorethink:"id"`
    Created       Time      `json:"created,omitempty" gorethink:"created,omitempty"`  //Account Created time/date

}
```

Everything seems to work. However if I use Time instead of *Time when an empty value is submited it will create an empty field. 
In the case of Time it looks like: "created":  "0001-01-01T00:00:00Z". Other values might be "" or {}. 

Not marshalling an empty struct using a pointer is a common technique as illustrated here:
http://stackoverflow.com/questions/18088294/how-to-not-marshal-an-empty-struct-into-json-with-go

This was working great before in #145 but it seems your change in #151 might have broken something. Thanks!

**Comment by dancannon** [comment]
I have pushed some more tests and a fix for this issue to `develop`. Could you check it out and make sure everything is ok?

Assuming that it is I will probably merge to `master` on Sunday.

**Comment by nullboundary** [comment]
Yup, looking good now, everything running flawlessly. Thanks a lot!
