### ISSUE TITLE
goprotobuf repository has moved to  github.com/golang/protobuf

### ISSUE THREAD

**Issue by AlexLuya** [rethinkdb/rethinkdb-go#169]
Hello,
        gorethink is still refer to https://code.google.com/p/goprotobuf,and In china,all google's stuff has been blocked.This cause a installation issue.Would you please update source to refer to github?

**Comment by dancannon** [comment]
Hi @AlexLuya, this issue has already been fixed by https://github.com/dancannon/gorethink/pull/162. I am just waiting for RethinkDB 2.0 before I can release the latest version of the driver (v0.7). For more information regarding the release have a look at #168.

**Comment by AlexLuya** [comment]
Thanks
