### ISSUE TITLE
Is it possible to refer to a Term value like this:creator isn't 'user-xxxx' but "+row.Field("CreatorId")

### ISSUE THREAD

**Issue by AlexLuya** [rethinkdb/rethinkdb-go#172]
Hello,
       My use case likes blow,and I want to combine a string with row.Field("CreatorId") value to produce more useful error message,is this possible?

``` go
          rt.Branch(
                       row.Field(CREATOR_ID).Eq(creatorId),
                       dsc.Map{EDIT_STATUS: DELETED},
                       rt.Error("creator id isn't 'user-xxxx' but "+row.Field("CreatorId")),
         )
```

**Comment by dancannon** [comment]
Hey, sorry it took so long for me to reply, I have been pretty busy with v0.7. 

That being said I don't believe it is possible to do what you want just using ReQL. If you would like to request this feature I recommend creating an issue on the RethinkDB repository.

**Comment by AlexLuya** [comment]
thanks
