### ISSUE TITLE
Subqueries via Merge()?

### ISSUE THREAD

**Issue by keighl** [rethinkdb/rethinkdb-go#183]
I'm struggling to translate this kind of JS-driver query into gorethink. It's basically a multi-subquery situation similar to [this](http://rethinkdb.com/docs/cookbook/javascript/#using-subqueries-to-return-additional-fields).

``` js
r.db("test").
  table("items").  
  merge(function(x) {
    return {
      user_1: r.db("test").table('users').get(x('user_1_id')),
      user_2: r.db("test").table('users').get(x('user_2_id'))
    }
  })
```

I've tried stuff like this with no luck:

``` go
res, err := r.Table("items").  
  Merge(func(row r.Term) interface{} {
    return map[string]interface{}{
      "user_1": r.Table("users").Get(row.Field("user_1_id")),
      "user_2": r.Table("users").Get(row.Field("user_2_id")),
    }
  }).
  Run(DB)

res, err := r.Table("items").  
  Map(func(row r.Term) r.Term {
    return row.Merge(map[string]r.Term{
      "user_1": r.Table("users").Get(row.Field("user_1_id")),
      "user_2": r.Table("users").Get(row.Field("user_2_id")),
    })
  }).
  Run(DB)
```

I might end up denormalizing the key user attributes within these records cuz the subquery performance is kind of bad. But curious as to how I would accomplish it with gorethink. 

Thanks for a great go driver!

**Comment by dancannon** [comment]
Hi @keighl, 

I cant see anything wrong with your first query and after running the query myself I get the exact same value when running both the Go version and the JS version. Could you explain exactly what issues you are having with your queries and that should hopefully make it a bit easier to answer your question.

Thanks :)

**Comment by keighl** [comment]
Hey @dancannon thanks for getting back to me. The user_1, user_2 attributes were returning nil. 

However, I fired it up again today, and now the fields are hydrating appropriately. Must have been me doing something dumb!
