### ISSUE TITLE
Aborting change query

### ISSUE THREAD

**Issue by aviz** [rethinkdb/rethinkdb-go#191]
I could not find a way to abort a change query.

Next() is blocking... and while Next is blocking i found no way to stop it's execution.
I tried to call close, but it ended with crash due to double socket close.

**Comment by dancannon** [comment]
Hi @aviz, Thanks for creating the issue.

Calling `Close` should work so there is probably a bug there causing the crash however I am also not sure if closing the cursor is the best way of stopping the query. I will look into fixing this issue after the 1.0 release of the driver.

**Comment by aviz** [comment]
I'v made a temporary fix to this at https://github.com/aviz/gorethink
The fix should be applied on the closed flag.. but i did not wanted to diverge too much from original code.

The idiomatic way of closing the cursor is by notifying a channel in my opinion.

**Comment by dancannon** [comment]
@aviz I agree with your idea of using a channel but I think it makes sense to get a fix out quickly. That being said I think we should probably use `closed` instead of adding a new flag that does the same thing.

**Comment by dancannon** [comment]
Merged the fix to `master`. Thanks for the help @aviz.
