### ISSUE TITLE
Changefeeds block forever when connection is dropped

### ISSUE THREAD

**Issue by dancannon** [rethinkdb/rethinkdb-go#194]
As reported by @omeid when iterating through a changefeed stream using `Next` the driver sometimes blocks forever (even when changes are made). This seems to be due to the connection being dropped but the changefeed does not detect this.

I am still investigating the source of this issue and will update the issue when I know more.

**Comment by omeid** [comment]
To replicate this issue, simply drop the connection between the software and database after starting a change feed, the `Next` call will be blocking even when the connection is dropped.

**Comment by dancannon** [comment]
So it seems like Go is not actually closing the connection in certain situations which is causing the driver to read from the connection forever. The situation that I used to replicate this was running the DB on an external server and then disabled the WiFi on my laptop. Attempting to break the connection by killing the DB process and also when I killed the SSH tunnel I was using caused the connection to be closed.

I am not really sure if there is a solution for this issue so unless anybody has any other ideas I will close this issue.

**Comment by pandemicsyn** [comment]
Pretty sure im running into similar issues, except I'm _not_ using change feeds. I've noticed that periodically my app stall's out and blocks on the vanilla Run(rethinksession) call when I go to execute a query. 

Running with SetVerbose(true) doesn't giving me any additional output.

**Comment by pandemicsyn** [comment]
Heh, nevermind, I was running a Delete elsewhere and never returning the connection to the pool.

**Comment by dancannon** [comment]
Glad you solved your issue @pandemicsyn, I would recommend running `Delete` queries using `RunWrite` or `Exec` as this automatically returns the connection to the pool.

**Comment by dancannon** [comment]
@omeid since we couldn't reliably reproduce this issue and nobody else has reported this issue I will close it.

**Comment by omeid** [comment]
I could not reproduce the problem any more and it seems like the issue was with something else.

14 days in and the changefeed is alive and strong. :+1:
