### ISSUE TITLE
No connections were made after updating gorethink package

### ISSUE THREAD

**Issue by aranw** [rethinkdb/rethinkdb-go#200]
I've been working with the gorethink package locally for awhile and when I went to install the project on my colleagues machine they pulled gorethink for the first time the code then stopped working. 

I noticed the godocs had been updated so updated my local version and updated the code but found that I started getting the "no connections were made when creating the session" 

The code am running is 

```
        address := fmt.Sprintf("%s:%d", c.String("rethink_host"), c.Int("rethink_port"))

    r.SetVerbose(true)

    session, err := r.Connect(r.ConnectOpts{
        Address: address,
    })
    if err != nil {
        log.Fatalln(err.Error())
    }
```

This is the output I get in terminal 

```
FATA[0003] no connections were made when creating the session
```

**Comment by aranw** [comment]
I've confirmed that this problem only happens with my Docker version of RethinkDB.

Docker version

```
"version":  "rethinkdb 2.0.2~0jessie (GCC 4.9.1)"
```

Server version 

```
"version":  "rethinkdb 2.0.2~0trusty (GCC 4.8.2)"
```

**Comment by dancannon** [comment]
It looks like this is an issue caused by the switch to using host discovery by default (due to an issue with the healthchecks when host discovery was disabled).

I will revert the change and come up with a better solution to the previous issue.
