### ISSUE TITLE
UnmarshalJSON vs UnmarshalRQL

### ISSUE THREAD

**Issue by or-else** [rethinkdb/rethinkdb-go#201]
If I understand correctly, `gorethink` gets query result data from DB as a thinly wrapped JSON, json.Unmarshal's it into a map, then unmarshals the map into the user-provided object. I suspect you chose to copy the data one extra time (vs directly unmarshaling JSON to the user's object) to support user-provided struct tags + support for Rethingk-specific data types like time, binary & geo. You also support rethink-specific unmarshaling `UnmarshalRQL`.

Now, that represents somewhat of a problem. I want to add Rethink as another backend to a larger project. One of the data types I want to store is defined as an interface. It has the standard decoding interfaces defined: `sql.Scanner`, `encoding.BinaryUnmarshaler`, `encoding.TextUnmarshaler`, `json.Unmarshaler`. None of these work with gorethink. I have to require `UnmarshalRQL` at the top level even if the system uses a different DB backend. Alternatively, I can read the result into a map then unmarshal it manually into a user-provided object, copying it for the second time. Neither seems like a clean solution.

On a related note, gorethink ignores `json.Marshaler` if it's provided for a value (as opposite to a pointer). Why?

**Comment by dancannon** [comment]
You have understood the unmarshalling code correctly, RethinkDBs pseudotypes mean that the second step is required. Unfortunately it is not currently possible to add support for Unmarshaler as there is no way to skip the initial `JSON > map` step. Well that is not entirely true if a `json.Unmarshaler` is detected the intermediate "map" representation of the result could be encoded as JSON and then passed to the `
UnmarshalJSON` function however in my opinion this is much less tidy than just using `UnmarshalRQL`.

I think for now just adding the `UnmarshalRQL` function is the best solution.

**Comment by or-else** [comment]
Thanks, that makes sense. Geometry is not a problem but binary & time are. Unless you are willing to expose custom binary & time types to the user, the way sql package exposes nullable types. Which may be an acceptable tradeoff because it would substantially improve driver's performance and simplify the code base.

P.S. My current interest is more academic because I circumvented the immediate problem.

**Comment by dancannon** [comment]
In my opinion exposing custom types for the driver is even less flexible than having custom interfaces. Also while I understand that having an extra encoding step is unfortunate I think making the driver as easy to use as possible is more important for now.

For that reason I am going to close this issue for now unless anybody has any other ideas for how to add support for `json.Marshaler`/`json.Unmarshaler`. However thanks @or-else for asking a good question :)
