### ISSUE TITLE
Behaviour of calling cursor.Close() on changefeed

### ISSUE THREAD

**Issue by knowthen** [rethinkdb/rethinkdb-go#202]
Really digging this library, Thanks!

I'm seeing some odd behaviour, that's not ideal.

When I start a changefeed such as 

``` JavaScript
session, err := r.Connect(r.ConnectOpts{
    Address:  "localhost:28015",
    Database: "junk",
    MaxIdle:  1,
    MaxOpen:  1,
})
cursor, err := r.Table("item").
    Changes().Run(session)
change := make(chan r.ChangeResponse)

cursor.Listen(change)
go func() {
    for val := range change {
        fmt.Println(val)
    }
}()
time.Sleep(time.Second * 10)
cursor.Close()

```

calling `cursor.Close()` doesn't break out of the for / range loop until another table change happens.
This ends up consuming a connection and leaving the goroutine running for potentially long periods of time/ leaking.

``` JavaScript
// since I only had 1 connection in pool, this hangs even after another change event
// get's us out of the goroutine
cursor2, err := r.Table("item").
    Run(session)
var res []interface{}
cursor2.All(&res)
fmt.Println(res)
```

Am I missing something on this?

**Comment by dancannon** [comment]
Hey @knowthen,

Thanks for reporting this issue, I have replicated the issue and luckily it was a very easy fix. Unfortunately  the driver was not properly sending the `STOP` query to RethinkDB when closing the cursor.

I will release the fix shortly.

**Comment by knowthen** [comment]
Awesome, thanks!

**Comment by dancannon** [comment]
Shipped in v1
