### ISSUE TITLE
Connection pool has no free slots after first 100 req, are there tricks to debug such problems

### ISSUE THREAD

**Issue by osiloke** [rethinkdb/rethinkdb-go#206]
I have a similar issue to #171 where i bench 100 concurrent requests against my api, which is using gorethink default options, which run to completion, then i run another 100 and it errors out. Looking at the rethink log, it says that there are no free request slots, a sample of my log output is as follows

```
DEBU[0033] No conns free, opening new connection         maxOpen=0 numFree=0 numOpen=0
DEBU[0033] Opened new connection                         numFree=0 numOpen=1
DEBU[0033] Released connection                           numFree=0 numOpen=1
[GIN] 2015/07/12 - 10:22:46 | 200 |   16.345473ms | 127.0.0.1:55090 |   GET     /get_storage_schema
10:22:49.431428 WRN resource.service gorethink: no connections were available
   in: func.030(service/service.go:690)
```

If i wait a few seconds before running the next 100 bench requests, they complete. I'm putting a bunch of stack traces to see what part of my code is opening and not leading to an automatic close.

Can anyone suggest a way to debug issues like this. My api uses a general store api for accessing rethink as shown here https://gist.github.com/osiloke/36ab27c652c3c618f834. According to the docs, all the functions used should auto close. Maybe there's away to see what request is holding the connection? i.e the actual http request

**Comment by osiloke** [comment]
As i was about to give up, I realized my problem after reading this, https://groups.google.com/forum/#!topic/rethinkdb/ETxn-FkeuM0. I was trying to dynamically create tables. The create table operation is a heavy process even if the table already exists. So it was holding up the connection.

**Comment by dancannon** [comment]
Are you still having this issue @osiloke? 

Also I am a little confused as to why you can only use 100 connections if the MaxOpen option was not set (In your logs MaxOpen=0). Are there any other errors/warnings from GoRethink?

**Comment by osiloke** [comment]
Nope, don't have this error anymore. Sorry, i copied the logs for different setting.
Basically, the createtable call made everytime a request is made to check if the table existed was holding up the connection because it's such a long process and hence was tieing up resources.  
I'll close the issue, thanks
