### ISSUE TITLE
insert failed gorethink: Cannot convert STRING to SEQUENCE in

### ISSUE THREAD

**Issue by thinkong** [rethinkdb/rethinkdb-go#207]
I am currently using gorethink and created a custom primarykey as such

``` go
r.TableCreate("accounts", r.TableCreateOpts{PrimaryKey:"Accountid})
```

but when i try to insert an object as such

``` go
r.Table("accounts").Insert(MyAccountStruct{Accountid:"asdf"})
```

it gives me an error insert failed gorethink: `Cannot convert STRING to SEQUENCE in ...`

Can i not set a custom string as a primary key in gorethink? It works in the web interface for rethinkdb

**Comment by dancannon** [comment]
Hi @thinkong,

I tried reproducing the error with the queries in the issue but it worked fine for me. The error you have posted comes directly from the database and is not returned from GoRethink, also it usually is returned when there is "syntax" error in your query. Have you got any other queries that be causing this issue?

Also here is the code I ran to attempt to reproduce your issue:

``` go
package main

import (
    r "github.com/dancannon/gorethink"
)

type MyAccountStruct struct {
    Accountid string
}

func main() {
    r.SetVerbose(true)
    s, err := r.Connect(r.ConnectOpts{
        Address: "localhost:28015",
    })
    if err != nil {
        panic(err)
    }

    err = r.DB("test").TableCreate("accounts", r.TableCreateOpts{
        PrimaryKey: "Accountid",
    }).Exec(s)
    if err != nil {
        panic(err)
    }

    err = r.DB("test").Table("accounts").Insert(MyAccountStruct{
        Accountid: "asdf",
    }).Exec(s)
    if err != nil {
        panic(err)
    }
}
```

**Comment by thinkong** [comment]
I'll check on this again. Maybe I had to use Exec instead of runwrite

**Comment by thinkong** [comment]
Oh bummers I guess i was doing something stupid..
shame on me :weary: 
closing this

**Comment by dancannon** [comment]
Haha no worries! Glad to hear you have fixed your issue.
