### ISSUE TITLE
Calling filter/map after changes causes connection to timeout

### ISSUE THREAD

**Issue by let4be** [rethinkdb/rethinkdb-go#211]
I'd like to filter and map changes to a more simplified structures to reduce network loading and increase efficiency

but as soon as I chain .filter() / .map() after .changes() my connection starts to timeout(10 second as I specified during creating a connection)

I also saw this one for the .NET driver so gorethink might have a similar issue
mfenniak/rethinkdb-net#193

Thanks!

**Comment by dancannon** [comment]
Replied in rethinkdb/rethinkdb#4642

> Currently the driver has a global timeout setting which is used for both connecting and queries. I think that having timeouts on queries makes sense but clearly it needs to be possible to ignore this for changefeeds. I will look into adding this soon.
> 
> For now I think @danielmewes is correct in saying that removing the timeout for now is the best solution.

**Comment by dancannon** [comment]
I have updated the driver to split out the timeout options into `Timeout`, `RunTimeout` and `WriteTimeout`. See the release notes for more info.
