### ISSUE TITLE
"no connections were available" error with RethinkDB 2.1

### ISSUE THREAD

**Issue by oliver006** [rethinkdb/rethinkdb-go#212]
I'm running into `gorethink: no connections were available` errors after updating RethinkDB from 2.0.x to 2.1.0. I use gorethink release 1.0.0 (https://github.com/dancannon/gorethink/releases/tag/v1.0.0).

When I start the process, everything runs fine but after about ~45 mins all requests fail with that error.

Unfortunately, aside from the above error, I got not much else. I'm running with:
- `setVerbose(true)` but no debug output on the console (btw, that error is returned in two places, if verbose==true I'd expect the library to log where it occured)
- `DiscoverHosts: true` in ConnectOpts allthough I only have one host in my db setup. This ran fine for months now but could this be a problem with the new raft-based cluster HA stuff?
- I changed MaxIdle and MaxOpen from eg. 20 to 40 to unlimited (0) - didn't help. I monitored the connection count and the max number of connections is never reached so it looks like there's a bug with how gorethink accounts for the number of available connections.

Let me know if there is another branch I can test or any other info I can provide.

**Comment by dancannon** [comment]
Hi, I have not yet tested gorethink with 2.1 but from your tests it sounds like the system status tables have changed in a way that makes the driver incompatible. 

I hope to have a fix released by sometime next week but until then I recommend downgrading.

**Comment by oliver006** [comment]
Hmmkay, let me try that, fortunately someone else just asked about downgrading here: https://groups.google.com/forum/#!topic/rethinkdb/7a_BLHeYRJQ
Let's hope it works.

Any chance you could put a big warning in the README to let people know that 2.1 isn't supported yet?

**Comment by dancannon** [comment]
Sure, although the readme already contains the currently supported RethinkDB version.

**Comment by oliver006** [comment]
Thanks man, appreciate it.The downgrade was a bit a hassle as I had to dump and restore the data and during restore creating of the secondary indices failed and I had to do it manually.

**Comment by dancannon** [comment]
This should now be fixed, let me know if you have any further issues with RethinkDB 2.1

**Comment by 1lann** [comment]
You might also want to remove the: "**Driver does not currently support RethinkDB 2.1, update coming soon!**" warning in the README.

I really appreciate your work, what you're doing is awesome :)
