### ISSUE TITLE
Possible race condition

### ISSUE THREAD

**Issue by let4be** [rethinkdb/rethinkdb-go#213]
I'm extensively using gorethink and when ran wirh -race found out this:

WARNING: DATA RACE

Read by goroutine 23:

  github.com/dancannon/gorethink.(_Cluster).GetRandomNode()
      C:/Users/dev/IdeaProjects/gotest/src/github.com/dancannon/gorethink/cluster.go:328 +0x19b
  github.com/dancannon/gorethink.(_Cluster).Query()
      C:/Users/dev/IdeaProjects/gotest/src/github.com/dancannon/gorethink/cluster.go:55 +0x54
  github.com/dancannon/gorethink.(*Session).Query()
      C:/Users/dev/IdeaProjects/gotest/src/github.com/dancannon/gorethink/session.go:175 +0x91
  github.com/dancannon/gorethink.Term.Run()
      C:/Users/dev/IdeaProjects/gotest/src/github.com/dancannon/gorethink/query.go:215 +0x122
  github.com/dancannon/gorethink.Term.RunWrite()
      C:/Users/dev/IdeaProjects/gotest/src/github.com/dancannon/gorethink/query.go:228 +0xdf
...

down the stack is my call to gorethink's `RunWrite(data.session)`

Previous write by goroutine 10:

  sync/atomic.StoreInt64()
      c:/go/src/runtime/race_amd64.s:213 +0xc
  github.com/dancannon/gorethink.(_Node).ResetHealth()
      C:/Users/dev/IdeaProjects/gotest/src/github.com/dancannon/gorethink/node.go:209 +0x51
  github.com/dancannon/gorethink.(_Node).Refresh()
      C:/Users/dev/IdeaProjects/gotest/src/github.com/dancannon/gorethink/node.go:199 +0x62f
  github.com/dancannon/gorethink.func┬╖005()
      C:/Users/dev/IdeaProjects/gotest/src/github.com/dancannon/gorethink/node.go:52 +0x134

Any idea what could cause this?

**Comment by dancannon** [comment]
Looks like this race condition is unrelated to anything you are doing and is an internal issue. Ill look into it later today.

Thanks for reporting the issue!

**Comment by let4be** [comment]
Thanks Daniel!

**Comment by let4be** [comment]
Looks like it may also lead to a possible dead lock, I'm having hard time to catch why my program sometimes stucks and one of suspects is gorethink

One of important goroutines randomly gets locked inside gorethink:

```
net.(*pollDesc).Wait(0xc082543c70, 0x72, 0x0, 0x0)
        c:/go/src/net/fd_poll_runtime.go:84 +0x4e
net.(*ioSrv).ExecIO(0xc082046050, 0xc082543b60, 0x869b80, 0x7, 0x950fd0, 0x0, 0x
0, 0x0)
        c:/go/src/net/fd_windows.go:188 +0x305
net.(*netFD).Read(0xc082543b00, 0xc0822d7000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
        c:/go/src/net/fd_windows.go:470 +0x180
net.(*conn).Read(0xc082046818, 0xc0822d7000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
        c:/go/src/net/net.go:121 +0xe3
bufio.(*Reader).fill(0xc082238480)
        c:/go/src/bufio/bufio.go:97 +0x1d5
bufio.(*Reader).ReadSlice(0xc082238480, 0x411800, 0x0, 0x0, 0x0, 0x0, 0x0)
        c:/go/src/bufio/bufio.go:295 +0x25e
bufio.(*Reader).ReadBytes(0xc082238480, 0xc082046800, 0x0, 0x0, 0x0, 0x0, 0x0)
        c:/go/src/bufio/bufio.go:374 +0xd9
github.com/dancannon/gorethink.(*Connection).readHandshakeSuccess(0xc0822d4240,
0x0, 0x0)
        C:/Users/dev/IdeaProjects/gotest/src/github.com/dancannon/gorethink/conn
ection_helper.go:54 +0x9e
github.com/dancannon/gorethink.NewConnection(0xc0822b28a0, 0xf, 0xc08200a100, 0x
c0822b28a0, 0x0, 0x0)
        C:/Users/dev/IdeaProjects/gotest/src/github.com/dancannon/gorethink/conn
ection.go:78 +0x54c
github.com/dancannon/gorethink.(*Pool).conn(0xc08206e280, 0xc08259ba70, 0x0, 0x0
)
        C:/Users/dev/IdeaProjects/gotest/src/github.com/dancannon/gorethink/pool
.go:269 +0x516
github.com/dancannon/gorethink.(*Pool).query(0xc08206e280, 0x1, 0x0, 0xc08268386
0, 0xc08259b9b0, 0xc0821570d8, 0x0, 0x0)
        C:/Users/dev/IdeaProjects/gotest/src/github.com/dancannon/gorethink/pool
.go:511 +0x47
github.com/dancannon/gorethink.(*Pool).Query(0xc08206e280, 0x1, 0x0, 0xc08268386
0, 0xc08259b9b0, 0xc08208e0b0, 0x0, 0x0)
        C:/Users/dev/IdeaProjects/gotest/src/github.com/dancannon/gorethink/pool
.go:503 +0x9b
github.com/dancannon/gorethink.(*Node).Query(0xc0820c6000, 0xc000000001, 0x0, 0x
c082683860, 0xc08259b9b0, 0x0, 0x0, 0x0)
        C:/Users/dev/IdeaProjects/gotest/src/github.com/dancannon/gorethink/node
.go:121 +0xaf
github.com/dancannon/gorethink.(*Cluster).Query(0xc08200c300, 0xc000000001, 0x0,
 0xc082683860, 0xc08259b9b0, 0x0, 0x0, 0x0)
        C:/Users/dev/IdeaProjects/gotest/src/github.com/dancannon/gorethink/clus
ter.go:60 +0xa3
github.com/dancannon/gorethink.(*Session).Query(0xc08205b1d0, 0x1, 0x0, 0xc08268
3860, 0xc08259b9b0, 0x0, 0x0, 0x0)
        C:/Users/dev/IdeaProjects/gotest/src/github.com/dancannon/gorethink/sess
ion.go:175 +0x6e
github.com/dancannon/gorethink.Term.Run(0x867520, 0x7, 0x3700000000, 0x0, 0x0, 0
xc0822d41b0, 0x2, 0x2, 0xc08259b920, 0xc08205b1d0, ...)
        C:/Users/dev/IdeaProjects/gotest/src/github.com/dancannon/gorethink/quer
y.go:215 +0x10f
github.com/dancannon/gorethink.Term.RunWrite(0x867520, 0x7, 0x3700000000, 0x0, 0
x0, 0xc0822d41b0, 0x2, 0x2, 0xc08259b920, 0xc08205b1d0, ...)
        C:/Users/dev/IdeaProjects/gotest/src/github.com/dancannon/gorethink/quer
y.go:228 +0xba
```

From user side it just looks like RunWrite call randomly never returns, or returns with huge delays(minutes)

**Comment by dancannon** [comment]
From the stacktrace it just looks like that goroutine is stuck waiting to connect to the database, maybe try setting the Timeout property when connecting and see if that causes your program to become unstuck.

**Comment by kofalt** [comment]
The [go race detector](https://blog.golang.org/race-detector) is a marvellous thing! 
I have seen it catch potentially disastrous bugs at a very early stage.

I would highly recommend a dev branch that turns on the flag in CI and then gets CI to pass :)

**Comment by dancannon** [comment]
Agreed, I have started work in this branch https://github.com/dancannon/gorethink/tree/feature/safe_cursor. The tests dont pass completely yet but its a start.

**Comment by let4be** [comment]
why would we need cursors synchronization enforced by gorethink? I normally use data within the same goroutine or use channels instead...

**Comment by dancannon** [comment]
For most queries that is the case but with the addition of changefeeds it is quite common to have an iterator in one goroutine and close the channel on another. 

I have also included the fix for this issue in this branch.

**Comment by let4be** [comment]
Just my imho on cursors: we could simply let the user decide when to sync and how to do it(mutex, rwmutex or maybe a channel)

**Comment by dancannon** [comment]
Given some of the features that I would like to add to the driver in future I think ensuring that cursors and sessions are safe for concurrent use is important.

I have updated the driver with the changes discussed and updated the CI scripts to run the tests with the race detector enabled.
