### ISSUE TITLE
ErrConnectionClosed isn't ever returned

### ISSUE THREAD

**Issue by 1lann** [rethinkdb/rethinkdb-go#214]
If the connection to the server is closed remotely, and there is an attempt to make a query, either an io.EOF error  (upon getting a response) is returned or `gorethink: gorethink: write tcp 127.0.0.1:28015: broken pipe` (upon writing the query) is returned from `.Run(session)`.

I would expect that ErrConnectionClosed would be returned instead, but it isn't ever used throughout the library.

**Comment by dancannon** [comment]
`ErrConnectionClosed` is returned when a query is executed using a connection/session that has been closed using `Close` not when the connection is closed by the server. 

The driver could possibly parse the returned errors and close the connection if certain errors were returned but I dont think that is currently necessary.

**Comment by 1lann** [comment]
Hm, currently I get a `panic: runtime error: invalid memory address or nil pointer dereference` if I attempt to `.Run(session)` when the session had been closed earlier with `session.Close()`. Querying a closed connection will theoretically just return nil as an error: https://github.com/dancannon/gorethink/blob/master/connection.go#L107-L110

Did you mean to return ErrConnectionClosed instead?

**Comment by dancannon** [comment]
Hmm ok that is an issue! Sorry for missing that earlier. I will look into that now.

**Comment by dancannon** [comment]
This should now be fixed, thanks again.
