### ISSUE TITLE
Problem importing gopkg.in/dancannon/rethinkdb.v1

### ISSUE THREAD

**Issue by bradleyankrom** [rethinkdb/rethinkdb-go#217]
I receive the following errors when running `go get gopkg.in/dancannon/rethinkdb.v1`:

```
# gopkg.in/dancannon/gorethink.v1
../../../../../gopkg.in/dancannon/gorethink.v1/query_math.go:190: undefined: ql2.Term_ROUND
../../../../../gopkg.in/dancannon/gorethink.v1/query_math.go:195: undefined: ql2.Term_ROUND
../../../../../gopkg.in/dancannon/gorethink.v1/query_math.go:201: undefined: ql2.Term_CEIL
../../../../../gopkg.in/dancannon/gorethink.v1/query_math.go:207: undefined: ql2.Term_CEIL
../../../../../gopkg.in/dancannon/gorethink.v1/query_math.go:213: undefined: ql2.Term_FLOOR
../../../../../gopkg.in/dancannon/gorethink.v1/query_math.go:219: undefined: ql2.Term_FLOOR
```

The repository is downloaded, however. When I try to run or build a project that imports the gopkg.in repo, I see the same errors about undefined ql2.Term_\* values.

I am able to successfully build and run when importing the github repository.

**Comment by dancannon** [comment]
Seems to work for me, could you run `go get -u gopkg.in/dancannon/gorethink.v1` instead and let me know if that fixes your issues?

**Comment by bradleyankrom** [comment]
Works for me now; not sure what the issue was before. Thanks.
