### ISSUE TITLE
Dont work Update

### ISSUE THREAD

**Issue by Gitart** [rethinkdb/rethinkdb-go#218]
Hi !

I have :
Ver rethinkdb : RethinkDB 2.1.2

My script :

`r.DB("Test").Table("a").Update(map[string]interface{}{"Res": r.Row.Field("PRICE").Mul(2),r.UpdateOpts{"soft", false, true}})`

My result in column "Res" :
`{...}`

Please help me.

**Comment by dancannon** [comment]
Hi @Gitart,

I have created a simple test query with the query you have included above and it seems to work for me so I would guess that this issue is with your query and how you have structured your data, would it be possible to see an example document?

**Comment by Gitart** [comment]
This my func :

``` go
UpdOpts:= r.UpdateOpts{"soft", false, true}

type MT map[string]interface{} 

r.DB("Test").Table("a").Delete().Run(sessionArray[0])

r.DB("Test").Table("a").Insert(MT{"PRICE": 25}).Run(sessionArray[0])
r.DB("Test").Table("a").Insert(MT{"PRICE": 26}).Run(sessionArray[0])
r.DB("Test").Table("a").Insert(MT{"PRICE": 27}).Run(sessionArray[0])
r.DB("Test").Table("a").Update(MT{"Res":   r.Row.Field("PRICE").Mul(2)}, UpdOpts).Run(sessionArray[0])
```

**Comment by dancannon** [comment]
Hey, I have found the source of the issue, unfortunately in the most recent update I made a change to the encoding that breaks type aliasing, for example calling `r.DB("Test").Table("a").Update(MT{"Res":   r.Row.Field("PRICE").Mul(2)}, UpdOpts)` will not work but `r.DB("Test").Table("a").Update(map[string]interface{}{"Res":   r.Row.Field("PRICE").Mul(2)}, UpdOpts)` will.

I will look into releasing a fix, thanks for reporting the issue.

**Comment by dancannon** [comment]
This should now be fixed, could you let me know if you still have the issue?

**Comment by Gitart** [comment]
Yes, and I found this . Very thanks. I am sure I will keep up to date. Yes of course - will be reporting.

**Comment by Gitart** [comment]
Good day !
All OK !!!  
Now i can  use my short construction :  type MT map[string]interface{} ! 
Many thanks !!!
