### ISSUE TITLE
reflect: call of reflect.Value.SetUint on ptr Value

### ISSUE THREAD

**Issue by pzduniak** [rethinkdb/rethinkdb-go#219]
I am unable to unmarshal a ReQL result into the following struct:
https://github.com/pgpst/pgpst/blob/master/pkg/models/key.go#L30-L43

The error is `reflect: call of reflect.Value.SetUint on ptr Value`. Seems that the unmarshaler isn't able to distinguish between `uint` and `*uint`.

**Comment by dancannon** [comment]
Thanks for reporting this issue. I have found the source of the bug but it is taking a while to properly fix. I will keep you updated.

**Comment by dancannon** [comment]
This should now be fixed in the `develop` branch, I have added a new test but if you could ensure that it solves your issue that would be great, thanks.

**Comment by dancannon** [comment]
This is now also merged to `master`. Thanks for reporting the bug.
