### ISSUE TITLE
Connect Timeout and TLS example

### ISSUE THREAD

**Issue by mdmdmdmd** [rethinkdb/rethinkdb-go#225]
Dan:

Any chance you could provide an example of the Timeout and TLS parameter on connect()?

I started a Timeout issue, but they instructed me to post here.

Here is the link:

https://github.com/rethinkdb/rethinkdb/issues/4800

Nice job with the go driver.

Thanks,

md

**Comment by dancannon** [comment]
Hi @mdmdmdmd!

The issue with the timeout should now be fixed in the most recent version (released yesterday). If not let me know and I will have another look.

Regarding TLS parameters the driver accepts a `*tls.Config` field in the `ConnectOpts`. for example:

``` go
const rootPEM = `...`

roots := x509.NewCertPool()
ok := roots.AppendCertsFromPEM([]byte(rootPEM))
if !ok {
    panic("failed to parse root certificate")
}

sess, err := r.Connect(r.ConnectOpts{
    Address: "localhost:28015",
    TLS: &tls.Config{
        RootCAs: roots,
    },
})
```

**Comment by dancannon** [comment]
Even better, compose just wrote an article on using SSL with RethinkDB and included some instructions about GoRethink. https://www.compose.io/articles/rethinkdb-and-ssl-think-secure
