### ISSUE TITLE
r.Cursor.Next() no longer sets pointer to nil on document not found

### ISSUE THREAD

**Issue by ftKnox** [rethinkdb/rethinkdb-go#226]
Documents that don't exist no longer set the pointer to nil when using r.Cursor.Next(). Seems to come from this commit c52349e8e587dbbffe482e9404420d310b2015a7 in func decode()

Changing decode from

```
 func decode(dv, sv reflect.Value) {
       if dv.IsValid() {
               dv = indirect(dv, false)
               dv.Set(reflect.Zero(dv.Type()))
       }

        valueDecoder(dv, sv)(dv, sv)
 }
```

back to

```
 func decode(dv, sv reflect.Value) {
    valueDecoder(dv, sv)(dv, sv)
 }
```

restores previous behavior. I don't know the codebase well enough, to determine if this breaks other things.

test case (shortened for brevity) -- Also note that using cur.One(&doc) works as expected and returns nil

```
type doc struct {
  id string
}

cur, err := r.Table("test").Get(NonExistingDocId).Run(sess)
if err != nil {
  panic(fmt.Sprintf("Could not check for existing document [ERR:%s]", err.Error()))
}
cur.Next(&doc)
if doc == nil {
  fmt.Printf("Document not found!\n")
}
```

**Comment by dancannon** [comment]
Sorry for taking so long to look into this, I will look into fixing this issue now.

**Comment by dancannon** [comment]
I have just pushed an update to develop which should fix this issue, I hope to have it pushed to master within a couple of days.

**Comment by ftKnox** [comment]
No worries, it was an easy work around. I tested the develop branch, and it looks like it's fixed. Thanks for getting to this!

**Comment by dancannon** [comment]
Merged to master
