### ISSUE TITLE
ReadMode usage ?

### ISSUE THREAD

**Issue by FlagSystemes** [rethinkdb/rethinkdb-go#227]
since we can't use UseOutdated anymore.

**Comment by dancannon** [comment]
It looks like I have completely misunderstood how the `ReadMode` flag worked and implemented incorrectly. I will add the `TableOpts` struct.

Thanks for pointing out the issue.

**Comment by dancannon** [comment]
ReadMode can be used like this, I have removed the incorrect options in `RunOpts` and `ExecOpts`:

``` go
cursor, err := r.Table("test", r.TableOpts{
    ReadMode: "outdated",
}).Run(session)
```
