### ISSUE TITLE
Changes(), cursor, and Close(),

### ISSUE THREAD

**Issue by eatnut** [rethinkdb/rethinkdb-go#232]
The normal cursor can be closed properly:

``` go
session, _ := r.Connect(r.ConnectOpts{Address: "localhost:28015"})          
c, _ := r.DB("test").Table("test").Run(session)                             
c.Close() 
```

The cursor from change feed cannot be closed, and will block code

``` go
session, _ := r.Connect(r.ConnectOpts{Address: "localhost:28015"})          
c, _ := r.DB("test").Table("test").Changes().Run(session) // add Changes()                             
c.Close()  // block
```

**Comment by dancannon** [comment]
Thanks for the bug report, I think I have a fix and hope to merge to release a new version soon.

**Comment by eatnut** [comment]
And thanks for the awesome package!

**Comment by dancannon** [comment]
Thanks :)

**Comment by dancannon** [comment]
This should now be fixed, just waiting on @navy1125 to confirm regarding his comment on https://github.com/dancannon/gorethink/commit/dc37a99826333444d375145585ec414312a4c955#commitcomment-13573314.

Please note that c877782d is the actual fix.
