### ISSUE TITLE
pubsub

### ISSUE THREAD

**Issue by truongsinh** [rethinkdb/rethinkdb-go#236]
Ref https://rethinkdb.com/docs/publish-subscribe/javascript/

Can we port the above example to this driver, with 3 namespaces:
- An `Exchange` is created by both publishers and subscribers. Publishers put messages into the exchange, and subscribers listen to messages on the exchange.
- A `Topic` is used by publishers. It contains some key that contains meta-data about the messages.
- A `Queue` is used by consumers. It has two purposes:
  - To buffer messages that the subscriber hasn’t consumed yet (this buffering is actually done in the database server)
  - To filter messages from the Exchange by their Topic (again, the server does this filtering)

**Comment by dancannon** [comment]
This sounds like a great project but I don't think I have the time to work on this right now and if created should probably remain separate from GoRethink. If anybody starts something like this I will definitely try to support it.

For now I will close this issue, Sorry!
