### ISSUE TITLE
Question: Is it possible to create a table using the session's configured database?

### ISSUE THREAD

**Issue by nickcarenza** [rethinkdb/rethinkdb-go#238]
Do i have to do

```
DB("name").TableCreate("name").RunWrite(session)
```

or if I specified a database in the ConnectOpts as in the example, can I omit it?

```
...TableCreate("name").RunWrite(session)
```

these result in errors

```
DB().TableCreate("name")... (gorethink: Expected 1 argument but found 0)
gorethink.Term.TableCreate("name")... (not enough arguments in call to gorethink.Term.TableCreate)
```

**Comment by dancannon** [comment]
This looks like a bug in the driver, I will look into it and report back. Thanks!

**Comment by dancannon** [comment]
The root terms were missing, these are now added in `v1.1.4`. Thanks for pointing it out.

**Comment by nickcarenza** [comment]
Np thanks for the quick fix

**Comment by dancannon** [comment]
Jus just to clarify you don't need the `DB()` call now.
