### ISSUE TITLE
2.2.x Support

### ISSUE THREAD

**Issue by leetal** [rethinkdb/rethinkdb-go#247]
Are there any planned updates for the newly released 2.2.0 version of RethinkDB?

I'm really excited about the new way atomic changefeeds are handled, as well as the two new ReQL commands. :+1:

**Comment by dancannon** [comment]
Support for 2.2 is coming soon! @SKatiyar has put some great work into some of the new RQL terms and I would also like to spend some time overhauling the cluster connection code.

Since you have created this issue I will keep it open until the new version is released.

**Comment by dancannon** [comment]
2.2 support is now in master!

**Comment by joeblew99** [comment]
Thanks Dan.
