### ISSUE TITLE
Unmarshaling response 1e+06 into int64

### ISSUE THREAD

**Issue by dewey4iv** [rethinkdb/rethinkdb-go#250]
When attempting to unmarshal any value over 1e+06 into a int64 (or lesser precision) I run into an error. I realize this is probably more an issue with the stdlib's json package -- but is there any way I could patch the driver to not return scientific notation? Thanks! I appreciate any help you can offer.

**Comment by dancannon** [comment]
Try using `UseJSONNumber` instead (https://github.com/dancannon/gorethink/blob/master/session.go#L56). This scans the integer into `encoding/json.Number` (https://golang.org/pkg/encoding/json/#Number)

**Comment by dewey4iv** [comment]
Updating the driver and adding that option yields another error: `interface conversion: interface is json.Number, not float64`

**Comment by dancannon** [comment]
Hmm not sure what is going on here, I ran the same code and was able to connect without any problems. I would only expect that error when MaxIdle is less than MaxOpen. Can you post a full code example + the git hash of gorethink and fatih/pool that you are using?

**Comment by dewey4iv** [comment]
Sorry -- changed that as soon as I was able to figure out what was wrong there. What am I missing/need to change in order to use the gorethink package with that option enabled?

**Comment by dancannon** [comment]
Although not ideal you would need to change your data structure to use `json.Number` instead of `int64` and then use `Int64()` function to access the int64. 

Reading your original post I dont think this is what you are looking for, I will think about this and try and come up with a better solution if possible.

**Comment by dewey4iv** [comment]
Thanks -- I appreciate the help. Is there a way (even if temporary, or i have to temporarily fork) to force the driver to Unmarshal into an int using the full size of the value instead of into scientific notation?

**Comment by dancannon** [comment]
I just ran this script on my laptop and got the following result. This was ran using Go 1.5, if you are using an older version maybe try upgrading and see if that fixes your issue?

``` go
package main

import (
    "log"

    r "github.com/dancannon/gorethink"
    "github.com/davecgh/go-spew/spew"
)

type A struct {
    ID int64 `gorethink:"id"`
    I  int64
}

func main() {
    session, err := r.Connect(r.ConnectOpts{
        Address: "localhost:28015",
        MaxIdle: 30,
        MaxOpen: 50,
    })
    if err != nil {
        log.Fatalln(err.Error())
    }

    var v A

    err = r.DB("test").Table("test250").Insert(A{
        ID: 1,
        I:  9000000000000000,
    }, r.InsertOpts{
        Conflict: "replace",
    }).Exec(session)
    if err != nil {
        log.Fatalln(err.Error())
    }

    c, err := r.DB("test").Table("test250").Get(1).Run(session)
    if err != nil {
        log.Fatalln(err.Error())
    }

    err = c.One(&v)
    if err != nil {
        log.Fatalln(err.Error())
    }

    spew.Dump(v)
}

```

```
(main.A) {
 ID: (int64) 1,
 I: (int64) 9000000000000000
}
```
