### ISSUE TITLE
Feature request: Ability to identify returned Error identities from RethinkDB to Golang domain

### ISSUE THREAD

**Issue by eliezedeck** [rethinkdb/rethinkdb-go#253]
At this time, the returned `error` object doesn't offer the ability to identify the kind of the error. Because of this, one needs to manually test the error string if it contains a specific set of strings, for example (testing if the error mentions about Table or Database already existing):

``` go
if strings.Contains(err.Error(), "already exists") {
  // I may choose to ignore errors about stuffs already existing
}
```

This is error-prone and it's easy to mistake the comparison string. Not only that, but the RethinkDB team may decide in the future that the message needs to be changed and all programs relying on the message to contain that specific "already exists" string will all fail silently.

As mentioned on Gitter by @dancannon himself, the error from RethinkDB contains an "e" field which is likely to be the unique error identifier code. This field provides several benefits:
- Accurate identity of the error and could possibly identify the difference between a Database already existing and a Table already existing
- Easier to compare to, rather than involving memory compare for strings comparison.
- Has a lower probability of change because it's likely deep from the C++ RethinkDB API.

There needs to be a way to be able to get detailed information about this error up to Golang domain.

**Comment by dancannon** [comment]
This should now be fixed in v1.3.0. I implemented the same error types as in the official drivers. This allows you to do a type switch to check which error is returned.
