### ISSUE TITLE
gorethink panics in cursor.Listen

### ISSUE THREAD

**Issue by gthmac** [rethinkdb/rethinkdb-go#257]
Hi Dan,

first of all, thanks much for gorethink. It makes my life so much easier. Awesome stuff.

I am using it in a large, scale out environment and am making use of the cursor's Listen function for Changefeeds a lot. That being said, I am encountering panics when the query I am watching for is seeing a lot of concurrent changes.

I drilled into it and figured out the following:

The crash happens in cursor.go:514, i. e. the expand-routine.
The value of q.popi >= len(q.elems) (i. e. in my debug outputs which I added, len(q.elems) == 0 and q.popi == 1) which leads the copy-builtin to crash.

Removed the cursor.Listen from my code for now and am back to polling, so I hope you will find time to look into it.

Thanks,
Gunther

P. S.: The Listen-cursor is used only in a single goroutine (just to make sure we remove the obvious first question from the equation :-) ).

**Comment by dancannon** [comment]
Hey, sorry you are having this issue. Its kind of worrying that the queue data structure is panicking. I may just replace this code with something simpler.

Since this looks like a pretty serious issue I hope to have a fix released very soon. Thanks for submitting the issue.

**Comment by omeid** [comment]
Please post the panic message if possible.

**Comment by gthmac** [comment]
Dan,

thanks much for your prompt reply. Really appreciated.

As 'omeid' requested the panic message, please find it below. I don't think it is going to tell you guys any more than what I had described in my initial submission.

Based on the panic message, I had added some tracing output to Dan's code to at least understand what exactly was going on.

Again, thanks much :-)

```
panic: runtime error: slice bounds out of range

goroutine 53 [running]:
github.com/dancannon/gorethink.(*queue).expand(0xc8200b3ad8)
    /Users/gth/code/go/src/bitbucket.org/cloudintel/vatomizer/Godeps/_workspace/src/github.com/dancannon/gorethink/cursor.go:514 +0x2de
github.com/dancannon/gorethink.(*queue).Push(0xc8200b3ad8, 0x50b9a0, 0xc820463ca0)
    /Users/gth/code/go/src/bitbucket.org/cloudintel/vatomizer/Godeps/_workspace/src/github.com/dancannon/gorethink/cursor.go:476 +0x36
github.com/dancannon/gorethink.(*Cursor).extendLocked(0xc8200b3a40, 0xc8201c83f0)
    /Users/gth/code/go/src/bitbucket.org/cloudintel/vatomizer/Godeps/_workspace/src/github.com/dancannon/gorethink/cursor.go:450 +0x11b
github.com/dancannon/gorethink.(*Cursor).extend(0xc8200b3a40, 0xc8201c83f0)
    /Users/gth/code/go/src/bitbucket.org/cloudintel/vatomizer/Godeps/_workspace/src/github.com/dancannon/gorethink/cursor.go:445 +0x7e
github.com/dancannon/gorethink.(*Connection).processPartialResponse(0xc820227130, 0xc800000002, 0x1, 0x0, 0x0, 0x0, 0x0, 0xc8201c83f0, 0x8, 0xc, ...)
    /Users/gth/code/go/src/bitbucket.org/cloudintel/vatomizer/Godeps/_workspace/src/github.com/dancannon/gorethink/connection.go:324 +0x30f
github.com/dancannon/gorethink.(*Connection).processResponse(0xc820227130, 0xc800000002, 0x1, 0x0, 0x0, 0x0, 0x0, 0xc8201c83f0, 0x0, 0x7, ...)
    /Users/gth/code/go/src/bitbucket.org/cloudintel/vatomizer/Godeps/_workspace/src/github.com/dancannon/gorethink/connection.go:265 +0x230
github.com/dancannon/gorethink.(*Connection).Query(0xc820227130, 0x2, 0x1, 0x0, 0x0, 0x0, 0x0, 0xc820464680, 0x4dbba0, 0x0, ...)
    /Users/gth/code/go/src/bitbucket.org/cloudintel/vatomizer/Godeps/_workspace/src/github.com/dancannon/gorethink/connection.go:148 +0x3d5
github.com/dancannon/gorethink.(*Cursor).fetchMore(0xc8200b3a40, 0x0, 0x0)
    /Users/gth/code/go/src/bitbucket.org/cloudintel/vatomizer/Godeps/_workspace/src/github.com/dancannon/gorethink/cursor.go:416 +0x139
github.com/dancannon/gorethink.(*Cursor).loadNextLocked(0xc8200b3a40, 0x4dbba0, 0xc82008b2c0, 0xc82008b2c0, 0x0, 0x0)
    /Users/gth/code/go/src/bitbucket.org/cloudintel/vatomizer/Godeps/_workspace/src/github.com/dancannon/gorethink/cursor.go:192 +0x17c
github.com/dancannon/gorethink.(*Cursor).Next(0xc8200b3a40, 0x4dbba0, 0xc82008b2c0, 0x4dbba0)
    /Users/gth/code/go/src/bitbucket.org/cloudintel/vatomizer/Godeps/_workspace/src/github.com/dancannon/gorethink/cursor.go:164 +0x91
github.com/dancannon/gorethink.(*Cursor).Listen.func1(0x4f7e00, 0xc820203020, 0xc8200b3a40)
    /Users/gth/code/go/src/bitbucket.org/cloudintel/vatomizer/Godeps/_workspace/src/github.com/dancannon/gorethink/cursor.go:348 +0x19d
created by github.com/dancannon/gorethink.(*Cursor).Listen
    /Users/gth/code/go/src/bitbucket.org/cloudintel/vatomizer/Godeps/_workspace/src/github.com/dancannon/gorethink/cursor.go:357 +0x49
```

**Comment by dancannon** [comment]
This should now be fixed in v1.3.0, I replaced the queue data structure which a simpler slice as it keeps the code simpler.

Thanks for reporting the issue.

**Comment by gthmac** [comment]
Hi Dan,

wow, that was fast. Dared to look at the code changes, I do like the
increased simplicity, if you allow me to say so.
I will play with the new code and run it through my test harness here, most
likely tomorrow and will provide you with feedback, if you wish so.

Thanks very much one more time, I really do appreciate your work.

Best,
Gunther

2016-01-11 22:08 GMT+01:00 Daniel Cannon notifications@github.com:

**Comment by gthmac** [comment]
Hi Dan,

I hope my note finds you well and you had some relaxing holidays in
between, Dan.

It took longer than I had hoped and planned to stress-test your new code. I
finally did it today and it crashed after two minutes again:

---

panic: runtime error: invalid memory address or nil pointer dereference

[signal 0xb code=0x1 addr=0x20 pc=0x5592df]

goroutine 62 [running]:

github.com/dancannon/gorethink.(*Cursor).loadNextLocked(0xc82045e6e0,
0x9bb8c0, 0xc8202da280, 0xc8202da280, 0x0, 0x0)

```
    /home/centos/go/src/
```

bitbucket.org/cloudintel/vatomizer/Godeps/_workspace/src/github.com/dancannon/gorethink/cursor.go:211
+0x41f

github.com/dancannon/gorethink.(*Cursor).Next(0xc82045e6e0, 0x9bb8c0,
0xc8202da280, 0x9bb8c0)

```
    /home/centos/go/src/
```

bitbucket.org/cloudintel/vatomizer/Godeps/_workspace/src/github.com/dancannon/gorethink/cursor.go:166
+0x91

github.com/dancannon/gorethink.(*Cursor).Listen.func1(0x9db4e0,
0xc82047f800, 0xc82045e6e0)

```
    /home/centos/go/src/
```

bitbucket.org/cloudintel/vatomizer/Godeps/_workspace/src/github.com/dancannon/gorethink/cursor.go:352
+0x19d

created by github.com/dancannon/gorethink.(*Cursor).Listen

```
    /home/centos/go/src/
```

bitbucket.org/cloudintel/vatomizer/Godeps/_workspace/src/github.com/dancannon/gorethink/cursor.go:361
+0x49

---

I just uncommented my "change listener" in my code and it crashed basically
right away.

I commented it back out again as even my dev and test env are pretty busy.
I will try to setup a separate env to dig deeper and file a proper bug
report, but I wanted to give you a heads-up.

Here is the code snippet by the way that causes all the issues (just FYI as
seeing it might trigger eventually something :-) ):

...

// do we need to wait for the result?

if actionEntry.Wait {

/*

mychan := make(chan events.DocChange)

// start the changeFeed from DB

cursor, dberr := r.Table(t.EventTable).Get(id).Changes().Run(cfg.EventDB)

if dberr != nil {

errmsg := fmt.Sprintf("%+v", dberr)

cilog.Log(sys.ERROR, cierrors.LogError(&API_ERR_DB_GET, errmsg))

replyWithError(c, &API_ERR_DB_GET)

return

}

cursor.Listen(mychan)

defer cursor.Close()

var change events.DocChange

*/

var res t.VEvent

for done := false; !done; {

select {

/*

case change = <-mychan:

_ = change

*/

case <-time.After(time.Duration(10) \* time.Millisecond):

_ = done

}

resp, dberr := r.Table(t.EventTable).Get(id).Run(cfg.EventDB)

if dberr != nil {

errmsg := fmt.Sprintf("%+v", dberr)

cilog.Log(sys.ERROR, cierrors.LogError(&API_ERR_DB_GET, errmsg))

replyWithError(c, &API_ERR_DB_GET)

return

}

defer resp.Close()

if resp.IsNil() {

continue

}

dberr = resp.One(&res)

if dberr != nil {

errmsg := fmt.Sprintf("%+v", dberr)

cilog.Log(sys.ERROR, cierrors.LogError(&API_ERR_DB_GET, errmsg))

replyWithError(c, &API_ERR_DB_GET)

return

}

if res.Status != string(events.EventClosed) {

continue

}

done = true

}

....

I am basically waiting for a single record to change on my "event-bus"
which I am (ab)using rethinkdb for in a quite big multinode setup which
works perfectly fine, but just not with change feeds which I would
obviously prefer over the stupid polling.

Any ideas?

Have a great day.

Cheers,

Gunther

2016-01-12 2:06 GMT+01:00 Gunther Thiel gunther.thiel@gmail.com:
