### ISSUE TITLE
non deterministic error with sometimes responses have no primary key field. 

### ISSUE THREAD

**Issue by ghost** [rethinkdb/rethinkdb-go#259]
This is very weird, in that it is non deterministic, and i cant see any sort of pattern

golang 1.5.2, osx

Basically i have a simple golang server that returns json to a web front end, but every 10th or 8th call, returns with all the data for each row, but NOT the primary key data.

Here is the the requests, and results on the front end. The last one has no ID value - that the problem :)
This is happening in development with no load.

```
req: /order/getallbycreatedasc/
res: {"orders":[{"id":"e6d97e01-8529-435c-ba1e-5c557c02d280","variantid":"example varientid 1","doneis":false,"cancelis":false,"createdat":"2016-01-13T18:02:38.182Z","modifiedat":"0001-01-01T00:00:00Z"}],"total":0}
res code: 200 
req: /order/getallbycreatedasc/
res: {"orders":[{"id":"e6d97e01-8529-435c-ba1e-5c557c02d280","variantid":"example varientid 1","doneis":false,"cancelis":false,"createdat":"2016-01-13T18:02:38.182Z","modifiedat":"0001-01-01T00:00:00Z"}],"total":0}
res code: 200 
req: /order/getallbycreatedasc/
res: {"orders":[{"id":"","variantid":"example varientid 1","doneis":false,"cancelis":false,"createdat":"2016-01-13T18:02:38.182Z","modifiedat":"0001-01-01T00:00:00Z"}],"total":0}
res code: 200 

```

Really cant work this out, and maybe someone else knows.

Thanks in advance ...

**Comment by dancannon** [comment]
Hi, this error often occurs when decoding the results into a struct and the ID fields does not have the `omitempty` tag. This is due to the random ordering of maps in Go.

For example the struct should look like this

``` go
type Order {
    ID string `gorethink:"id,omitempty"`
}
```

Hopefully this should fix your issue, if not let me know.

**Comment by joeblew99** [comment]
Awesome stuff Dan. I will give it a go tomorrow, and come back here and let you know. Thanks again for the support.

**Comment by gedw99** [comment]
Works - Super thanks for help Dan !!!!

**Comment by ghost** [comment]
Cant believe i forgot this.... Its such a weird thing about the map ordering. 
@dancannon thanks for your help.
