### ISSUE TITLE
How to get all based on array string

### ISSUE THREAD

**Issue by vongohren** [rethinkdb/rethinkdb-go#261]
Hi, i want to use this function:

```
func (t Term) GetAll(keys ...interface{}) Term {
```

But what I have is a []string and not sure how to be able to call GetAll("string1","string2", ....).
The length of the slice of strings is very different.

Any suggetions? Im kinda new to go so still learning but not sure how to google my way to this.

**Comment by dancannon** [comment]
I am not sure I fully understand your question and I only have my phone but Go should allow something like this.

``` go
GetAll(slice...)
```

This "converts" a slice to the variation argument form.

**Comment by vongohren** [comment]
I tried the slice... on my []string into the GetAll(list.Items...)
But this returns: cannot pass argument list.Items (variable of type []string) to parameter of type []interface{}

So I have to convert it to a interface array for it to work:

```
  b := make([]interface{}, len(list.Items))
  for i := range list.Items {
      b[i] = list.Items[i]
  }
```

But this is costly when things become big, because it runs in O(n).
Are there any way to make this a bit more efficient or?

**Comment by dancannon** [comment]
Sorry it took me so long to reply, unfortunately I am not sure if there is a good way to solve your problem. The `GetAll` function needs to use `interface{}` as any type can be used as an index. 

I will leave this issue open for a little longer in case somebody else has any ideas for how this can be improved but for now I think creating a new slice is the only way forward,

**Comment by gabeio** [comment]
@dancannon I think it would help to provide an example of the use of the GetAll I actually tried to use it to no avail yet I passed a pointer to a `[]string` of id's and got nothing back...?

What I tried:

``` go
var test []string
test = make([]string, 2)
test[0] = "<id 1>"
test[1] = "<id 2>"
log.Print("test",test)
responses := []user{} // user is the type I build to hold users from the table users
cursor, err := rethink.Table("users").GetAll(test).Run(rethinkSession) // I know rethinkSession is correctly setup as other queries are working properly.
// I also did try passing test as a pointer as &test didn't help :/
log.Print("getAll.error",err)
log.Print("cursor.error",cursor.All(&responses)) // tried cursor.One also didn't work :/
log.Print("responses",responses)
```

and the output was:

```
test[<id 1> <id 2>]
getAll.error<nil> // yeah
cursor.errorThe result does not contain any more rows // this is if I used cursor.One
cursor.error<nil> // this is if I used .All
responses[] // confused
```

yet I run that same query directly in rethink an it worked...

query in rethink:

``` js
r.db("<db>").table("users").getAll("<id 1>","<id 2>")
```

gets me 2 users...

**Comment by dancannon** [comment]
Sure here is an example for how to use `GetAll` with multiple arguments.

``` go
package main

import (
    "fmt"
    "log"

    r "github.com/dancannon/gorethink"
)

func main() {
    session, err := r.Connect(r.ConnectOpts{
        Address: "localhost:28015",
    })
    if err != nil {
        log.Fatalln(err.Error())
    }

    r.DB("test").TableDrop("test").Exec(session)
    r.DB("test").TableCreate("test").Exec(session)
    r.DB("test").Table("test").Insert([]interface{}{
        map[string]interface{}{"id": 1},
        map[string]interface{}{"id": 2},
        map[string]interface{}{"id": 3},
    }).Exec(session)

    v := []interface{}{}

    c, err := r.DB("test").Table("test").GetAll(1, 2).Run(session)
    if err != nil {
        log.Fatalln(err.Error())
    }

    err = c.All(&v)
    if err != nil {
        log.Fatalln(err.Error())
    }

    fmt.Println(v)
    // Output:
    // [map[id:2] map[id:1]]
}
```

I think you can fix your code by "spreading" the arguments for example:

``` go
var test []string
test = make([]string, 2)
test[0] = "<id 1>"
test[1] = "<id 2>"
log.Print("test",test)
responses := []user{} // user is the type I build to hold users from the table users
cursor, err := rethink.Table("users").GetAll(test...).Run(rethinkSession)
```

That being said it is clear this function does not have sufficient documentation so I have created #266 to add some further documentation and examples.

**Comment by gabeio** [comment]
I tried to use `test...` but got the same issue @Snorlock was receiving:
`cannot use test (type []string) as type []interface {} in argument to gorethink.Table("users").GetAll`

---

`cursor, err := rethink.Table("users").GetAll(test[0],test[1]).Run(rethinkSession)` does work though. :confused:

**Comment by dancannon** [comment]
@gabeio You could change the type of `test` to `[]interface{}` but unfortunately as mentioned I can't think of any better API for `GetAll`.

**Comment by gabeio** [comment]
Yeah I looked around for the answer apparently `[]interface{}` does not like any type like `interface{}` does... but you are fine we just need to get used to go :+1:

---

it works now like this:

``` go
var test []interface{}
test = make([]interface{}, 2)
test[0] = "<id 1>"
test[1] = "<id 2>"
log.Print("test",test)
responses := []user{}
cursor, err := rethink.Table("users").GetAll(test...).Run(rethinkSession)
log.Print("getAll.error",err)
log.Print("cursor.error",cursor.All(&responses))
log.Print("responses",responses)
```
