### ISSUE TITLE
Database creation code

### ISSUE THREAD

**Issue by joeblew99** [rethinkdb/rethinkdb-go#262]
I am doing basic migration code. Create dB and tables etc.

I am consistently failing in that the second operation always blows up.
For example the first operation might make the dB, and the 2nd one creates a table.
The table creation operation always blows up with an errir,. I think it's related to the session.

Is there something special I should be doing with the session that is different from normal CRUD operations maybe ?

**Comment by dancannon** [comment]
Its a little difficult to tell what is going on without seeing the code you are running and the error that is being returned. Would it be possible to post them here? Thanks.
