### ISSUE TITLE
Using private struct's fields

### ISSUE THREAD

**Issue by dobegor** [rethinkdb/rethinkdb-go#267]
Is there any way to use private fields in structs to insert/get them as usual?
I. e. :

``` go
type User struct {
    SteamID      string
    ID           string `gorethink:"id,omitempty"`
    money        int    `gorethink:"Money"`
}
```

By inserting this struct to database there is no field "Money".
gorethink uses reflection anyway, so why doesn't it scans private fields, especially when they have gorethink tags?

I need this feature because User object is cached in-memory in my app, but I wanted to get user's balance directly from database, by exposing User.Balance() method, or something like this.

**Comment by dobegor** [comment]
In other words, I would ask: How do I create User object with Money field in database within inserting a struct without such field? 

I don't see a way to do this, except creating some anonymous struct upon inserting, like this:

``` go
r.DB("db").Table("users").Insert(
        struct {
            User
            Money int
        }{
            user,
            0,
        }).RunWrite(DB)
```

**Comment by dancannon** [comment]
Hey @dobegor, Unfortunately I dont think I can support the use of private fields even if it is technically possible. Looking at other similar libraries they all do the same thing.

**Comment by dobegor** [comment]
@dancannon that's ok, but how about some new tag's feature to create fields?
like [this](https://github.com/alexflint/go-restructure) library does with fields named "_" with tags.
something like:

``` go
type User struct {
    SteamID      string
    ID           string `gorethink:"id,omitempty"`
    _          int `gorethink:"Money"`
}
```
