### ISSUE TITLE
slices disappears if when i do a get for missing data

### ISSUE THREAD

**Issue by thinkong** [rethinkdb/rethinkdb-go#268]
so basically i have something like

```
type A struct{
 a []int
 AA []int
}

someA := &A{}
someA.a = make([]int,10)
someA.AA = make([]int, 10) 
cur, _ := r.table('sometable').get(1).run(session)
cur.One(someA)

```

doing this gives the following result

```
len(someA.a) == 0
len(someA.AA) == 10
```

Is this intended? or am i doing something wrong?

**Comment by dancannon** [comment]
GoRethink will zero any fields when decoding the result into a struct. The reason for this is that if you were reusing the same variable for each iteration of `Next` you wouldnt want data from a previous iteration to still be there in future iterations.

**Comment by thinkong** [comment]
OK got it!
