### ISSUE TITLE
error when doing concurrent writes

### ISSUE THREAD

**Issue by Jarema** [rethinkdb/rethinkdb-go#272]
I encountered a problem when doing endless concurrent writes in loop with short pauses between them.

write returns error: 

> dial tcp: lookup localhost: no such host

After some research I found that it's os related problem in net package. (https://github.com/golang/go/issues/3575)

I also run go tests in net package: `go test -v -run=TestLookupIPDeadline -dnsflood`
and it failed.

So, I understand, that it's not related with gorethink package, but the potential problem is: should there be such problem if I set `MaxIdle` and `MaxOpen` around `10`?
**Does it means, that gorethink tries to use more connections then defined in the pool?**

Sample code for writes:

```
func doWrite(s *r.Session) {
    var i uint64
    for  {
        time.Sleep(time.Microsecond * 100)
        go func() {

            atomic.AddUint64(&i, 1)
            nt := Train{Name: fmt.Sprintf("train%v", atomic.LoadUint64(&i))}
            _, err := r.DB("test").Table("trains").Insert(nt).RunWrite(s)

            if err != nil {
                log.Println("error while writing!: ", err)
            }
            log.Println("inserted!")

        }()
    }
}
```

Also, reading when this error occurs is impossible, but it's quite obvious I guess...

**EDIT**: just tested on digitalOcean droplet and after increasing ulimit i got such error:
`dial tcp 127.0.0.1:28015: connect: cannot assign requested address`
which leads there: 
http://stackoverflow.com/questions/19648217/getting-127-0-0-1-cant-assign-requested-address-http-client  
where someone has similar problem when doing lot of http calls.

I'm wondering if there is any problem with closing connections/body of tcp responses. Or maybe session struct is not fully concurrent safe and doesn't protect it's connection pool. I'm just guessing.

**EDIT2**: I'm aware that it's much better to do bulk inserts, but I was testing stability issues only.

Os: OS X 10.11.1
rethinkDB: 2.2.4
gorethink: latest, just pulled

**Comment by dancannon** [comment]
Hi, GoRethink uses the `fatih/pool` package for its connection pool which will open more connections if there are no more connections available in the pool. If you are having this issue it might be worth rate limiting your requests.
