### ISSUE TITLE
Send and receive JSON for querying?

### ISSUE THREAD

**Issue by nkev** [rethinkdb/rethinkdb-go#273]
After working on a query in the RethinkDB web GUI, I end up with a working JavaScript snippet for the result I need. It would be great to just paste this working JavaScript query as a string into my Go code, instead of having to convert it into gorethink syntax. Is this possible?

Similarly, it would be great to receive the raw JSON result from RethinkDB and let me use my own Marshal/Unmarshal functions. 

I wonder how much more performant these 2 features would be than the current way.

**Comment by nkev** [comment]
anyone?

**Comment by dancannon** [comment]
Hi @nkev, sorry for taking a while to reply. I cant see GoRethink ever supporting execution of JavaScript queries, I consider it outside the scope of the project and would likely make the driver significantly more difficult to maintain if added.

Regarding your second suggestion I think it could work but I will need to first look into how the change could be implemented. I will investigate it and reply when I know more.

**Comment by nkev** [comment]
Thanks @dancannon. Doesn't the driver send queries as JSON to RethinkDB? If so, wouldn't it be easy to make that method public?

**Comment by dancannon** [comment]
1.4.0 includes support for both sending and reading raw JSON queries using the `RawQuery` and `NextResponse` functions.

Here is an example https://godoc.org/github.com/dancannon/gorethink#RawQuery

**Comment by nkev** [comment]
Awesome, thank you! I'll do some testing when I get a chance and report back if I find any issues.

**Comment by nkev** [comment]
The example in [RawQuery](https://godoc.org/github.com/dancannon/gorethink#RawQuery) which uses "Hello World" is not very clear. How would you use it in a real-world Javascript raw query, say like this:

``` GO
r.db('mydb').table('users').filter({email: 'you@domain.com'}).update({
  roles: r.row("roles").append('admin')
})
```

Thanks

**Comment by dancannon** [comment]
Well you first need to convert your query to JSON. I got this query by running it in the web admin tool and viewing the request in the chrome developer tools. However the request also includes the query type and options which should be stripped. Here is what the request looks like:

``` json
[1,[53,[[39,[[15,[[14,["mydb"]],"users"]],{"email":"you@domain.com"}]],[69,[[2,[28]],{"roles":[29,[[170,[[13,[]],"roles"]],"admin"]]}]]]],{"binary_format":"raw","time_format":"w","profile":false}]
```

The raw query is the bit after the query type (`[1,`) and before the query options (`,{"binary_format":"raw","time_format":"w","profile":false}]`), for example:

``` json
[53,[[39,[[15,[[14,["mydb"]],"users"]],{"email":"you@domain.com"}]],[69,[[2,[28]],{"roles":[29,[[170,[[13,[]],"roles"]],"admin"]]}]]]]
```

Once I have the query JSON I can pass this to `RawQuery`.

``` go
cur, err := r.RawQuery([]byte(`
    [53,[[39,[[15,[[14,["mydb"]],"users"]],{"email":"you@domain.com"}]],[69,[[2,[28]],{"roles":[29,[[170,[[13,[]],"roles"]],"admin"]]}]]]]
`)).Run(s)
if err != nil {
    log.Fatalln(err)
}

var result interface{}
err = cur.All(&result)
if err != nil {
    log.Fatalln(err)
}

log.Println(result)
```

**Comment by allochi** [comment]
> Similarly, it would be great to receive the raw JSON result from RethinkDB and let me use my own Marshal/Unmarshal functions.

I don't know if this is implemented yet, I would like to receive the raw result as `[]byte` and forward it to the client instead of marshal it again, is this possible?

**Comment by timshannon** [comment]
@allochi that is an intriguing idea, because then you could incorporate something ffjson for performance improvements.

**Comment by allochi** [comment]
@timshannon well, I hope that this can find its way to `gorethink` soon, I hope it's not that much work, something like:

``` go
content, err := q.RunRaw(conn)
```

Which just bypass the `Unmarshal` and pass the response as `[]byte`.

I love `gorethink` and I have been using it in production for several projects, I would like to thank the contributors.

**Comment by dancannon** [comment]
So if I understand you correctly this should already be possible using the `Cursor.NextResponse` function. Please note that this is a low level function that returns the raw response from RethinkDB, as such this may change. Here is an example of how you might us this:

``` go
cur, err := query.Run(session)
if err != nil {
    log.Fatalln(err)
}
defer cur.Close()

for {
    content, more := cur.NextResponse()
    if !more {
        break
    }

    // Use content ([]byte) as required
}

if err := c.Err(); err != nil {
    log.Fatalln(err)
}
```

**Comment by timshannon** [comment]
:+1: That's new to me.  Looks like it'd work great.

**Comment by allochi** [comment]
Hey, this works! 👍 wonderful! I'm so happy! Thanks a lot, you are the best!

Now I can miss use it 😆
