### ISSUE TITLE
connection timeouts (TLS)

### ISSUE THREAD

**Issue by definitelycarter** [rethinkdb/rethinkdb-go#278]
I'm getting intermittent connection timeouts when connecting to a compose rethinkdb instance using TLS.  Restarting my app fixes the issue; however, i'm not sure how to debug these timeouts that are happening.  The app is running in a docker container hosted on a azure vm.

```
api_1 | 2016/03/07 18:43:05 read tcp 172.17.0.8:46752->xx.xx.xx.xx:11329: read: connection timed out 
api_1 | 2016/03/07 18:50:47 dial tcp xx.xx.xx.xx:11329: getsockopt: connection timed out 
api_1 | 2016/03/07 18:57:44 dial tcp xx.xx.xx.xx:11329: getsockopt: connection timed out 
api_1 | 2016/03/07 18:58:44 dial tcp xx.xx.xx.xx:11329: getsockopt: connection timed out 
api_1 | 2016/03/07 18:59:40 dial tcp xx.xx.xx.xx:11329: getsockopt: connection timed out 
api_1 | 2016/03/07 19:00:43 dial tcp xx.xx.xx.xx:11329: getsockopt: connection timed out 
api_1 | 2016/03/07 19:01:37 dial tcp xx.xx.xx.xx:11329: getsockopt: connection timed out 
api_1 | 2016/03/07 19:03:08 read tcp 172.17.0.8:48800->xx.xx.xx.xx:11329: read: connection timed out 
api_1 | 2016/03/07 19:11:19 read tcp 172.17.0.8:49865->xx.xx.xx.xx:11329: read: connection timed out 
api_1 | 2016/03/07 19:25:44 dial tcp xx.xx.xx.xx:11329: getsockopt: connection timed out 
api_1 | 2016/03/07 19:25:51 dial tcp xx.xx.xx.xx:11329: getsockopt: connection timed out 
api_1 | 2016/03/07 19:26:24 dial tcp xx.xx.xx.xx:11329: getsockopt: connection timed out 
api_1 | 2016/03/07 19:27:50 dial tcp xx.xx.xx.xx:11329: getsockopt: connection timed out 
api_1 | 2016/03/07 19:30:40 dial tcp xx.xx.xx.xx:11329: getsockopt: connection timed out
```

**Comment by dancannon** [comment]
Its quite difficult to tell what is going on just from those logs, are you specifying a connection timeout in `Connect()`? Also are the addresses in the logs valid addresses for your RethinkDB cluster?

**Comment by definitelycarter** [comment]
Hey Dan,

I apologize for the late reply.  I was able to track down my issue and I created pull request #279 that fixes my issue.

The bulk of of my issue was that the connections in the pool were dying after a certain period (typically around 5 minutes).  I saw in NewConnection there was `SetKeepAlive` called but `SetKeepAlivePeriod` was not.  I made the keep alive period configurable (in ConnectOpts) and now the connections in the pool are not dying.

**Comment by dancannon** [comment]
Hey thanks for the PR! I had a look over it and it looks great. I hope to merge it some time this weekend

**Comment by dancannon** [comment]
Hey thanks for the PR! I had a look over it and it looks great. I hope to merge it some time this weekend however I have a couple of things that I need to spend some time looking into first.

Regarding the connections not being removed from the pool. That sounds slightly worrying and I will look into that as well.

**Comment by dancannon** [comment]
I think this might fix the issue that prevented the  connection from being removed from the pool https://github.com/dancannon/gorethink/commit/46e8669d3889fe78731c4e8d4d46207c8996f576
