### ISSUE TITLE
Bug in Connection.Query method

### ISSUE THREAD

**Issue by definitelycarter** [rethinkdb/rethinkdb-go#280]
I stumbled across [this code](https://github.com/dancannon/gorethink/blob/master/connection.go#L108-L126) while working on another issue that I wanted to run by you.  On line 108 there is a lock on the Connection's mutex.  The mutex is released on lines 110 and 115 in case of an error; However, on line 126 the method returns out without releasing the mutex.

**Comment by dancannon** [comment]
Good spot! Ill get that fixed in the next release.

**Comment by definitelycarter** [comment]
I'd be more than happy to take a crack at it.  I'll create a PR.

**Comment by definitelycarter** [comment]
I apologize for closing.  Hit the wrong button.

**Comment by definitelycarter** [comment]
I'm not sure what happened but the commit got added to PR #279

https://github.com/dancannon/gorethink/commit/93a6962b68e8fba530c52fdbb2c4ddca9fd11a82
I removed the check to see if c == nil because it appears that code would never git hit since the line above it uses c.mu.
