### ISSUE TITLE
changes feed cluster problem

### ISSUE THREAD

**Issue by deviantmk** [rethinkdb/rethinkdb-go#281]
Hi
Listening for changes on a cluster returns the feed of just one RethinkDB instance.

case.
I have 3 machines running in a cluster with full replication n/n,
writes/sec = 800
changes feed caught = ~250/280

I am not sure whether RethinkDB should report everything on each machine (doesnt sound right) or the driver should take care of this

**Comment by dancannon** [comment]
This is not something I have seen before but I have not spent much time testing changefeeds on a cluster. That being said this sounds like more of an issue with RethinkDB than GoRethink. I will see if I can replicate the issue and report back.

**Comment by deviantmk** [comment]
thanks for taking the time to look into this

**Comment by dancannon** [comment]
I could not replicate this issue. If you run a changefeed query in the RethinkDB web interface do you still get only 1/3 of the results?

**Comment by deviantmk** [comment]
I can not reproduce it again as well, it only happened on 1/3 clusters.
i will try to nail down the cause of this and re-open the issue. It might be a rehinkdb cluster mess up as we were trying to stress test it.
