### ISSUE TITLE
Compound index creation question

### ISSUE THREAD

**Issue by chrisolsen** [rethinkdb/rethinkdb-go#283]
In the `IndexCreate` method [docs](https://github.com/dancannon/gorethink/blob/master/query_table.go#L81) it says that IndexCreate supports compound indexes, but there is no example and I can't figure out how it would be done based on the method argument list.  In some of the [test code](https://github.com/dancannon/gorethink/blob/master/query_select_test.go#L166) I found an example of creating a compound index, but it is using the `IndexCreateFunc` method instead. 

Can compound indexes be created with the `IndexCreate` func or is the later approach the only way?

**Comment by timshannon** [comment]
There's an example in the documentation:

https://godoc.org/github.com/dancannon/gorethink#Term.IndexCreate

**Comment by chrisolsen** [comment]
Thanks :) 
That looks like the same example I found by digging through the test code. I just thought I was missing something since the `IndexCreate` docs says, unless I read it wrong, it can create compound indexes.

**Comment by timshannon** [comment]
Yeah I may be wrong, but the only way I'm aware of is to use IndexCreateFunc for compound indexes.

I don't believe we have an option like the javascript API to specify a name and an object

```
r.table('comments').indexCreate('postAndDate', [r.row("postId"), r.row("date")]).run(conn, callback)
```

@dancannon could probably speak to that.  I doubt there's any real difference between the javascript implementation and the IndexCreateFunc option we have with Go.  I believe rethink will end up creating the same index.  At least that's what I see from the Web interface.

**Comment by dancannon** [comment]
Hey sorry for the delayed reply, as @timshannon mentioned `IndexCreateFunc` is the function that you want to use. The reason for having two separate functions is that Go doesn't allow you to do any function overloading and the RethinkDB api allows you to either pass just a name or both a name and a index function.

I hope this explanation helps, if not let me know.

**Comment by chrisolsen** [comment]
Using the `IndexCreateFunc` is the way I figured it was done, but the [https://github.com/dancannon/gorethink/blob/master/query_table.go#L81](docs) make it sound like the `IndexCreate` is the way to do it, maybe a doc update is required? Thanks for the help :+1:

**Comment by dancannon** [comment]
I have updated the docs in the `develop` branch, I hope to merge to `master` soon.

**Comment by dancannon** [comment]
The fix has been released to master.
