### ISSUE TITLE
TableCreate with compound primary key?

### ISSUE THREAD

**Issue by tve** [rethinkdb/rethinkdb-go#285]
I'm trying to create a table with a compound primary key and I get an error:

```
 26         _, err := r.DB(db.opts.Database).TableCreate("resources", r.TableCreateOpts{
 25                 PrimaryKey: []string{"project_id", "pool_name", "type_name", "name"},
 24         }).RunWrite(db.conn)
```

```
 Database schema has problems: gorethink: Expected type STRING but found ARRAY. in:
r.DB("crs").TableCreate("resources", primary_key=["project_id", "pool_name", "type_name", "name"])
```

The RethinkDB docs state "Using an array as a primary key creates a compound index", so I think I'm trying to do the right thing? What am I doing wrong or is this not supported by gorethink?

**Comment by tve** [comment]
Well, the error comes from rethinkdb, not from the driver. It would be nice if it was clear which errors come from rethinkdb and which come from gorethink. Perhaps the "gorethink:" prefix could be changed to "rethinkdb:" in the former case?
So this doesn't work 'cause https://github.com/rethinkdb/rethinkdb/issues/3875

**Comment by gabeio** [comment]
:+1: that would be really nice! To be able to better distinguish database errors from driver errors... if there are any on purpose driver errors...?

**Comment by dancannon** [comment]
You should be able to check the type of the error, there are some issues with some errors not having the correct types but it should work for most cases.
