### ISSUE TITLE
Concern about time type in gorethink

### ISSUE THREAD

**Issue by nthhtn** [rethinkdb/rethinkdb-go#286]
In brief, I used NodeJS to setup RethinkDB database, and createdAt field has a value of milliseconds since epoch UTC (which can be achieved via Date.now()), I want to store data like this because createdAt will be used as a number for later calculating process after data fetching

Now I buid the same server in Go, I need to seek an equivalent type in this case, which returns a number for me to calculate later process

I read GoDocs for time and found:

func (t Time) Unix() int64

But both int64 and time.Time didn't work out

To be more specific, I posted my question in Stackoverflow: http://stackoverflow.com/questions/36150021/go-get-time-from-rethinkdb

**Comment by gabeio** [comment]
For future reference it's not good practice to ask the same question on multiple websites and link between. That being said.

The first person answered your question but you are just missing that you want to run the function `.Unix()` upon the Field `CreatedAt` in your structure:

``` go
type Quote struct{
    CreatedAt   time.Time  `gorethink:"created_at"`
}
```

if you are working with time stick with `time.Time` as it has a large quantity of functions you may want to use in the future. 

_sidenote:_ that the `func (t Time) Unix() int64` is a function of (`time.Time`) with the name `Unix(no params)` and returns `int64`

**Comment by nthhtn** [comment]
@gabeio If I use time.Time, the fetched data will always be 0001-01-01 00:00:00 +0000 UTC (similarly 0 value if converted to milliseconds). Data in database is a number of milliseconds, and it can't be fetched

**Comment by nthhtn** [comment]
I managed to find the answer myself. True type is used in this condition is float64 so that results fetched match with in database explorer (for example, 1458184908597 milliseconds)
