### ISSUE TITLE
panic when calling Error() on a rqlServerError

### ISSUE THREAD

**Issue by tve** [rethinkdb/rethinkdb-go#288]
I'm getting a server error, but when I call Error() on it to log it I get a panic in gorethink:

```
runtime error: index out of range stack=panic(0xa0fba0, 0xc82000e090)
        /usr/local/go/src/runtime/panic.go:426 +0x4e9
github.com/rightscale/crs/vendor/gopkg.in/dancannon/gorethink%2ev1.Term.String(0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /big/home/src/github.com/rightscale/crs/vendor/gopkg.in/dancannon/gorethink.v1/query.go:159 +0xb2d
github.com/rightscale/crs/vendor/gopkg.in/dancannon/gorethink%2ev1.Term.String(0xad9938, 0x6, 0x3800000000, 0x0, 0x0, 0xc8202ca000, 0x2, 0x2, 0xc8202aa720, 0x0, ...)
        /big/home/src/github.com/rightscale/crs/vendor/gopkg.in/dancannon/gorethink.v1/query.go:159 +0x80d
github.com/rightscale/crs/vendor/gopkg.in/dancannon/gorethink%2ev1.rqlServerError.Error(0xc8201d4070, 0xc8202b42a0, 0x0, 0x0)
        /big/home/src/github.com/rightscale/crs/vendor/gopkg.in/dancannon/gorethink.v1/errors.go:90 +0x25a
github.com/rightscale/crs/vendor/gopkg.in/dancannon/gorethink%2ev1.(*RQLCompileError).Error(0xc820272890, 0x0, 0x0)
        <autogenerated>:167 +0x4f
github.com/rightscale/crs/vendor/github.com/goadesign/goa.NewErrorClass.func1(0xa43460, 0xc820272890, 0x0, 0x0, 0x0, 0xd)
        /big/home/src/github.com/rightscale/crs/vendor/github.com/goadesign/goa/error.go:125 +0x280
...
```

If I %#v print the error before calling Error() I get:

```
err=gorethink.RQLCompileError{rqlServerError:gorethink.rqlServerError{response:(*gorethink.Response)(0xc8201d4070), term:(*gorethink.Term)(0xc8202b42a0)}}
```

**Comment by dancannon** [comment]
Could you please post your query? Thanks

**Comment by tve** [comment]
How do I print the query? The debug output below happens to show it, but in general would be nice to know.

I added some debug. In `func (t Term) String() string` I added the following if clause before the end:

```
if len(t.args) == 0 {
  return fmt.Sprintf("{{len(t.args) == 0}}.%s()", t.name)
}
return fmt.Sprintf("%s.%s(%s)", t.args[0].String(), t.name, strings.Join(allArgsToStringSlice(t.args[1:], t.optArgs), ", "))
```

and I get the following output:

```
gorethink.RQLCompileError{rqlServerError:gorethink.rqlServerError{response:(*gorethink.Response)(0xc82015d6c0), term:(*gorethink.Term)(0xc820294360)}} err=gorethink: Unrecognized TermType: 0. in:
{{len(t.args) == 0}}.().Insert({id="Yh4YzA31xqk0wek13kJ8YQ", project_id=1, name="aws-us-east-1", seq=1, created_at={epoch_time=1.4587555882025526e+09, timezone="-07:00", $reql_type$="TIME"}, updated_at={timezone="-07:00", $reql_type$="TIME", epoch_time=1.4587555882025526e+09}}, return_changes="true")
```

looks to me like term is uninitialized?

**Comment by dancannon** [comment]
I meant the Go code you are using to query the database.

**Comment by tve** [comment]
Well, I most certainly have a bug, but it shouldn't panic. The code is something like this:

```
db.resourcePoolsTable = r.DB(db.opts.Database).Table("resource_pools")
wr, err := db.resourcePoolsTable.Insert(rp, r.InsertOpts{ReturnChanges: "true"}).RunWrite(db.conn)
```

but either `db.opts.Database` in the first statement is empty or `db.resourcePoolsTable` in the second statement is uninitialized (the two statements are not in sequence in the real code). Or is it not possible to reuse `db.resourcePoolsTable` from one query to the next?

**Comment by dancannon** [comment]
Of course I understand that! It's just that having the Go code should help me debug the issue.
Sorry for the short messages I am on my phone.

**Comment by tve** [comment]
Looks like the bug on my end is that I'm starting with un uninitialized term. A `Sprintf("%#v", db.resourcePoolsTable)` yields `gorethink.Term{name:"", rawQuery:false, rootTerm:false, termType:0, data:interface {}(nil), args:[]gorethink.Term(nil), optArgs:map[string]gorethink.Term(nil), lastErr:error(nil)}`. I think this should let you repro the issue.

Thanks for making gorethink available!

**Comment by dancannon** [comment]
I have pushed a change to `develop` which should prevent the `String()` function from panicking, this should be merged to `master` soon.

**Comment by dancannon** [comment]
The fix has been released to master.
