### ISSUE TITLE
incorrect use of gopkg.in

### ISSUE THREAD

**Issue by tve** [rethinkdb/rethinkdb-go#289]
Gorethink advertises using gopkg.in (thank you!) but the usage is incorrect. Specifically, the imports of subpackages reference github.com/dancannon/gorethink. For example (from a quick grep):

```
vendor/gopkg.in/dancannon/gorethink.v1/utils.go:        "github.com/dancannon/gorethink/encoding"
vendor/gopkg.in/dancannon/gorethink.v1/utils.go:        p "github.com/dancannon/gorethink/ql2"
vendor/gopkg.in/dancannon/gorethink.v1/query_geospatial.go:     p "github.com/dancannon/gorethink/ql2"
vendor/gopkg.in/dancannon/gorethink.v1/query_time.go:   p "github.com/dancannon/gorethink/ql2"
vendor/gopkg.in/dancannon/gorethink.v1/query_table.go:  p "github.com/dancannon/gorethink/ql2"
vendor/gopkg.in/dancannon/gorethink.v1/connection_helper.go:    p "github.com/dancannon/gorethink/ql2"
vendor/gopkg.in/dancannon/gorethink.v1/session.go:      p "github.com/dancannon/gorethink/ql2"
vendor/gopkg.in/dancannon/gorethink.v1/query_aggregation.go:    p "github.com/dancannon/gorethink/ql2"
```

Before tagging the gopkg.in version you have to fix up the imports to all reference gopkg.in. The tool we use for that for our repos is github.com/rogpeppe/govers

**Comment by dancannon** [comment]
The fix has been released to master.

**Comment by aeneasr** [comment]
gopkg.in is imho obsolete now that package managers like glide advance. the problem is, that with @tve suggestion to use `gopkg.in/dancannon/gorethink.vX` everywhere (even in master) using this library from github breaks. having to adjust your import paths is, by the way, why i think that gopkg is problematic and shouldn't be the way forward.

my suggestion is to use `import "github.com/dancannon/gorethink"` again in master, keep a `v2` and `v1` branch around to keep gopkg working and release a v3 that goes back to importing from github.com

**Comment by tve** [comment]
Yup.

**Comment by dancannon** [comment]
I wouldn't say that gopkg.in is completely obsolete yet but I agree that using glide would be a good step forward. I think that by migrating from gopkg.in to glide there will be some small impact to users but hopefully we can minimise this using the steps you mention, I have gone ahead and created the `v1` branch and a new issue #357 to keep track of the required changes. I have not created the `v2` branch yet as there will likely be a couple more releases before I start work on `v3` however I expect this to be released within a couple of months.

How does that sound?

**Comment by aeneasr** [comment]
> I wouldn't say that gopkg.in is completely obsolete yet

absolutely not and there are probably quite some people who rely on this still working!

> How does that sound?

sounds good, i'll head over to #357 and check what's going on there now :)
