### ISSUE TITLE
support for dump and restore

### ISSUE THREAD

**Issue by vikstrous** [rethinkdb/rethinkdb-go#299]
Looks like rethinkdb can do backups remotely: http://www.rethinkdb.com/docs/backup/. It would be very useful to be able to use this feature through gorethink.

**Comment by gabeio** [comment]
Please note that even in their documentation they do not support `rethinkdb backup` from their drivers.

**Comment by vikstrous** [comment]
The official cli is actually using their python driver to do dump: https://github.com/rethinkdb/rethinkdb/blob/next/drivers/python/rethinkdb/_dump.py I suspect that it just goes through all the tables and dumps it one by one?

**Comment by dancannon** [comment]
Hi @vikstrous, thanks for the suggestion. Unfortunately I don't see this as something that should be part of the driver however I think it would be a good project to be built using GoRethink. 

If you or anybody else creates such a tool let me know and I will link to it in the readme also if anybody else disagrees with me let me know, until then I will close this issue.
