### ISSUE TITLE
Anonymous embedded struct field inserted/encoded as empty object in DB

### ISSUE THREAD

**Issue by ereyes01** [rethinkdb/rethinkdb-go#301]
I'm hitting an issue where structs with an anonymous time.Time field lose their value when encoded and inserted in the DB. Here is an example illustrating the problem. The code below assumes the following:
- There is a DB called `test`
- The `test` DB has an empty table called `time_test`

``` go
package main

import (
    "log"
    "time"

    r "github.com/dancannon/gorethink"
)

type TimeHolder struct {
    time.Time
}

type Post struct {
    Title string
    When  TimeHolder
}

func main() {
    p := Post{
        Title: "A test",
        When:  TimeHolder{time.Now()},
    }

    log.Printf("%+v\n", p)

    session, err := r.Connect(r.ConnectOpts{
        Address:  "localhost:28015",
        Database: "test",
    })
    if err != nil {
        log.Fatal(err)
    }

    response, err := r.DB("test").Table("time_test").Insert(p).RunWrite(session)
    if err != nil {
        log.Fatal(err)
    }

    log.Printf("%+v\n", response)

    cursor, err := r.DB("test").Table("time_test").Run(session)
    if err != nil {
        log.Fatal(err)
    }

    if err := cursor.One(&p); err != nil {
        log.Fatal(err)
    }

    log.Printf("%+v\n", p)
}
```

The output of this program is:

```
2016/04/11 04:03:11 {Title:A test When:2016-04-11 04:03:11.156167866 -0500 CDT}
2016/04/11 04:03:11 {Errors:0 Inserted:1 Updated:0 Unchanged:0 Replaced:0 Renamed:0 Skipped:0 Deleted:0 Created:0 DBsCreated:0 TablesCreated:0 Dropped:0 DBsDropped:0 TablesDropped:0 GeneratedKeys:[e766b90f-46fc-4f97-9dbf-84c214fddd5e] FirstError: ConfigChanges:[] Changes:[]}
2016/04/11 04:03:11 {Title:A test When:0001-01-01 00:00:00 +0000 UTC}
```

As you can see, `p.Post.When` (a `TimeHolder` type that just holds an anonymous time.Time field) is retrieved with the zero time value despite having been initialized with the current time. In the DB's web UI, or via the Python driver, the `Post.When` field can be seen with an empty object:

```
{
"Title":  "A test" ,
"When": { } ,
"id":  "2e0c7937-db70-40ae-8547-4bd9d5bc6cb5"
}
```

I haven't tested whether anonymous struct fields in general are an issue, or whether the problem is just limited to time.Time values (which I presume may be a bit special). It's getting late (or early) over here :-)  ...maybe I can explore further later.

Let me know if I'm doing something wrong, or if this is a real issue.

Thanks, Eddy

**Comment by ereyes01** [comment]
I also tried just straight up aliasing the time.Time type instead of nesting it as an anonymous struct field. However, the result was similar:

``` go
package main

import (
    "log"
    "time"

    r "github.com/dancannon/gorethink"
)

type TimeHolder time.Time

type Post struct {
    Title string
    When  TimeHolder
}

func main() {
    p := Post{
        Title: "A test",
        When:  TimeHolder(time.Now()),
    }

    log.Printf("%+v\n", p)

    session, err := r.Connect(r.ConnectOpts{
        Address:  "localhost:28015",
        Database: "test",
    })
    if err != nil {
        log.Fatal(err)
    }

    response, err := r.DB("test").Table("time_test").Insert(p).RunWrite(session)
    if err != nil {
        log.Fatal(err)
    }

    log.Printf("%+v\n", response)

    cursor, err := r.DB("test").Table("time_test").Run(session)
    if err != nil {
        log.Fatal(err)
    }

    if err := cursor.One(&p); err != nil {
        log.Fatal(err)
    }

    log.Printf("%+v\n", p)
}
```

Output:

```
2016/04/11 04:07:27 {Title:A test When:{sec:63595962447 nsec:738681696 loc:0x8e6b80}}
2016/04/11 04:07:27 {Errors:0 Inserted:1 Updated:0 Unchanged:0 Replaced:0 Renamed:0 Skipped:0 Deleted:0 Created:0 DBsCreated:0 TablesCreated:0 Dropped:0 DBsDropped:0 TablesDropped:0 GeneratedKeys:[cbc5d603-3a96-47a4-8404-cb67dd47c2f6] FirstError: ConfigChanges:[] Changes:[]}
2016/04/11 04:07:27 {Title:A test When:{sec:0 nsec:0 loc:<nil>}}
```

Object in the RethinkDB web UI:

```
{
"Title":  "A test" ,
"When": { } ,
"id":  "82f22868-5472-4f00-9ce6-5e1ff70be2c3"
}
```

Thanks again, Eddy

**Comment by dancannon** [comment]
Hey, thanks for the bug report. I had a quick look at the issue and was able to replicate it myself. However I am not sure if this will be easy to fix without causing performance issues. 

In a related note I tried encoding the same struct with `encoding/json` and got the same result which makes me think that if the stdlib doesnt support this structure maybe GoRethink shouldnt either. What do you think? I will have a more indepth look into this issue later today.

Here is the code I ran:

``` go
package main

import (
    "log"
    "time"
    "encoding/json"
)

type TimeHolder time.Time

type Post struct {
    Title string
    When  TimeHolder
}

func main() {
    p := Post{
        Title: "A test",
        When:  TimeHolder(time.Now()),
    }

    log.Printf("%+v\n", p)

    b, err := json.Marshal(p)
    if err != nil {
        log.Fatalln(err)
    }

    log.Printf("%+v\n", string(b))
}
```

**Comment by ereyes01** [comment]
Thanks for the quick reply!

You are correct that when time.Time is aliased as another type, it JSON Marshals to the zero value due to this new type not implementing the json.Marshaler interface.

However, when it is an anonymous struct field, it does get JSON-Marshalled as its original value.

``` go
package main

import (
    "encoding/json"
    "log"
    "time"
)

type TimeHolder struct {
    time.Time
}

type Post struct {
    Title string
    When  TimeHolder
}

func main() {
    p := Post{
        Title: "A test",
        When:  TimeHolder{time.Now()},
    }

    log.Printf("%+v\n", p)

    b, err := json.Marshal(p)
    if err != nil {
        log.Fatalln(err)
    }

    log.Printf("%+v\n", string(b))
}
```

Output:

```
2016/04/11 04:33:32 {Title:A test When:2016-04-11 04:33:32.088240358 -0500 CDT}
2016/04/11 04:33:32 {"Title":"A test","When":"2016-04-11T04:33:32.088240358-05:00"}
```

So maybe my case where TimeHolder is defined as `type TimeHolder timeTime` is not really a problem. The behavior as an anonymous struct field, however, doesn't line up with Go's JSON encoding.

Thanks, Eddy

**Comment by ereyes01** [comment]
You may wonder why I'm playing with such strange corner cases :-)  I was trying to get this to work with gorethink: https://github.com/ereyes01/servertime

I may rethink my approach to this if the fix isn't easy (no pun intended).

Thanks, Eddy

**Comment by dancannon** [comment]
Before you start rethinking everything (pun intended :D) let me have a look at the code this evening to see if I can figure out solution.

**Comment by ereyes01** [comment]
I think this problem applies more generally to all embedded anonymous struct fields, not just those of type `time.Time`. Observe the following extended example:

``` go
package main

import (
    "log"
    "time"

    r "github.com/dancannon/gorethink"
)

type TimeHolder struct {
    time.Time
}

type ANumber struct {
    int
}

type Post struct {
    Title string
    When  TimeHolder
    Value ANumber
}

func main() {
    p := Post{
        Title: "A test",
        When:  TimeHolder{time.Now()},
        Value: ANumber{100},
    }

    log.Printf("%+v\n", p)

    session, err := r.Connect(r.ConnectOpts{
        Address:  "localhost:28015",
        Database: "test",
    })
    if err != nil {
        log.Fatal(err)
    }

    if _, err := r.DB("test").Table("time_test").Delete().RunWrite(session); err != nil {
        log.Fatal(err)
    }

    response, err := r.DB("test").Table("time_test").Insert(p).RunWrite(session)
    if err != nil {
        log.Fatal(err)
    }

    log.Printf("%+v\n", response)

    cursor, err := r.DB("test").Table("time_test").Run(session)
    if err != nil {
        log.Fatal(err)
    }

    if err := cursor.One(&p); err != nil {
        log.Fatal(err)
    }

    log.Printf("%+v\n", p)
}
```

Output:

```
2016/04/11 14:15:47 {Title:A test When:2016-04-11 14:15:47.178705733 -0500 CDT Value:{int:100}}
2016/04/11 14:15:47 {Errors:0 Inserted:1 Updated:0 Unchanged:0 Replaced:0 Renamed:0 Skipped:0 Deleted:0 Created:0 DBsCreated:0 TablesCreated:0 Dropped:0 DBsDropped:0 TablesDropped:0 GeneratedKeys:[67afca66-f146-4f44-bca2-ef4011965676] FirstError: ConfigChanges:[] Changes:[]}
2016/04/11 14:15:47 {Title:A test When:0001-01-01 00:00:00 +0000 UTC Value:{int:0}}
```

In this case, Post.Value was initialized to `ANumber{100}` but was inserted into the DB as a zero value. I tried adding other named fields to the `ANumber` struct, and the named fields get written into the DB correctly. However, the anonymous embedded struct field is always zeroed out.

thanks, Eddy

**Comment by dancannon** [comment]
Unfortunately I dont have the time to look at this issue right now (sorry!) Would it be possible if you could investigate the issue?

**Comment by ereyes01** [comment]
So I did investigate and I think there's two separate issues. First, let's deal with the `time.Time` issue.

Suppose we have the following:

``` go
type TimeHolder struct {
    time.Time
}

type Foo struct {
    When TimeHolder
}

...
f := Foo{time.Now()}
```

Now suppose we want to encode `f`.

The code will eventually call down into `gorethink/encoding.typeFields()` in encoding/cache.go.

This function primarily is concerned with mapping the given type to its `gorethink` tag name, or deriving a key name from the field variable name. However, this function also contains special handling for anonymous structs- it tries to inline the processing of the anonymous struct's fields so that its fields are handled alongside the parent struct's. which is what eventually gets us into trouble with our anonymous `time.Time` value.

So the encoder will:
- Encounter the `When` field of `f`
  - `newStructEncoder()`->`cachedTypeFields()`->`typeFields()`
  - type of `When` is `TimeHolder` another struct
- `TimeHolder` gets its turn through `newStructEncoder()`
  - The only field of `TimeHolder` is the anonymous `time.Time` struct
  - `typeFields()` falls through into the anonymous struct special case code
  - All the fields inside the `time.Time` are unexported, and the field is effectively skipped.

This is the check that fails and leads to the fallthrough into the anonymous struct code:

``` go
// Record found field and index sequence.
if name != "" || !sf.Anonymous || ft.Kind() != reflect.Struct {
```

Elsewhere in the code, `time.Time` is a "special" type, and gets preferential treatment, since times are a pseudotype in RethinkDB. In `newTypeEncoder()`, this here short-circuits its processing before it can get the struct treatment:

``` go
    // Check for psuedo-types first
    switch t {
    case timeType:
        return timePseudoTypeEncoder
    }
```

So perhaps `time.Time` also needs preferential treatment in the `typeFields()` function. Something along the lines of:

`if name != "" || !sf.Anonymous || ft.Kind() != reflect.Struct || isPseudoType(ft) {`

...

``` go
func isPseudoType(t reflect.Type) bool {
    return t == reflect.TypeOf(time.Time{})
}
```

**Comment by ereyes01** [comment]
As for the anonymous `int` field... that issue is totally different from the `time.Time` issue I described above.

It turns out that, in the code sample I gave above. it does get written into the database and looks like:

```
{
"Title":  "A test" ,
"Value": {
"int": 100
} ,
"When": { } ,
"id":  "ed2563b1-218f-4063-9244-6b9ccffca1c1"
}
```

Notice that the anonymous `int` field is inserted into the db as:

`"int": 100`

That's not quite anonymous, now is it? Of course, in JSON, you can't have anonymous values like in Go structs. Maybe an approximation of that would be `{"": 100}` or something...

Where did the "int" keyname come from?

``` go
                // Record found field and index sequence.
                if name != "" || !sf.Anonymous || ft.Kind() != reflect.Struct {
                    tagged := name != ""
                    if name == "" {
                        name = sf.Name
                    }
```

And anonymous struct fields have their name set to their type's name (in this case "int").

I didn't go dive through all the decoding code, but it's not hard to guess what might be happening that leads to the anonymous int field getting decoded as 0:
- We encounter `{"int": 100}`
- No `gorethink:"int"` tag found
- No struct field called "int"
- Ignore this value
- Anonymous int field remains uninitialized

**Comment by ereyes01** [comment]
The change in the PR seems to fix the saving/retrieving of the anonymous time.Time in my original test code above. However, since this works, it calls into question my (admittedly half-baked) explanation of why the anonymous int is not decoded properly. Especially since this is how the anonymous time value looks in the database:

```
{
"Title":  "A test" ,
"Value": {
"int": 100
} ,
"When": {
"Time": Wed Apr 13 2016 02:18:34 GMT-05:00
} ,
"id":  "37521b55-f2e6-4432-8451-72d949287cac"
}
```

When I next have some free time, maybe I should dive into the decoder code to see what's happening...

**Comment by dancannon** [comment]
I had a look at the decoder however the reason it is failing is it is trying to assign the response to unaddressable location. 

Honestly I think that unless we can figure out a proper solution this is just too much of an edge case to support.

**Comment by ereyes01** [comment]
Yeah, the anonymous embedded int struct isn't important to me. The embedded time type addressed in the PR would be helpful though :-)

Thanks

**Comment by dancannon** [comment]
I merged your PR, thanks for the help!

**Comment by ereyes01** [comment]
Awesome thanks for your help too!
