### ISSUE TITLE
integer unmarshal bug

### ISSUE THREAD

**Issue by ghost** [rethinkdb/rethinkdb-go#303]
Simply unmarshaling a big int64 field will produce different value (overflow). For testcase, see [previous issue](https://github.com/dancannon/gorethink/issues/250), simply changing the value 9000000000000000 into 1<<54-1 will make it fail. I also tried UseNumber: true, and still fail. 

I suspect this is due to [numeric types conversion](https://golang.org/ref/spec#Conversions) during unmarshal

Go 1.6 64-bit

**Comment by dancannon** [comment]
I couldnt seem to replicate this using Go 1.6, RethinkDB 2.3 on a 64-bit PC. Here is the code I was using:

``` go
package main

import (
    "log"

    "github.com/davecgh/go-spew/spew"
    r "gopkg.in/dancannon/gorethink.v1"
)

type A struct {
    ID int64 `gorethink:"id"`
    I  int64
}

func main() {
    session, err := r.Connect(r.ConnectOpts{
        Address: "localhost:28015",
        MaxIdle: 30,
        MaxOpen: 50,
    })
    if err != nil {
        log.Fatalln(err.Error())
    }

    r.DB("test").TableDrop("test250").Exec(session)
    r.DB("test").TableCreate("test250").Exec(session)

    v1 := A{
        ID: 1,
        I:  1<<54 - 1,
    }
    var v2 A

    err = r.DB("test").Table("test250").Insert(A{
        ID: 1,
        I:  1<<54 - 1,
    }, r.InsertOpts{
        Conflict: "replace",
    }).Exec(session)
    if err != nil {
        log.Fatalln(err.Error())
    }

    c, err := r.DB("test").Table("test250").Get(1).Run(session)
    if err != nil {
        log.Fatalln(err.Error())
    }

    err = c.One(&v2)
    if err != nil {
        log.Fatalln(err.Error())
    }

    spew.Dump(v1, v2)
}
```

```
(main.A) {
 ID: (int64) 1,
 I: (int64) 18014398509481983
}
(main.A) {
 ID: (int64) 1,
 I: (int64) 18014398509481984
}
```

**Comment by ghost** [comment]
What do you mean ? It's clearly different output:
`v1.I = 18014398509481983`
`v2.I = v1.I + 1`

**Comment by ghost** [comment]
So, further research pointed me to [previous issue](https://github.com/dancannon/gorethink/issues/156).
The crux of the problem is because rethinkDB, not golang driver, [save number as float64](https://github.com/rethinkdb/rethinkdb/issues/3834).

This is a very surprising behavior for someone new to the database. Perhaps the driver can simply err on large int64/uint64 values for now.

**Comment by dancannon** [comment]
Sorry I was looking for an overflow and didnt look too closely at the values! As you mention it looks like a rounding error due to RethinkDB storing the number as a float.

Unfortunately while I agree this behaviour is rather confusing I dont think the driver should return an error when encoding large ints.
