### ISSUE TITLE
could not decode type string into Go value of type time.Time

### ISSUE THREAD

**Issue by thomasmodeneis** [rethinkdb/rethinkdb-go#307]
Hi,

I'm having this error with my queries, I know the problem is because RethinkDB is a JSON storage it accepts anything, but Go is a tiped lang and need to be precise set. This caused this error to happen.

Same field having two types string and date and gorethink is confused causing this error on my logs:
`gorethink: could not decode type string into Go value of type time.Time`

Is there a way to be including the field name where this decode failed on this error message ?

As well it will be good to know if there is a way to ignore this failures on specific fields by ignoring them.

Thanks.

**Comment by dancannon** [comment]
Hi, although I understand this would be a useful feature it would unfortunately require some pretty big changes to the way the decoder works so I will probably not be working on this at the moment.

**Comment by thomasmodeneis** [comment]
Hi,

I'm running into this problem again...

`gorethink: could not decode type string into Go value of type time.Time` 
This is not the first time I've raised this issue. It happened with other types as well.

RethinkDB is a JSON database & Golang is a typed lang, I can see why the error happens.

The main problem for me is that when it happens the complete marshall fails, the customer is returned with no data and the logs are really not giving me clues; from the customer perspective this system is broken and I have no say on that.

If I can't fix this I will be forced to migrate to Nodejs driver and that will be really a shame, given all the time and effort I've put into making it work with gorethink.

```
gorethink: could not decode type string into Go value of type time.Time &{0x199dc0 <nil> 0xc4201c22a0 1 Cursor 0xc4204579e0 map[db:[14 [test]]] {{0 0} 0 0 0 0} 0xc4202b9d70 false true true true false 0 [] [] <nil>}
```

Suggestions:
1) Find a way to work around the issue by displaying better logging, retry marshal against generic interface and print full struct on the log including ID.
2) Must ignore the row with problem and continue marshalling all the others, printing a silent warn of the problem.

I'm aware you are not willing to fix the bug, but with your support telling me where to look for and how to test it, I can have a look and maybe find a better work around the problem ?

Cheers.
