### ISSUE TITLE
gopkg.in/dancannon/gorethink.v1 tag not working correctly

### ISSUE THREAD

**Issue by definitelycarter** [rethinkdb/rethinkdb-go#308]
When I `go get -u gopkg.in/dancannon/gorethink.v1` there are three files that point to `github.com/dancannon/gorethink`.

![screen shot 2016-04-15 at 4 59 05 pm](https://cloud.githubusercontent.com/assets/6287039/14574913/4fd4480e-032c-11e6-83cd-88cf79092147.png)

![screen shot 2016-04-15 at 4 45 09 pm](https://cloud.githubusercontent.com/assets/6287039/14574907/49a2af20-032c-11e6-8094-bcfb3fc89a95.png)

When i download 1.4.1 from the release page the files are pointing correctly to `gopkg.in/dancannon/gorethink.v1`

**Comment by dancannon** [comment]
Fixed by correcting the v1.4.1 tag.
