### ISSUE TITLE
When using latest version of your driver and databases < 2.3 driver is not working

### ISSUE THREAD

**Issue by goors** [rethinkdb/rethinkdb-go#310]
Here is error:

<pre>
WARN[0000] Error creating connection: gorethink: Received an unsupported protocol version. 
This port is for RethinkDB queries. Does your client driver version not match the server?

no connections were made when creating the session
</pre>

**Comment by dancannon** [comment]
As noted in the changelog v2.0.0 will not work by default with < RethinkDB 2.3, if you want to use the latest version I suggest you read the fix in the changelog https://github.com/dancannon/gorethink/blob/master/CHANGELOG.md#v200---2016-04-13.

Alternatively change your import to use `gopkg.in/dancannon/gorethink.v1` to ensure that you continue to use v1 of the driver.

**Comment by goors** [comment]
thank you. closing.
