### ISSUE TITLE
Using the driver in production

### ISSUE THREAD

**Issue by gngeorgiev** [rethinkdb/rethinkdb-go#313]
I am using the driver in a semi-production environment with only one master node, but I am not quite sure that I am using it correctly. After every X requests my services begin to receive the following error:

```
ErrNoConnectionsStarted = errors.New("no connections were made when creating the session")
```

It seems that the connection to rethinkdb is closed and cannot be reopened.
I am not sure whether this is a problem with the driver, the way I am using it or the database.

The way I am using it is the following:
On every request to the DB I invoke the `Connect` method which returns a session. Regardless of whether I close or do not close the session after using it, the problem persists. I also tried using the pooled approach but that did not work as well.

Thanks

**Comment by dancannon** [comment]
Hi @gngeorgiev, could you post the code you are using to create your session and if possible an example of one of your queries? 

Also if you call `r.SetVerbose(true)` and see if there are any errors being logged?

**Comment by gngeorgiev** [comment]
Hey @dancannon, you can see the relevant code here: [DbService](https://github.com/neutrinoapp/neutrino/blob/master/src/common/db/dbService.go). Take a look at the `Run` and `Exec` methods.

However, I am not observing this behavior after updating to the latest version. Before that I was with the previous version, I did not see something major that would fix this. If I spot it will let you know.

**Comment by dancannon** [comment]
I had a quick look at your code and I would recommend reusing the session to take advantage of the built-in connection pool. It's unlikely that doing this would fix your issue but it might help.

Is it possible that there were network issues that prevented your application from contacting your database?

**Comment by gngeorgiev** [comment]
@dancannon I was reusing the session initially, I added the `Close` call afterwards hoping it would help. Guess I will revert it.

It is unlikely that there were networking issues since the setup has not changed since. Also, there was a single instance of RethinkDB and some of the services were losing the connection sporadically, while they run on the same machine, simply in different containers. I really think that the problem was in the driver version. The services are now running for 16h straight with no problems.

**Comment by timshannon** [comment]
Just thought I'd add my personal experience with this.  We recently had a hardware failure on the one of our VPS hosts that was running RethinkDB.  The VPS running the webserver was still up, and as soon as the RethinkDB backend was migrated to a new host and restarted, the webserver picked up the connection beautifully without having to restart or reset anything.

In my code we're using one session object as @dancannon has recommended.
