### ISSUE TITLE
Struct tags ignored when using other tags

### ISSUE THREAD

**Issue by frankdugan3** [rethinkdb/rethinkdb-go#314]
When using gorethink struct tags in conjunction with other tags (such as json), gorethink ignores the tags unless the gorethink tags are the first tags listed.

**Comment by dancannon** [comment]
Turns out we both misunderstood how to use multiple tags, there should not be a comma between the tags.

``` go
Field string `a:"123" b:"321”`
// not
Field string `a:”123", b:"321”`
```

**Comment by frankdugan3** [comment]
Hmm, not sure where I got the idea for the comma. Sorry for troubling you over nothing.

**Comment by dancannon** [comment]
haha well I had the exact same idea, I was writing tests and couldn't figure out why they were failing :)
