### ISSUE TITLE
Q: request retries, status & plans?

### ISSUE THREAD

**Issue by tve** [rethinkdb/rethinkdb-go#315]
I'm trying to figure out what I have to do in my app to deal with communication failures and rethinkdb node failures. Does the driver perform any retries? If not, is this something it should do?
If the driver doesn't perform any retries, is there a simple way to identify retryable requests from the error returned (either idempotent requests or that have not reached a stage where anything has been performed)?

**Comment by dancannon** [comment]
Hi, the driver does not currently do any retries and I consider this to be something that the application should handle.

Regarding the detection of retryable requests this is slightly more difficult to solve however I would suggest checking the type of the error returned. For example a `RQLConnectionError` could probably be retried but a `RQLRuntimeError` probably shouldnt be retried. That being said I am not sure how reliable these error codes are as I have not used them personally.

**Comment by timshannon** [comment]
Personally I'd say that absolutely need to be handled at the application layer, as there is no transactional integrity outside of a single document.  The driver can't make any assumptions about how an application is updating data if there is no concept of a transaction in the driver, which isn't currently possible with rethinkdb.

**Comment by tve** [comment]
I understand that the driver can't do retries in general, but there are certain conditions where the driver has much better info than the app and can be much more effective at retrying immediately.

For example, an error happening in NewConnection https://github.com/dancannon/gorethink/blob/38f30caccd076880e50db322c1c7a4d85980b8b0/connection.go#L48 is easily retryable. Even looking at the code, it's non-trivial for me as a user to sort out how to recognize such errors and retry them at a low level. Similarly, pretty much any error in writeQuery https://github.com/dancannon/gorethink/blob/master/connection_helper.go#L30 is retryable I would assume, 'cause the query wouldn't have been completed.

Handling some of those errors at a low level doesn't relieve the app from handling errors, but it can make the difference where a rethinkdb node failure or replacement can be masked from the app vs. where the app ends up returning errors to the user because it can't tell anymore whether it's safe to retry or not.

**Comment by dancannon** [comment]
The driver does actually do some basic retries if a bad connection was detected however this will use the same host as before so if a host fails then a query will not be retried on another host. This is not ideal however will require some refactoring to support this use case.

For now I would suggest moving the retry logic to your application especially if it is important that a query is successful. I will leave this issue open until I have time to revisit this.

**Comment by thomasmodeneis** [comment]
Hi,

I'm actually facing some of this failures and I would like to ask you guys for some connection retry strategy best practices. 

This is the basic query:

```
res, err := r.Table(table).GetAllByIndex(key, value).Count().Run(Session)
if err != nil {
        log.Println("404 not found ",err)
        valid = errors.New("404 not found")
    }
```

prints:
`2016/05/04 09:48:35 404 not found  read tcp 10.0.1.3:53908->10.0.1.125:28015: read: connection reset by peer`

Is correct to assume that if err contains `connection reset by peer` I should handle a retry at the application layer ? Do you have any other strategies in order to handle this issues ?

Thanks.

**Comment by dancannon** [comment]
I have recently updated the driver to retry with different hosts in the event of a connection failure, this is an improvement on the previous implementation as it means that if a single node in a cluster is failing then the query should be retried on a different node. There was also another issue where in certain situations the query would not be retried which should now be fixed.

**Comment by thomasmodeneis** [comment]
hi @dancannon 
Great news, however this won't fix what have been reported in this ticket is refering to retry to the same node, will your fix retry even in case of a temporarily downtime ?

I have issues for example when I'm updating rethinkdb that the node need to be down for some time and when the db is back up, the app can't recover and all queries are failing, will this be a fix for this scenario as well ?

thanks

**Comment by dancannon** [comment]
Hi @thomasmodeneis, this fix will only retry the query up to three times, currently there is no delay between each attempt. If your server becomes unavailable for a significant amount of time the driver will not continuously retry until it comes back and honestly I don't believe this is something the driver should handle. That being said if this behaviour is required then your application code could check if the returned error is of type `RQLConnectionError` and then retry until successful.

Regarding your application not recovering are you saying that all queries would fail after restarting your RethinkDB instance? If this is the case then there is a more serious issue that needs to be looked into however I have not seen this happen before.
