### ISSUE TITLE
Error decoding GEOMETRY to Point on struct

### ISSUE THREAD

**Issue by dguenther** [rethinkdb/rethinkdb-go#316]
It's very possible I'm doing this the wrong way, but I'm encountering an error when trying to retrieve a struct that contains a `types.Point`. Here's the error:

`gorethink: could not decode type interface {} into Go value of type *types.Point: pseudo-type GEOMETRY object is not valid`

and here's a sample case:

```
package main

import (
    "fmt"

    r "github.com/dancannon/gorethink"
    "github.com/dancannon/gorethink/types"
)

type T struct {
    ID       string      `gorethink:"id,omitempty"`
    Location types.Point `gorethink:"location"`
}

func main() {
    session, err := r.Connect(r.ConnectOpts{
        Address:  "<rethink_address>",
        Database: "testdb",
    })

    r.DBCreate("testdb").Run(session)
    r.TableCreate("testtable").Run(session)
    r.Table("testtable").Insert(T{
        Location: types.Point{
            Lat: 20,
            Lon: 10,
        },
    }).RunWrite(session)

    var result T
    c, _ := r.Table("testtable").Run(session)
    err = c.One(&result)
    fmt.Println(err) // error happens here
    fmt.Println(result)
}
```

Would someone be able to set me straight on what I'm doing wrong? Thanks!

**Comment by dancannon** [comment]
Unfortunately this issue seems to be due the recent switch to using the `gopkg.in` import path internally which means a type comparison is no longer working if you import the project directly. Changing your imports to the following should fix your issue, sorry the trouble this has caused you:

``` go
import (
    "fmt"

    r "gopkg.in/dancannon/gorethink.v2"
    "gopkg.in/dancannon/gorethink.v2/types"
)
```

**Comment by dguenther** [comment]
Oh awesome, thanks for the help! I'm still new to Go, so that's definitely on me.
