### ISSUE TITLE
Changefeeds block forever when connection is not used for long time

### ISSUE THREAD

**Issue by blackss2** [rethinkdb/rethinkdb-go#317]
I made some updating list code by changefeeds.
When I doesn't use connection for long time(about 1~2 hours), stream is not working.
Any other functionality like insert, update, delete is working fine. but only_ Changes() that was created before long time doesn't get feed any more.
It is blocked at Next() function forever._
Please let me know to how I make it can work.

``` go

type Project struct {
    Id      string   `json:"id,omitempty" gorethink:"id,omitempty"`
    Name    string   `json:"name" gorethink:"name"`
    Creator string   `json:"creator" gorethink:"creator"`
    TCreate NullTime `json:"t_create" gorethink:"t_create"`
}

type ProjectFeed struct {
    NewVal *Project `json:"new_val" gorethink:"new_val"`
    OldVal *Project `json:"old_val" gorethink:"old_val"`
}

type ProjectTable struct {
    DBTable
    dataList []*Project
    query    gorethink.Term
}

func NewProjectTable(session *gorethink.Session, db gorethink.Term) *ProjectTable {
    st := &ProjectTable{
        DBTable: DBTable{
            session: session,
            db:      db,
        },
        dataList: make([]*Project, 0),
    }
    st.Init("project", "t_create")
    st.query = st.table.OrderBy(gorethink.OrderByOpts{Index: "t_create"})
    return st
}

func (st *ProjectTable) Reload() {
    log.Println("ProjectTable Reload")

    list := make([]*Project, 0)

    res, err := st.query.Run(st.session)
    if err != nil {
        log.Fatalln(err.Error())
    }
    defer res.Close()

    res.All(&list)

    st.dataList = list
}

func (st *ProjectTable) Start() {
    go func() {
        for {
            st.Reload()

            log.Println("ProjectTable Start")

            stream, err := st.query.Changes().Run(st.session)
            if err != nil {
                log.Fatalln(err.Error())
            }
            defer stream.Close()

            hash := make(map[string]interface{})
            for stream.Next(&hash) {
                data, err := json.Marshal(hash)
                if err != nil {
                    panic(err)
                }
                var feed ProjectFeed
                err = json.Unmarshal(data, &feed)
                if err != nil {
                    log.Println("project stream error", err)
                    st.Reload()
                    continue
                }

                if feed.OldVal == nil {
                    if feed.NewVal != nil {
                        log.Println("inserted", feed.NewVal)
                        st.dataList = append(st.dataList, feed.NewVal)
                    } else {
                        panic("cannot reach")
                    }
                } else {
                    if feed.NewVal != nil {
                        log.Println("updated", feed.OldVal, feed.NewVal)
                        for i, v := range st.dataList {
                            if v.Id == feed.OldVal.Id {
                                st.dataList[i] = feed.NewVal
                                break
                            }
                        }
                    } else {
                        log.Println("deleted", feed.OldVal)
                        idx := -1
                        for i, v := range st.dataList {
                            if v.Id == feed.OldVal.Id {
                                idx = i
                                break
                            }
                        }
                        if idx >= 0 {
                            st.dataList = append(st.dataList[:idx], st.dataList[idx+1:]...)
                        }
                    }
                }
            }

            log.Println("ProjectStream End")
        }
    }()
}
```

Thanks for reading.

**Comment by dancannon** [comment]
Hi, sorry for taking so long to reply I have attempted to look into this a couple of times but couldn't figure anything out. I have a couple of questions which might help figure out what is going on:
- Has this only started happening recently?
- Which version of RethinkDB and GoRethink are you using?
- What does your `Connect` look like?

**Comment by blackss2** [comment]
- Has this only started happening recently?
  => No. About 4 month ago, i experienced same issue, but i ignore that because of that is not production project. Both are running on windows 7.
- Which version of RethinkDB and GoRethink are you using?
  => Always recent version I use.
- What does your Connect look like?
  => This issue only occured when I sit off long time(minimum 1~2 hours). So I think connection is restart, or feed from rethinkdb is not maintained, but I do not have check method anyway. Other stuff like CRUD is work fine, but only created feed by Changes() cannot get event from rethinkdb.

**Comment by dancannon** [comment]
I asked about this issue on the #driver-dev channel on the RethinkDB slack and somebody suggested that I look into the drivers KeepAlive settings. After checking the code I think I can see a possible problem, I will try to look into it tomorrow and get back to you.

**Comment by dancannon** [comment]
I reverted a change to develop to re-enable KeepAlive by default (this was disabled by a release in March so it doesnt look like it will completely fix your issue). I will try to find some more time this week to do a more in-depth investigation.

I apologize for taking so long to look into this but issues like this always take a long time to even figure out what is going on and I have been unusually busy lately with personal stuff.

**Comment by blackss2** [comment]
You're welcome.
Thank you for your efforts to solving this issue.
I will reply after some testing after affecting this way.

**Comment by blackss2** [comment]
In similar condition, problems are solved.
Thank you for your help.
I will write another comment if I got same error.

**Comment by dancannon** [comment]
This has now been merged to master.
