### ISSUE TITLE
Add constant / var for special "rethinkdb" database

### ISSUE THREAD

**Issue by timshannon** [rethinkdb/rethinkdb-go#321]
I'm building unit tests and my app runs across multiple databases.  So for the teardown of the tests I'm dropping all the database on the server by getting DBList() and ranging a DBDrop call on them.

This fails on the _rethinkdb_ database because its special.  Since it's special, can we get a constant declared that we can reference the name?   I can hard code it just as easy, but having a const defined that is inline with the product and version would be helpful.

**Comment by dancannon** [comment]
Sure I can't see any reason why not, what do you think about the following?

``` go
const (
    SystemDatabase = "rethinkdb"
)
```

**Comment by timshannon** [comment]
Yep, works for me.

**Comment by dancannon** [comment]
I pushed this change to `develop` 67377840449bf21585272b9a21ce867e86c77e67.

**Comment by dancannon** [comment]
This has now been merged to master.
