### ISSUE TITLE
Error connecting to node: invalid capacity settings

### ISSUE THREAD

**Issue by rawfish-dev** [rethinkdb/rethinkdb-go#322]
I'm trying to create a testhelper to prepare the DB tables etc before running some tests. The DB seems to be up and running fine when I visit localhost:8080. However when running the following code:

```
    dbSession, err := rtdb.Connect(rtdb.ConnectOpts{
        Address:         "localhost:28015",
        Database:        "rethinkdb_test",
        MaxIdle:         20,
        MaxOpen:         10,
        KeepAlivePeriod: time.Duration(60) * time.Second,
    })
    if err != nil {
        panic(fmt.Sprintf("testhelper - unable to setup test DB due to %v", err.Error()))
    }
```

The setup panics when the `err != nil` with the message:

```
Test Panicked
      testhelper - unable to setup test DB due to no connections were made when creating the session
      /usr/local/Cellar/go/1.5.1/libexec/src/runtime/panic.go:423
```

I also see an odd message in the logs before the problem:

```
Error connecting to node: invalid capacity settings"
```

Is this related to the library or the DB setup? I am using `rethinkdb 2.3.1 (CLANG 7.0.2 (clang-700.1.81))` and `gopkg.in/dancannon/gorethink.v2`.

**Comment by dancannon** [comment]
Hi, this issue is because you are asking the connection pool to have a maximum of 10 connections open but allow 20 idle connections. If you swap these two round you should now longer have any issues.

**Comment by rawfish-dev** [comment]
Works great now, I should have tried with the default values before asking. Thanks for the prompt help!
