### ISSUE TITLE
Getting wrong password with the new release

### ISSUE THREAD

**Issue by agaurav** [rethinkdb/rethinkdb-go#323]
Unable to connect with a password protected user (while being successful with the python driver using same parameters). 

```
Error Message : Error creating connection: gorethink: Wrong password
gorethink version : v2.0.2
RethinkDB version : 2.3.1
go version : 1.6.2
OS : debian-jessie 3.16.0-4-amd64
```

**Comment by dancannon** [comment]
Hi, Could you please post the code you are using to create your session? Thanks

**Comment by agaurav** [comment]
My bad, I was using the deprecated `AuthKey` field instead of the new `Password` one in `ConnectOpts`. Realized it while going through the your commits https://github.com/dancannon/gorethink/commit/e75533a325c56c84b00a2bc2b9cc01c42b9c1ac2, https://github.com/dancannon/gorethink/commit/c0c7e176b23070b105f513ae53c78447a461f6fc
Sorry for false alarm :)
