### ISSUE TITLE
.Fold with FoldOpts crashes

### ISSUE THREAD

**Issue by peternoyes** [rethinkdb/rethinkdb-go#324]
Perhaps I am misunderstanding how to rewrite a .Fold query in Go, but it is just not working. I get a panic in Cursor line 161.

JavaScript:

``` javascript
r.db("environment").table("data").orderBy('date').fold(0, function(prev, cur) 
  { 
    return r.branch(cur("date").toEpochTime().sub(prev).gt(30), cur("date").toEpochTime(), prev); 
  }, { emit: function (prev, row, cur) 
  { 
    return r.branch(row("date").toEpochTime().eq(cur), [row], []);
  }
})
```

Go:

``` go
cursor, err := r.DB("environment").Table("data").Between(from, to, r.BetweenOpts{LeftBound: "open", Index: "date"}).OrderBy(r.OrderByOpts{Index: "date"}).Fold("", func(prev, cur r.Term) r.Term {
    return r.Branch(cur.Field("date").ToEpochTime().Sub(prev).Gt(interval), cur.Field("date").ToEpochTime(), prev)
}, r.FoldOpts{
    func(prev, row, cur r.Term) r.Term {
        return r.Branch(row.Field("date").ToEpochTime().Eq(cur), []interface{}{row}, []interface{}{})
    }, nil}).Run(rethink.Session)
```

I have tried to simplify the Fold to as simple as possible. Without the FoldOpts parameter I can get a query to not crash.

**Comment by dancannon** [comment]
Hi, I am really sorry for taking so long to reply but I completely missed this issue! Would it be possible to see the stack trace that the panic returns?

Also could you let me know what version of GoRethink and RethinkDB you are using.

**Comment by peternoyes** [comment]
I actually just tried it and it worked. The problem I guess was that my 'date' field was just a string in the database instead of an actual Time object. That is the only thing I have changed since I last tried this. Not a bug.
