### ISSUE TITLE
bad pointer frame panic in convertPseudotype

### ISSUE THREAD

**Issue by onufert** [rethinkdb/rethinkdb-go#325]
Hi Dan,

Hoping you might have an idea on this: About once a month our server panics and crashes with the following stack trace.

```
runtime: bad pointer in frame github.com/dancannon/gorethink.convertPseudotype at 0xc8203274d0: 0x1
fatal error: invalid stack pointer

runtime stack:
runtime.throw(0xaf0b50, 0x15)
    /usr/local/go/src/runtime/panic.go:527 +0x90 fp=0x7f26e7ffe8f0 sp=0x7f26e7ffe8d8
runtime.adjustpointers(0xc8203273f0, 0x7f26e7ffea68, 0x7f26e7ffec58, 0xc65858)
    /usr/local/go/src/runtime/stack1.go:438 +0x2d4 fp=0x7f26e7ffe9e8 sp=0x7f26e7ffe8f0
runtime.adjustframe(0x7f26e7ffeb78, 0x7f26e7ffec58, 0xc800000101)
    /usr/local/go/src/runtime/stack1.go:505 +0x1b5 fp=0x7f26e7ffeaa0 sp=0x7f26e7ffe9e8
runtime.gentraceback(0x413660, 0xc8203273a0, 0x0, 0xc820846a80, 0x0, 0x0, 0x7fffffff, 0xb96db0, 0x7f26e7ffec58, 0x0, ...)
    /usr/local/go/src/runtime/traceback.go:336 +0xa69 fp=0x7f26e7ffebd0 sp=0x7f26e7ffeaa0
runtime.copystack(0xc820846a80, 0x2000)
```

It's that stack trace each time, and no other trace into any of our/or gorethink code. 

Each time I've tried digging into the problem and come up with nothing. Unfortunately I have not been able to reproduce this reliably - again happens about once a month. Seen it about 4 or 5 times now.

Any ideas?

Using v1 of gorethink.

**Comment by dancannon** [comment]
Hey @onufert, thanks for reporting this issue. This is the first crash of this type I have heard of so I can't give you any feedback right now but I will look into it and get back to you when I find something.

**Comment by dancannon** [comment]
I had a look at the code but couldn't find anything obvious that would cause this crash, considering the error that was returned and the fact that it only occurs after running for a very long time it is possible that your application has some kind of memory leak or another process is modifying your applications memory space.

Is there any extra information you could provide that might narrow the issue down a bit?

**Comment by dancannon** [comment]
I am closing this as until I get more information there is not much I can do.

**Comment by onufert** [comment]
Apologies for not replying sooner. On holiday.

Thanks for giving it a look see. I also couldn't find anything obvious. I wish I had more information as well. This one is a stumper. I was initially suspicious that some other piece of our code was modifying the memory space, but find it strange that it always panics on that same convertPseudotype function. 

We'll put some more debug around this and maybe get better clues next time it happens.

Thanks again for the support!

**Comment by dancannon** [comment]
No worries, sorry for closing without discussing it first. Feel free to open if you find out anything more!
