### ISSUE TITLE
Connection Pool not closing connections

### ISSUE THREAD

**Issue by beatscode** [rethinkdb/rethinkdb-go#327]
I used to get errors regarding too many open files. So i increased the limit. However I took a look at  ls -l /proc/{PID}/fd | wc -l and saw that it kept growing to almost 1000 open files since starlit it about an hour ago.
The app basically makes multiple queries every 3-5 minutes. Right now it'll make about 100 queries every 3 minutes. 
So I was curious files are being opened and the 
`ls -l /proc/{PID}/fd` and `lsof -p 12950`
I saw socket:[3318919] and a list of what seems to be open sockets against the rethinkdb server on port 28015.  My question is do I need to close the connection after a certain amount of queries?

Here is my connection. I'm using an older version of the driver (0.5.0) Is there something I'm missing, I thought the configuration below was utilizing the pool functionality. 

```
    session, err = r.Connect(r.ConnectOpts{
        Address:     dbconn,
        Database:    "webpages",
        AuthKey:     pw,
        MaxIdle:     10,
        MaxActive:   20,
        IdleTimeout: time.Second * 10,
    })

```

How do I close connections? Do I need to explicitly call Close()?

**Comment by dancannon** [comment]
Hi @beatscode, while you should not close your session it is important that you close any `Cursor` values returned by any queries, for example:

``` go
cursor, err := r.DB("database").Table("tablename").Get(key).Run(session)
if err != nil {
    // error, we do not need to close the cursor as no cursor was returned
}
defer cursor.Close()
```

If you are still leaking connections with this change let me know, however I would strongly recommend upgrading to a version that is at least newer than v1.0.0 however I know this is difficult if you are running an older version of RethinkDB.

**Comment by beatscode** [comment]
That fixed it thank you.

**Comment by beatscode** [comment]
I started to get some errors after about a few 100 simple lookups/updates

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x0 pc=0x4df6b2]

goroutine 1 [running]:
panic(0x61cae0, 0xc82000e080)
    /usr/local/opt/go/libexec/src/runtime/panic.go:481 +0x3e6
github.com/dancannon/gorethink.(*Cursor).Close(0x0, 0x0, 0x0)
    /Users/alex/projects/go/src/github.com/dancannon/gorethink/cursor.go:53 +0x222
main.UpdateDomainExportTimestamp(0xc827f867f0, 0x14)
    /Users/alex/projects/go/src/com.abc/publishing/main.go:182 +0x55c
main.Export(0xc827f867f0, 0x14, 0xc82d002d40, 0x14, 0xc82ae36000, 0x17cc6, 0xc82ba42000, 0x39eb, 0x0, 0x0, ...)
    /Users/alex/projects/go/src/com.abc/publishing/main.go:167 +0x10f9
main.ExportRecentlyChangedDomains(0xc827f867f0, 0x14)
    /Users/alex/projects/go/src/com.abc/publishing/main.go:121 +0x97
main.main()
    /Users/alex/projects/go/src/com.abc/publishing/main.go:106 +0x805
```

Is this grounds to update I'm using 1.13

**Comment by dancannon** [comment]
Hi, it sounds like you are attempting to close the Cursor even if your query fails, in the code I posted I made the assumption that you would exit the function/program if an error was returned by `Run`, sorry if this was not clear.
