### ISSUE TITLE
Regrid support for Gorethink

### ISSUE THREAD

**Issue by ghost** [rethinkdb/rethinkdb-go#329]
[Regrid](https://github.com/internalfx/regrid) provides a wonderful way to store files in RethinkDB, similar to GridFS in MongoDB. Any chance it can be integrated with Gorethink?

**Comment by timshannon** [comment]
Sounds like they are planning on adding it to the official drivers as well:
https://github.com/rethinkdb/rethinkdb/issues/2647#issuecomment-219494013

**Comment by kofalt** [comment]
My 2 cents would be to add it once it becomes officially integrated - until then, maybe a separate project that uses gorethink to implement Regrid? Their [spec](https://github.com/internalfx/regrid-spec) looks straightforward.

**Comment by dancannon** [comment]
I agree with @kofalt, I think until this becomes part of the ReQL spec it should be kept as a separate project, that being said I will try and look into implementing this spec soon, I will update this issue when I figure out what exactly is required.

**Comment by internalfx** [comment]
@dancannon @kofalt Developer of regrid here...

Feel free to contact me if I can be of assistance with this. The spec is a little out of date compared to the actual node driver. I can easily point out the changes if there is any interest from a go developer (which I am not).

**Comment by dancannon** [comment]
Thanks @internalfx! Adding regrid support is definitely on my roadmap however I am trying to work a little bit on improving testing + documentation at the moment.

Hopefully I will be able to start working on regid support next month some time (or maybe the month after) and I am sure I will have lots of questions 😄

**Comment by dancannon** [comment]
I have spent a little bit of time today implementing regrid support as a separate [package](https://github.com/dancannon/gorethink-regrid), there are no docs yet but I have tried to test everything so if you are interested in how the API looks feel free to have a look.

**Comment by internalfx** [comment]
@dancannon didn't know you already we're starting this.

FYI...the spec will change. If I we're you, I would follow the node regrid API docs over the regrid spec for now.

**Comment by internalfx** [comment]
@dancannon At first glance your indexes look good...

I am hoping to convince everyone to use the same names, indexes, etc...

I think the ultimate goal is that I can write with the node driver and read with the gorethink driver, or vice versa.

**Comment by dancannon** [comment]
@internalfx I got bored yesterday so I decided to start writing it 😆 I based my implementation partly on the spec and partly on the Node implementation so hopefully it should be completely compatible, I will definitely make sure that is the case before I release anything.

What changes do you expect you will be making to the spec? I will try to put a readme together soon to give you a proper idea of what the library supports.

**Comment by dancannon** [comment]
Due to some of the recent RethinkDB news I have decided to halt development of this feature. As far as I can tell the implementation should work exactly the same as the JS implementation and all of the tests are passing locally however there is very little documentation.

Hopefully the code will be useful to some people.

https://github.com/dancannon/gorethink-regrid

**Comment by internalfx** [comment]
> Due to some of the recent RethinkDB news I have decided to halt development of this feature.

I checked RethinkDBs twitter, and blog.... :confused: 

What news are you referring to?

**Comment by Coccodrillo** [comment]
@internalfx I suspect this https://discuss.horizon.io/t/are-rethink-and-horizon-dead-abandoned/619/8

**Comment by kofalt** [comment]
A bit more information from Slava:

https://news.ycombinator.com/item?id=12642060
