### ISSUE TITLE
Public access to built Term

### ISSUE THREAD

**Issue by rgzr** [rethinkdb/rethinkdb-go#330]
A `Term` has a `build()` method which returns term data in rdb wire protocol format ready to be JSON-serialized and sent to the server.

If that method was public it would be possible to serialize a `Term`, send it to another application and let that application execute it on the rethinkdb server. ¿Could that method be public?

**Comment by dancannon** [comment]
Hi, I think this suggestion makes sense. If I have time time I will look into exporting `build()` in the next release.

**Comment by dancannon** [comment]
The changed has been released to master.
