### ISSUE TITLE
Field(int) after GetAll() or GetAllByIndex()

### ISSUE THREAD

**Issue by bakape** [rethinkdb/rethinkdb-go#333]
Hello, I'm trying to get a query that works in the official JS driver done in gorethink. 

`r.table("images").getAll("1")(0).update({foo: "bar"})` in the official JS API is valid and updates the first document found.

`r.Table("images").GetAll("1").Field(0).Update(map[string]string{"foo": "bar"})` returns an `Expected type SELECTION but found SEQUENCE:\nVALUE SEQUENCE` in the `Update` part of the query. 

`r.Table("images").GetAll("1").Update(map[string]string{"foo": "bar"})` works just fine.

I assume this a bug, or am I missing some specific difference in the APIs?

**Comment by dancannon** [comment]
Hey @bakape thanks for the bug report, could you please show an example of what the `images` table looks like?

**Comment by bakape** [comment]
I've tested this with a single document table `{id: "1"}` and with an empty table, by adding `.Default(nil)` to the end of both queries. `GetAllByIndex` produced identical results with a single index table. At first glance it does not seem like the contents of the table matter.

**Comment by dancannon** [comment]
Sure but having an example will help me replicate the issue.

**Comment by bakape** [comment]
Minimal reproduction script: https://gist.github.com/bakape/cda519e0172cd8d37492ef6ef1545bc8

**Comment by dancannon** [comment]
Great, that helped me figure out the cause of the issue. In GoRethink `Field` uses the `GET_FIELD` ReQL term instead of the `Bracket` term, if you are trying to use an integer index use the `AtIndex` function instead, for example:

``` go
r.Table("test").
    GetAll("1").
    AtIndex(0).
    Update(map[string]string{"foo": "bar"}).
    Exec(session)
```

**Comment by bakape** [comment]
I see. Thanks! Working as intended then?
