### ISSUE TITLE
Multi-document transactions

### ISSUE THREAD

**Issue by ghost** [rethinkdb/rethinkdb-go#334]
Is it possible that something like [this](https://godoc.org/labix.org/v2/mgo/txn) can be developed for RethinkDB. From what I understand in [this](http://blog.labix.org/2012/08/22/multi-doc-transactions-for-mongodb) article, support for single document transaction is a prerequisite which is already there in RethinkDB. Any thoughts?

**Comment by timshannon** [comment]
:+1:   At some point I wanted to take a stab at reimplementing that specific library via gorethink.  

I'm not sure if it should be part of the driver, but a separate lib makes a lot of sense in my opinion.

**Comment by dancannon** [comment]
Hey, thanks for the suggestion. While I think its a great idea I cant see myself working on this right now and I definitely think it should be kept separate to GoRethink (or at least as a sub-package similar to mgo).

**Comment by dancannon** [comment]
I am closing this issue for now as I am not sure when I will be able to work on this.
