### ISSUE TITLE
Filter()

### ISSUE THREAD

**Issue by olliephillips** [rethinkdb/rethinkdb-go#335]
I'm seeing some unexpected behaviour using `Filter()`. I am a novice with RethinkDB and this driver but I thought I would flag. I am checking a table to ascertain if a username is available before inserting a new user record

This is the code:-

```
func (d *DB) UsernameExists(username string) bool {
    res, err := r.Table("user").Filter(map[string]interface{}{
        "username": username,
    }).Run(d.Session)
    if err != nil {
        fmt.Println("r.Table", err)
        return false
    }
    defer res.Close()

    var users []interface{}
    err = res.All(&users)
    if err != nil {
        fmt.Printf("Error scanning database result: %s", err)
        return false
    }
    log.Println(len(users))

// remaining code not relevant
....
```

If a document with matching username exists in the table , I get len(users)  = 1. As expected, and same behaviour as RethinkDB Data Explorer query

If the document with matching username does not exist in table , len(users) count is all rows in the table? RethinkDB Data Explorer query returns the result I would have expected and want, "No Results Returned"

Should I expect this behaviour - is my query not constructed properly, or is this an issue with the driver?

**Comment by olliephillips** [comment]
Hey Dan, I'm sorry, I think I my logging was screwed up, this seems to be functioning when I've come back to it. I am closing this - red herring.

**Comment by dancannon** [comment]
No worries, glad you sorted it out!
