### ISSUE TITLE
How to populate the content to a table HTML?

### ISSUE THREAD

**Issue by iAdolph** [rethinkdb/rethinkdb-go#336]
I wonder if I can advise how I can fill the content of the table Rethink , regardless of the number of rows contained .

Following your example , try to tables but I have no success , all the records contained in the sample Rethink me in only one row

Html Code

```
<!doctype html>
<html lang="en" data-framework="javascript">
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <title>Gorethik </title>
        <link rel="stylesheet" href="/css/main.css">
    </head>
    <body>
        <section id="todoapp">
            <header id="header">
                <h1>SAS</h1>
                  <form method="POST" action="/new">
                    <input name="text" id="new-todo" placeholder="What needs to be done?" autofocus>
                </form>
            </header>
            <section id="main">

                <!-- Table -->
                <table border = "1" id="todo-list">{{range .Items}}
                    <thead></thead>
                    <tbody>
                        <tr>
                            <td data-id="{{.Id}}" class="{{.}}">
                                <span>{{.}}</span></tbody>
                            </td>
                        </tr>
                    <tfoot></tfoot>
                    {{end}}
                </table>
            </section>
            <footer id="footer">
                <span id="todo-count"></span>
                <ul id="filters">
                    <li>
                        <a href="/all">All</a>
                    </li>
                    <li>
                        <a href="/active">Active</a>
                    </li>
                    <li>
                        <a href="/completed">Completed</a>
                    </li>
                </ul>
                <a href="/clear" class="button" id="clear-completed">Clear completed</a>
            </footer>
        </section>
        <footer id="info">
            <p>Double-click to edit a todo</p>
        </footer>
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.3/jquery.min.js"></script>
        <script src="/js/main.js"></script>
        <script type="text/javascript">
            connect("{{.Route}}");
        </script>
    </body>
</html>
```

JS Code 

```
function connect(path, TableJSON, columnID, container) {
    var ws = new WebSocket("ws://localhost:8085/WS/"+path);
    var list = $("#todo-list");

    ws.onmessage = function(e) {
        var data = JSON.parse(e.data);

        if (data.old_val === null && data.new_val !== null) {
            // new item
            var item = data.new_val;
            var thead = false;
            var theaders = "";

            $('#'+container+'tbody').empty();
            $('#'+container+'thead').empty();
            $('#'+container+'tfoot').empty();

            $.each(TableJson,function(row,data_column){
                var html_init_tr ="<tr>";
                var html_row = "";

                $.each(data_column,function(column,value){
                    if(colum == columnID){
                        html_init_tr = "<tr id='"+value+"'>";
                    }
                    html_row = html_row+"<td data-id='"+item.Id+"' class='"+item.Items+"'>"+"<span>"+item.items+"</span>"+"</td>";
                    if(thead == false){
                        theaders = theaders+'<th>'+column'</th>';
                    }
                });
                thead = true;
                html_row = html_init_tr+html_row+"</tr>";
                $('#'+container+'tbody').append(html_row);
            });
            $('#'+container+'thead').append('<tr>'+theaders+'</tr>');
            $('#'+container+'tfoot').append('<tr>'+theaders+'</tr>');


        } else if (data.old_val !== null && data.new_val === null) {
            // deleted item
            var item = data.old_val;
            $("[data-id='"+item.id+"']").remove();
        } else {
            // updated item
            var item = data.new_val;
            $("[data-id='"+item.id+"']").attr("class", item.Status);
        }
    };
}
```

Hoping you can support me with this, thank you very much .

**Comment by dancannon** [comment]
Hi @iAdolph, I am not really sure what your question is here, could you provide some more information?

**Comment by iAdolph** [comment]
Hi Dan , if you look in your TodoList example , the values ​​are inserted into a list `<ul><li>`. Well my intention is to show the information in a table `<table>`, but with the condition that display all the values ​​in a table without having to set the headers of the table shown (Id, Text, Status).

I hope to be clearer, and excuse my English....

**Comment by dancannon** [comment]
Thanks @iAdolph, I think I understand what you are trying to do, what results are you seeing currently?

**Comment by gabeio** [comment]
I believe you need to change the `{{.}}` to the field name you want to be showing?
this:

``` html
<span>{{.}}</span>
```

to something like:

``` html
<span>{{.Body}}</span>
```

_sidenote: remember in golang all fields that are lowercase are private._

**Comment by iAdolph** [comment]
If , now total 3 rows shown in a Id + Text + Status alone, but the intention is that each record is in each row for each column

![2016-06-17_16-30-09](https://cloud.githubusercontent.com/assets/20000572/16165824/e274ee4c-34ab-11e6-873e-0f891ac62758.png)

**Comment by iAdolph** [comment]
From these values, would show as follows :

----------------------------------------------------------| ----------------------- | ------------------|
                  Id                                                 |           Text           |        Status     |
---------------------------------------------------------- | ---------------------- | ------------------ |
40bedeb1-b5ac-488a-8e78-379da123be81  |  Hello Seahorse      active

I wrote this code...

`table.append(""+
            "<tr>"+
                "<td data-id='"+item.Id+"' class='"+item.Status+"'>"+
                    "<span>"+item.Text+"</span>"+
                "</td>"+
                "<td data-id='"+item.Id+"' class='"+item.Status+"'>"+
                "   <span>"+item.Status+"</span>"+
                "</td>"+
            "</tr>"+
            "");`

And if it works , but if a new column is created , my code would have to modify and add the header , so I would like it to be dynamic...

Regards...

**Comment by dancannon** [comment]
I would suggest changing the data structure used for `Items` to a map to allow for easier iteration as it looks like one issue you currently have.

Regarding the JavaScript issue you are having I am not too sure how to help without seeing more code however I think [StackOverflow](stackoverflow.com) would be a better place to ask that question.
