### ISSUE TITLE
Merge subquery is not consistent.

### ISSUE THREAD

**Issue by pieperz** [rethinkdb/rethinkdb-go#338]
I am getting some odd behavior running the Merge subquerry below I am not getting consistent results. The results of lastPing will sometimes come back null then on subsequent queries I will get different results but the data has not changed. 

```
res, err := r.DB("myDB").Table("sites").
        Filter(map[string]interface{}{"userId": userID}).
        Merge(func(sites r.Term) interface{} {
            lastPing := r.DB("myDB").Table("pingHistory").
                GetAllByIndex("siteID", sites.Field("id")).
                OrderBy(r.Desc("time")).
                Nth(0).
                Pluck("resultCode")

            return map[string]interface{}{
                "status": lastPing.Field("resultCode"),
            }
        }).
        OrderBy(r.Asc("Created")).
        Run(session)


```

Currently my structure has a 'sites' and 'pingHistory' table. Each site in the 'sites' table has many pings in 'pingHistory'.

The end result of this query should be the sites table filtered for a user with a new property called status that is the resultCode of the latest pingHistory for a site. 

I came up with this query strategy from https://github.com/dancannon/gorethink/issues/291 it seemed to be doing a similar type of query. 

I have not created this query in JS.

Thanks for any help.

**Comment by dancannon** [comment]
Hi @pieperz, sorry to hear you are having issues. I will look into the problem and see if I can either solve or replicate the issue and get back to you soon.

**Comment by dancannon** [comment]
I couldn't manage to replicate your issue however I did make one change to your query by adding `Default(map[string]interface{}{"resultCode": 0})` after `Nth(0)` to ensure that if any sites did not yet have any ping data then the query would still succeed. Would it be possible for you to post the data you are using that has this issue and the code you are using to decode the response?

Here is the code I was using in my tests:

``` go
package main

import (
    "time"

    "github.com/davecgh/go-spew/spew"

    r "github.com/dancannon/gorethink"
)

func main() {
    session, _ := r.Connect(r.ConnectOpts{Address: "localhost:28015"})

    userID := "user_1"

    r.DB("test").TableDrop("sites").Exec(session)
    r.DB("test").TableDrop("pingHistory").Exec(session)
    r.DB("test").TableCreate("sites").Exec(session)
    r.DB("test").TableCreate("pingHistory").Exec(session)
    r.DB("test").Table("pingHistory").IndexCreate("siteID").Exec(session)
    r.DB("test").Table("pingHistory").Wait().Exec(session)

    r.DB("test").Table("sites").Insert(map[string]interface{}{"id": "site_1", "userId": userID, "created": time.Now()}).Exec(session)
    r.DB("test").Table("sites").Insert(map[string]interface{}{"id": "site_2", "userId": userID, "created": time.Now().Add(-time.Hour * 2)}).Exec(session)
    r.DB("test").Table("sites").Insert(map[string]interface{}{"id": "site_3", "userId": userID, "created": time.Now().Add(-time.Hour * 1)}).Exec(session)

    r.DB("test").Table("pingHistory").Insert(map[string]interface{}{"siteID": "site_1", "resultCode": 500, "time": time.Now().Add(-time.Second * 5)}).Exec(session)
    r.DB("test").Table("pingHistory").Insert(map[string]interface{}{"siteID": "site_1", "resultCode": 200, "time": time.Now().Add(-time.Second * 15)}).Exec(session)
    r.DB("test").Table("pingHistory").Insert(map[string]interface{}{"siteID": "site_1", "resultCode": 200, "time": time.Now().Add(-time.Second * 25)}).Exec(session)
    r.DB("test").Table("pingHistory").Insert(map[string]interface{}{"siteID": "site_2", "resultCode": 200, "time": time.Now().Add(-time.Second * 5)}).Exec(session)
    r.DB("test").Table("pingHistory").Insert(map[string]interface{}{"siteID": "site_2", "resultCode": 200, "time": time.Now().Add(-time.Second * 15)}).Exec(session)
    r.DB("test").Table("pingHistory").Insert(map[string]interface{}{"siteID": "site_2", "resultCode": 500, "time": time.Now().Add(-time.Second * 25)}).Exec(session)

    res, err := r.DB("test").Table("sites").
        Filter(map[string]interface{}{"userId": userID}).
        Merge(func(sites r.Term) interface{} {
        lastPing := r.DB("test").Table("pingHistory").
            GetAllByIndex("siteID", sites.Field("id")).
            OrderBy(r.Desc("time")).
            Nth(0).
            Default(map[string]interface{}{"resultCode": 0}).
            Pluck("resultCode")

        return map[string]interface{}{
            "status": lastPing.Field("resultCode"),
        }
    }).OrderBy(r.Asc("Created")).Run(session)

    if err != nil {
        panic(err)
    }

    var response []interface{}
    err = res.All(&response)
    if err != nil {
        panic(err)
    }

    spew.Dump(response)
}
```

**Comment by pieperz** [comment]
Thanks for the tip on Default() that will come in handy. I had already hit that bug and had switched it to a Limit() and changed the query. The query below still has the same bug. 

This is the full method.

```
// ListUserSites ...
func ListUserSites(userID string) ([]*model.Site, error) {
    sites := []*model.Site{}

    res, err := r.DB("test").Table("sites").
        Filter(map[string]interface{}{"userId": userID}).
        Merge(func(sites r.Term) interface{} {
            latestStatus := r.DB("test").Table("pingHistory").
                GetAllByIndex("siteID", sites.Field("id")).
                OrderBy(r.Desc("time")).
                Limit(50).
                Default(map[string]interface{}{"pingHistory": nil}).
                CoerceTo("array")

            return map[string]interface{}{
                "pingHistory": latestStatus,
            }
        }).
        OrderBy(r.Asc("Created")).
        Run(session)

    if err != nil {
        return nil, err
    }
    err = res.All(&sites)
    if err != nil {
        return nil, err
    }

    return sites, nil

}
```

I don't have any demo data that I can send to you in go. But I can send you the tree view or raw view from the rethink admin site. 

Is there any particular way that would make it easy on you. I can create some demo data like your test if that is easiest.

**Comment by dancannon** [comment]
Thanks for sending the code over so quickly. The raw view would be perfect, if you are not comfortable posting it on Github feel free to email it to me. 

I am heading offline for today but I will try to look again evening.

**Comment by pieperz** [comment]
np email sent.

**Comment by dancannon** [comment]
I think I have figured out what is happening, because you are using the same data structure for creating the `sites` and reading them back there is a naming conflict which due to the way Go treats maps results in inconsistent results. (If you have a look at the raw `sites` data there should be a field called `PingHistory` however your merge subquery is adding the `pingHistory` field)

To resolve this issue I would ensure that any fields in your data structure have struct tags or I would change the field your merge query creates. Another solution would be to use a slightly different data structure when reading and writing.

Let me know if this hasnt solved your issue or you have any other questions.

**Comment by pieperz** [comment]
You are correct PingHistory was missing its struct tag. My results are coming back consistently after the fix.

Thanks for the help.
