### ISSUE TITLE
Get current DB in use

### ISSUE THREAD

**Issue by mfzl** [rethinkdb/rethinkdb-go#339]
Is  there a way to get the current db in use, after `db.Use`?

**Comment by dancannon** [comment]
Hi @faxal, this is not currently possible as the options are not exported however it should be easy enough to implement a `Database()` function in the next release.

**Comment by mfzl** [comment]
:+1: That would be great

**Comment by dancannon** [comment]
The `develop` branch now includes a `Database()` function in `Session`, I am not sure when this will be merged but hopefully it shouldnt be too long.

**Comment by dancannon** [comment]
Released as part of `v2.1.1`, sorry for the delay

**Comment by mfzl** [comment]
Fantastic! Thank you so much :smile:
