### ISSUE TITLE
Between on compound index

### ISSUE THREAD

**Issue by lomithrani** [rethinkdb/rethinkdb-go#341]
Hello, 
I've been trying to make this following reql with gorethink and fail miserabily. I get no error in the debugger I'm just stuck on the request

reql 
`r.db("myDb").table("myTable").between(["myHash",r.time(2012,1,1,'Z')], ["myHash",r.now()], {"index": "userHash_date"}).orderBy({"index": r.desc("userHash_date")}).count()`

Go: 

```
betweenOpts := gr.BetweenOpts{Index: "userHash_date"}
orderByOpts := gr.OrderByOpts{Index: gr.Desc("userHash_date")}
start := gr.Time(2012, 1, 1, 'Z')
end := gr.Time(time.Unix(ilast, 0))
res, err := gr.DB("MyDb").Table("myTable", gr.TableOpts{ReadMode: "outdated"}).Between([]interface{}{id, start}, []interface{}{id, end}, betweenOpts).OrderBy(orderByOpts).Limit(qty).Run(prog.Session)
```

I'm wondering if I'm doing something wrong or if gorethink doesn't support compound indexes on between.

Thanks for your help !

**Comment by lomithrani** [comment]
Well sorry, my request as actually good it's my gr.Time that were wrong...

**Comment by dancannon** [comment]
Hey, glad you figured out the issue 😄  Do you have any other questions?
