### ISSUE TITLE
Compound primary keys

### ISSUE THREAD

**Issue by tve** [rethinkdb/rethinkdb-go#342]
RethinkDB doesn't support compound primary keys but it does support arrays as primary keys. The downside is that this makes a mess of marshaling and unmarshaling. I'm wondering whether it would be worth adding some magic tag or whether I'm missing some trick. Basically, suppose I have:

```
type User struct {
  Company string `gorethink:"company"`
  Name    string `gorethink:"name"`
  Age     int    `gorethink:"age"`
}
```

and I want a compound primary key on company&name then I need to transform this into

```
type User struct {
  ID   []string `gorethink:"id"` // really: []string[company, name]
  Age int       `gorethink:"age"`
}
```

I'm wondering whether it would be doable to introduce something like:

```
type User struct {
  Company string `gorethink:"id[0]"`
  Name    string `gorethink:"id[1]"`
  Age     int    `gorethink:"age"`
}
```

Thoughts? Obviously it would be nicest if the DB supported compound primary keys, but I'm not seeing it happen soonish: https://github.com/rethinkdb/rethinkdb/issues/3875

**Comment by dancannon** [comment]
Hey @tve, thanks for the suggestion, I really like the idea and think it will definitely make it easier for some people to use the driver (which is something I am trying to work on at the moment). 

I will try to have a think about your solution and see if there are any edge cases that it will not work for and try to think about how it might be implemented but I hope that I will have a working solution to this issue in a couple of weeks.

**Comment by dancannon** [comment]
Hey @tve, I have just created a PR for this issue, if you have the time (and are comfortable with reflection) would you be able to review the changes? Thanks!

**Comment by tve** [comment]
Oh cool, yes, I'll review.

**Comment by dancannon** [comment]
Closing as this has now been merged to `develop` and should be release shortly.
