### ISSUE TITLE
Add ability to mock only part of a query

### ISSUE THREAD

**Issue by dancannon** [rethinkdb/rethinkdb-go#347]
Currently mocking only supports exact query matching meaning that you need to know exactly what your query is and exactly what data you are inserting, this is not always possible so having some kind of way of adding some kind of wildcard matching. 

This is not currently possible due to the way that the mocking is implemented however it should be possible to replace this code. The API for this might look something like this:

``` go
// Allow any insert to the table test
r.Table("test").Insert(r.MockAnything())

// Allow any insert of a slice to the table test
r.Table("test").Insert(r.MockAnythingOfType([]interface{}{})

// Allow any query on the table test
r.Table("test").MockAnything()
```

**Comment by dancannon** [comment]
@pzduniak I noticed that you have started working on an implementation of this, would you be interested in creating a PR and merging your changes upstream?

**Comment by dancannon** [comment]
Released improved mocking implementation as part of `v2.2.0`

**Comment by pzduniak** [comment]
Oops, forgot to reply to you :) I was worried about some functionality (such as function args) so I decided not to bother you with my tries at implementing it. Thanks for finishing the code, being able to replace `MockAnything()` with `row` feels awesome.

**Comment by dancannon** [comment]
No worries :) I extended your implementation to better support the function args, hopefully it covers everything! I also mentioned you in the changelog to thank you for all of your work (since you did 90% of this issue 😄 ). If you think of anything else you would like to add let me know.

**Comment by cirelli94** [comment]
Mmm I think only MockAnything has been implemented.
Is there any update for MockAnythingOfType?

**Comment by cirelli94** [comment]
I'm looking at issue #346 , but it looks like it's not working to me...
I'm doing something like:
```
	anObj := model.Object {
		ID:          "",
		Created:    r.MockAnything().String(),
		LastModify:  r.MockAnything().String(),
	}

	mock.On(r.Table("object").
		Insert(anObj)
		Return(nil, nil)
```
if I set Created and LastModify to "fooBar" it works, but they are fields with time.Now().String() normally and the r.MockAnything().String() doesn't do its job I think...
