### ISSUE TITLE
Closing a cursor while its blocked?

### ISSUE THREAD

**Issue by foliot** [rethinkdb/rethinkdb-go#348]
Is it possible to close a cursor while it is being blocked by something like Next? Equivalently, is it possible to close a cursor after you’ve called listen on it, but before it completes?

**Comment by dancannon** [comment]
Hi @foliot, you are able to call `Close()` at any time even if the cursor is being used to listen to a changefeed or of the cursor is already closed. If the cursor is being blocked while it waits for results and you close the cursor in another goroutine then the call to `Next` will  become unblocked and return `false`.

**Comment by foliot** [comment]
Hi @dancannon. Thanks for the response!

It seems like `Close` would be blocked by `Next` due to `c.mu`. I might be missing something though. Unless I'm mistaken, a goroutine trying to close another goroutine could be blocked indefinitely until the next value is returned by the cursor.

**Comment by dancannon** [comment]
The cursor is actually unlocked when waiting for data from the database https://github.com/dancannon/gorethink/blob/master/cursor.go#L510-L512. During this time it is possible to call `Close()` without causing a deadlock.

**Comment by foliot** [comment]
Ah, gotcha. Thanks!
