### ISSUE TITLE
Multiplexing queries on a single connection?

### ISSUE THREAD

**Issue by foliot** [rethinkdb/rethinkdb-go#349]
Unless I'm misunderstanding the [driver doc](https://www.rethinkdb.com/docs/writing-drivers/#notes-on-connections), multiple requests can be performed in parallel over the same database connection. Is this possible in gorethink?

**Comment by dancannon** [comment]
This is not currently supported by GoRethink however I am looking into changing this. That being said a GoRethink `Session` implements a connection pool and is thread safe so you should be able to use a single session over multiple requests/goroutines.

**Comment by foliot** [comment]
Great, thanks!
