### ISSUE TITLE
.Without("id").Run() returns no data at all  

### ISSUE THREAD

**Issue by olliephillips** [rethinkdb/rethinkdb-go#350]
I'm having problems suppressing the tables ("id") in returned data using 'without'. It works fine with all other fields, but if I use `.Without("id")` I get no data at all returned, but no err value either.

This is the Go code I'm trying:-

```
    var result ResultType
    res, err := r.DB("mydatabase").Table("mytable").Filter(map[string]interface{}{
        "id":  id,
        "key": key,
    }).Without("id").Run(d.Session)
    if err != nil {
        fmt.Println("mydatabase, mytable", err)
        return &result, err
    }
    defer res.Close()
    res.One(&result)
    return &result, nil
```

The query returns fine if I swap `.Without("id")` out and try suppress key with `.Without("key")`.

In Rethinkdb data explorer this equivalent query works as expected:-

```
r.db('mydatabase').table('mytable').filter({"id":"68d2b535-72b2-4771-a3ba-776c6878888a","key":"f7c04eaf-5510-5878-b3d1-abfacad3c60f"}).without("id")
```

Something I'm doing wrong or is this a bug?

**Comment by samb1729** [comment]
Can you share ResultType? I'll see if I can figure out the issue :)

(Disclaimer: I've never used this library before)

**Comment by olliephillips** [comment]
`ResultType` is a struct, it contains a number of properties, but id and key as used in `Filter()` and `Without()` above look like this.

```
type ResultType struct {
    Id     string   `gorethink:"id,omitempty" json:"id,omitempty"`
    Key    string   `gorethink:"key,omitempty" json:"key,omitempty"`

.....

}
```

**Comment by dancannon** [comment]
I put together a really simple script that replicates your snippet of code and it seems to work on my end and it appears to work as it should, is your code doing anything differently to this example?

``` go
package main

import (
    "fmt"

    r "github.com/dancannon/gorethink"
)

type ResultType struct {
    Id    string `gorethink:"id,omitempty" json:"id,omitempty"`
    Key   string `gorethink:"key,omitempty" json:"key,omitempty"`
    Field string `gorethink:"field,omitempty" json:"field,omitempty"`
}

func main() {
    session, err := r.Connect(r.ConnectOpts{Address: "localhost:28015"})
    if err != nil {
        panic(err)
    }

    id := "1"
    key := "key"

    r.TableDrop("test").Run(session)
    r.TableCreate("test").Run(session)
    _, err = r.Table("test").Insert(ResultType{
        Id:    id,
        Key:   key,
        Field: "field",
    }).Run(session)
    if err != nil {
        panic(err)
    }

    var result interface{}
    res, err := r.DB("test").Table("test").Filter(map[string]interface{}{
        "id":  id,
        "key": key,
    }).Without("id").Run(session)
    if err != nil {
        panic(err)
    }
    defer res.Close()
    res.One(&result)

    fmt.Println(result)
}
```

```
map[field:field key:key]
```

**Comment by olliephillips** [comment]
I'll set this up and test the script my end. Thank you for this. Looking at the code now, the only thing that jumps out as different is `r.ConnectOpts(...)`.

I'm including the Database as well as the Username/Password piece of the User granted permissions on those tables.

This is a straight lift of my r.ConnectOpts(..) call.

```
r.ConnectOpts{
    Address:  os.Getenv("RETHINKDB_ADDRESS"),
    Database: os.Getenv("RETHINKDB_DATABASE"),
    Username: os.Getenv("RETHINKDB_USERNAME"),
    Password: os.Getenv("RETHINKDB_PASSWORD"),
})
```

**Comment by dancannon** [comment]
There was a small bug in the script I posted, I just edited the comment with a corrected version.

**Comment by olliephillips** [comment]
Setting up, I get compile errors so I've switched to the v2 driver I'm using, but, no matter, the script you posted runs for me.  

I'll try your code against my database

**Comment by olliephillips** [comment]
@dancannon Your code runs with same user granted permissions on the test table too. Bit stuck. but must be my side. Thanks for your help, I'll pick up tomorrow.

**Comment by olliephillips** [comment]
I point the same code at table of mine. I get `<nil>` :/

**Comment by dancannon** [comment]
Weird... If you want jump on the #gorethink channel on the RethinkDB slack and we can look into why this is happening.

**Comment by olliephillips** [comment]
Thanks Dan - it's my side defo - I've now got a good return using your code on my table with auth.  id excluded. Thank you for your help tonight. Appreciated.
