### ISSUE TITLE
Populate model with the new value after an Update

### ISSUE THREAD

**Issue by acroca** [rethinkdb/rethinkdb-go#353]
Hi,

I'm doing an Update with `ReturnChanges: true` and I'd like to get a model object with the results, the same as doing a query and `.One(&user)` for queries but with the `NewValue` of the changes.
Is that possible? I can't find a way.

Thanks in advance.

**Comment by dancannon** [comment]
Hi @acroca, due to the way `ReturnChanges` works you need to change the data structure you are decoding your result into. Here is a simple example:

``` go
package main

import (
    "fmt"

    r "github.com/dancannon/gorethink"
)

type User struct {
    ID   string `gorethink:"id,omitempty"`
    Name string
}

func main() {
    session, err := r.Connect(r.ConnectOpts{
        Address:  "localhost:28015",
        Database: "test",
    })
    if err != nil {
        panic(err)
    }

    user := User{
        Name: "John Smith",
    }

    cur, err := r.Table("test").Insert(user, r.InsertOpts{
        ReturnChanges: true,
    }).Run(session)
    if err != nil {
        panic(err)
    }

    var result struct {
        Changes []struct {
            NewVal User `gorethink:"new_val"`
        }
    }
    if err := cur.One(&result); err != nil {
        panic(err)
    }

    if len(result.Changes) > 0 {
        user = result.Changes[0].NewVal
    }

    fmt.Println(user)
}
```

**Comment by acroca** [comment]
I see. That makes sense. I guess I can also use the `encoding` package, right? Something like 

``` go
res, err := dp.db.Table("users").Insert(user, gorethink.InsertOpts{
  ReturnChanges: true,
}).RunWrite(dp.session)
if err != nil {
  panic(err)
}

encoding.Decode(user, res.Changes[0].NewValue)
```

In any case, your solution should work, so I close this issue :)

Thanks a lot!

**Comment by dancannon** [comment]
Yes that would also work, although its a bit more inefficient since you would then be decoding the document twice.

**Comment by acroca** [comment]
good point :)
