### ISSUE TITLE
Migrate library from gopkg.in to Glide

### ISSUE THREAD

**Issue by dancannon** [rethinkdb/rethinkdb-go#357]
As discussed in #289 the Go community seems to be moving away from gopkg.in to package managers such as Glide and this library should probably do the same. To try and ensure that existing applications are not affected the following steps should be followed:
- [x] Create `v1` branch from the `v1.x.x` tag
- [ ] Create `v2` branch from the `v2.x.x` tag
- [ ] Add glide.yaml
- [ ] Remove gopkg.in imports
- [ ] Release `v3.0.0`

**Comment by aeneasr** [comment]
this looks like a reasonable plan, thanks!

**Comment by dancannon** [comment]
I am closing this issue for now as I am not sure when v3 will be released.
