### ISSUE TITLE
Filter with two fields 

### ISSUE THREAD

**Issue by iamhuy** [rethinkdb/rethinkdb-go#359]
Hello,
I am having a problem with filter function by gorethink.
In my table, I have two field: 

```
"createdTime": 1467941484 , // epoch time, type integer
"date": 20160708 , // date label, type integer too
```

Now I want to filter all the documents that have "createdTime" is the same day with "date".
`func EpochTime(args ...interface{}) Term`
I found this but I am still stuck in how to use it in this case .
Looking forward to your response
Thank you very much.

**Comment by dancannon** [comment]
Something like this should do what you want (just FYI I have not had time to test this but hopefully it should work):

``` go
r.Table("documents").Filter(func(row r.Term) interface{} {
    return r.EpochTime(row.Field("createdTime")).Date().Eq(r.EpochTime(row.Field("date")).Date())
})
```
