### ISSUE TITLE
Geo Query Error -> undefined: GetNearestOpts

### ISSUE THREAD

**Issue by Linicks** [rethinkdb/rethinkdb-go#360]
All,
  I'm trying to implement this query with GoRethink.  I believe that I have it right, but couldn't find any examples in the docs.  Here is what I have:

Origional Query From The Data Explorer:

> var point = r.point(-122.422876,37.777128);
>    r.db('geo_test').table('geo').getNearest(point, {index: 'location', maxDist: 500, unit: 'mi'})  

My Code

> var point = r.Point(-122.422876, 37.777128)
>   result, err := r.DB("geo_test").Table("geo").GetNearest(point, GetNearestOpts{Index: "location", MaxDist: 500, Unit: "mi"}).Run(session)

The Error:

> go run test2.go  
>   # command-line-arguments  
>   ./test2.go:39: undefined: GetNearestOpts               

Thanks!
--Nick

**Comment by dancannon** [comment]
Try changing your code to the following (as the GetNearestOpts type is in the GoRethink package it is important to include the `r.`)

``` go
var point = r.Point(-122.422876, 37.777128)
result, err := r.DB("geo_test").Table("geo").GetNearest(point, r.GetNearestOpts{Index: "location", MaxDist: 500, Unit: "mi"}).Run(session)
```

**Comment by Linicks** [comment]
Dan,
  Thanks for the quick response!  That was the issue.  The only example that I could find was in this test(  https://github.com/dancannon/gorethink/blob/ca0916a6f1e5999f7a2188444dd20b1865038c54/query_geospatial_test.go#L343), and it doesn't implement the r.GetN*\* semantics.  It may be helpful to add a couple of examples to the readme for us GoRethink newbies :)

Thanks!
--Nick

**Comment by dancannon** [comment]
Great 😄  Adding more documentation + examples is definitely on my roadmap but I am not quite sure when I will have time for that just yet (hopefully not too long!)
