### ISSUE TITLE
Insert() and object generated ID

### ISSUE THREAD

**Issue by allochi** [rethinkdb/rethinkdb-go#368]
Hi, is there a way to let `Insert()` update the object with the generated ID?

**Comment by allochi** [comment]
Could someone correct me, the only way to do this is to reselect the object again using `Get()`?

**Comment by dancannon** [comment]
Hi @allochi, the `Insert` request actually returns the generated ID in the [`WriteResponse`](https://godoc.org/github.com/dancannon/gorethink#WriteResponse). If you run your `Insert` query with [`RunWrite`](https://godoc.org/github.com/dancannon/gorethink#Term.RunWrite) then it will return the `WriteResponse` for you.

**Comment by allochi** [comment]
Hi @dancannon, 

First, thanks for `gorethink`, it's wonderful the good job that is you're doing with it.

I already doing this, but in order to get the generated id I either inject it directly, or reselect the object using `Get()` - incase other things need to be done:

``` go
res, err := db.Table("documents").Insert(document).RunWrite(session)
    if err != nil {
        return err
    }

    id := res.GeneratedKeys[0]
    set, err := db.Table("documents").Get(id).Run(session)
    if err != nil {
        return err
    }

    err = set.One(document)
    return err
```

I'm wondering if this is the `RethinkDB` way and `gorethink` is too based on that, instead of passing a pointer to `Insert` and have insert updating the object with the `ID`:

``` go
db.Table("documents").Insert(&document).RunWrite(session)
```

I also have another question about `EqJoin`, is this the right place to ask about these things? or should I use some other forum?

Thanks again!

**Comment by dancannon** [comment]
Thank you!

Unfortunately automatically injecting the generated ID back into the document would be pretty difficult to do with GoRethink given how RethinkDB returns the results. What I would suggest is doing something like this (I understand this is not ideal but I am not sure there is a better solution):

``` go
res, err := db.Table("documents").Insert(document).RunWrite(session)
if err != nil {
    return err
}

document.ID = res.GeneratedKeys[0]
```

Regarding other questions github issues are find (The #gorethink channel on the RethinkDB slack might be better though)
