### ISSUE TITLE
Using methods like now(), uuid(), deleteAt(), etc.

### ISSUE THREAD

**Issue by Norbell** [rethinkdb/rethinkdb-go#369]
Hello! 

I have some questions about how to use these serverside methods with this driver. I just can't figure it out. :( 

First of all now() and uuid(): 
I like to store the following struct:

``` go
type Node struct {
    UId     string  
    Name        string  
    CreatedAt   time.Time   
    ModifiedAt  time.Time
}
```

So how should my insert query method look like? I like to use r.Uuid() for the Uid field and r.Now for CratedAt and ModifiedAt fields. At the moment I do everything on the client side. It works, but it just does not feel right. :) 

Secondly  I would like to manipulate an Array in one of my documents directly. 
The struct is the following:

``` go
type Cluster struct {
    Id          string  
    Domain      string  
    IP          net.IP  
    Token       []byte  
    Nodes       []Node  
    CreatedAt   time.Time
    ModifiedAt  time.Time
}
```

How can I add/delete Nodes to the []Nodes array just by using ReQL/gorethinkdb? 

Some advice/examples would be very nice! I searched in the doc for some similar problems but wasn't able to get it working. 

Thank you very much! :)

**Comment by dancannon** [comment]
To answer your first question when passing a struct to GoRethink the value of the struct is stored directly in RethinkDB, this means that you are not able to use RethinkDB terms such as `UUID()` or `Now()` in your structs (at least not without completely changing the types which I dont think is the right solution here). I would actually suggest that doing everything client side makes sense for a simple data structure like the one you have posted, you can however pass a raw map to `Insert` which would also work, for example:

``` go
r.Table("table_name").Insert(map[string]interface{}{
    "Uid":          r.UUID(),
    "Name":         name,
    "CreatedAt":    r.Now(),
    "ModifiedAt":   r.Now(),
})
```

Also if you change your table to use `Uid` as the primary key then RethinkDB will generate a UUID for you.

To answer your second question RethinkDB provides a number of functions for manipulating arrays of elements such as:
- [Append](https://godoc.org/github.com/dancannon/gorethink#Term.Append)
- [InsertAt](https://godoc.org/github.com/dancannon/gorethink#Term.InsertAt)
- [SpliceAt](https://godoc.org/github.com/dancannon/gorethink#Term.SpliceAt)
- [DeleteAt](https://godoc.org/github.com/dancannon/gorethink#Term.DeleteAt)
- [ChangeAt](https://godoc.org/github.com/dancannon/gorethink#Term.ChangeAt)

Here is a simple update query which will add a new node to a cluster document:

``` go
r.Table("clusters").Get(id).Update(r.Row.Merge(map[string]interface{}{
    "Nodes": r.Row.Field("Nodes").Append(newNode)
}))
```

**Disclaimer**: I am not currently on a computer with RethinkDB installed so I was not able to test these queries but they should hopefully give you an idea about how it should look. If you are still not sure how to write your query let me know and I can have a closer look.

**Comment by Norbell** [comment]
@dancannon: Thank you very much for your answer. Your provided examples helped me very much. Now this map[string]interface construct makes way more sense to me and working on the server-side with arrays is also very handy.
