### ISSUE TITLE
Time Precision

### ISSUE THREAD

**Issue by pnelson** [rethinkdb/rethinkdb-go#371]
I was writing some tests for an application using the latest gorethink from gopkg.in and I noticed that what goes in is not what comes out with respect to times.

I wrote a program to demonstrate. See last lines comments for example unexpected output.

``` go
package main

import (
    "fmt"
    "log"
    "time"

    "gopkg.in/dancannon/gorethink.v2"
)

const name = "rethink_time_bug"

type foo struct {
    ID   string    `gorethink:"id,omitempty"`
    Time time.Time `gorethink:"time"`
}

func main() {
    s, err := gorethink.Connect(gorethink.ConnectOpts{
        Address:  "127.0.0.1:28015",
        Database: name,
    })
    if err != nil {
        log.Fatal(err)
    }
    gorethink.DBCreate(name).Exec(s)
    defer func() { gorethink.DBDrop(name).Exec(s) }()
    gorethink.TableCreate(name).Exec(s)
    f1 := &foo{Time: time.Now()}
    res, err := gorethink.Table(name).Insert(f1).RunWrite(s)
    if err != nil {
        log.Fatal(err)
    }
    var f2 *foo
    cursor, err := gorethink.Table(name).Get(res.GeneratedKeys[0]).Run(s)
    if err != nil {
        log.Fatal(err)
    }
    defer cursor.Close()
    err = cursor.One(&f2)
    if err != nil {
        log.Fatal(err)
    }
    if !f1.Time.Equal(f2.Time) {
        fmt.Println(f1.Time) // 2016-09-18 16:26:30.598809392 -0700 PDT
        fmt.Println(f2.Time) // 2016-09-18 16:26:30.599 -0700 -07:00
    }
}
```

**Comment by dancannon** [comment]
Hi @pnelson, I think this issue is down to the way RethinkDB stores times, as you can read on this [page](https://www.rethinkdb.com/docs/dates-and-times/javascript/) RethinkDB stores times with millisecond precision so even if you try and store a time with nanosecond precision the driver will truncate it.

**Comment by pnelson** [comment]
Understood, thanks. Looks the same for the location info oddity. RethinkDB only stores the offset so "PDT" won't come back, but that's fine too. Thanks again.
