### ISSUE TITLE
Docs for Recommended Reconnection strategy

### ISSUE THREAD

**Issue by thomasmodeneis** [rethinkdb/rethinkdb-go#374]
Hi,

I've been having this problem for a while, and I could not find any docs related to how you recommend for us to handle reconnection strategy. When the connection is lost the driver is not able to recover, resulting in a failure state, where the app is alive but connection is dead.

The error I'm getting is `gorethink: write tcp 10.0.1.18:63652->10.0.1.121:28015: write: broken pipe`.

Would you mind providing a default docs for handling reconnection strategies ?

Thank you.

**Comment by dancannon** [comment]
Hi @thomasmodeneis,

Sorry for taking so long to respond, the driver is meant to reconnect automatically when it detects a bad connection so if you are seeing issues then there may be a bug with the driver. Funnily enough I have been seeing some issues using a different database driver which uses some of the same underlying packages so the issues might be related.

Unfortunately I don't have any solutions right now but I will try to spend some time investigating the issue soon.

**Comment by dancannon** [comment]
Sorry for the delay, I just wrote a simple script to test reconnections and it appears to be working, could you let me know any more information about what is causing the connections to be dropped and any information you can find about why the connection is not being recreated?

Here is the code I was running and the output I observed

``` go
package main

import (
    "fmt"
    "time"

    r "github.com/dancannon/gorethink"
)

func main() {
    session, _ := r.Connect(r.ConnectOpts{
        Address:  "localhost:28015",
        Database: "test",
    })

    for {
        cur, err := r.Expr([]interface{}{1, 2, 3}).Run(session)
        if err != nil {
            fmt.Println(err)
        }

        var res []interface{}
        cur.All(&res)

        fmt.Println(res)

        time.Sleep(time.Second)
    }
}
```

```
[1 2 3]
[1 2 3]
// I manually interrupted RethinkDB instance
gorethink: dial tcp [::1]:28015: getsockopt: connection refused
[]
gorethink: dial tcp [::1]:28015: getsockopt: connection refused
[]
gorethink: dial tcp [::1]:28015: getsockopt: connection refused
[]
gorethink: dial tcp [::1]:28015: getsockopt: connection refused
[]
// I started the RethinkDB instance again
[1 2 3]
[1 2 3]
[1 2 3]
```

**Comment by thomasmodeneis** [comment]
Hi @dancannon 
I've tested with latest v2.2.2 and confirmed that it now reconnects after db is restarted.
I will deploy this to prod and monitor the behaviour for the next days. 
Thanks !

I was on v2.2.0

```
 {
            "ImportPath": "github.com/dancannon/gorethink",
            "Comment": "v2.2.0",
            "Rev": "e75f34b0817d1ed1a4b967975ccf5fac9535dbc2"
        },
```

And now on v2.2.2

```
{
            "ImportPath": "gopkg.in/dancannon/gorethink.v2/encoding",
            "Comment": "v2.2.2",
            "Rev": "016a1d3b4d15951ab2e39bd3596718ba94d298ba"
        },
        {
            "ImportPath": "gopkg.in/dancannon/gorethink.v2/ql2",
            "Comment": "v2.2.2",
            "Rev": "016a1d3b4d15951ab2e39bd3596718ba94d298ba"
        },
        {
            "ImportPath": "gopkg.in/dancannon/gorethink.v2/types",
            "Comment": "v2.2.2",
            "Rev": "016a1d3b4d15951ab2e39bd3596718ba94d298ba"
        },
```

**Comment by tikiatua** [comment]
Hi everyone,
for us the problem is not reconnecting (which actually seems to work) but connecting on startup. 

Currently, the the connection will only work if the rethinkdb server is already started when the program tries to establish the connection. This will pose problems if one is trying to automatically startup services and the rethinkd-db at the same time (i.e. using different docker-containers).

``` golang
    session, err := r.Connect(r.ConnectOpts{
        Address: url,
    })
    if err != nil {
        log.Fatalln(err)
    }
```

We did write a small utility package that will start a goroutine trying to establish the connection until it succeeds. As soon as the connection has been established once, later requests will automatically try to reconnect to the server.

It would however be great to have this implemented in the gorethink package itself.

**Comment by thomasmodeneis** [comment]
That is odd, could you share a gist with this goroutine of yours so I can try to reproduce it?
Cheers.

**Comment by tikiatua** [comment]
Here is an example gist: https://gist.github.com/tikiatua/f1a639d4e6c84dfc94660cfc3357d20e

Subsequent attempts to connect to a server will result in a panic, if the initial connection did not succeed and the process is not aborted. On the other hand, if an empty session is passed to a run command, the commend will not panic but correctly result in a corresponding error.

My suggestions would be to return an empty session from the r.Connect() method if the session failed to allow for later connection attempts (i.e in a separate goroutine).

**Comment by tikiatua** [comment]
I just added a pull request #381 to "fix" this behaviour.

**Comment by dancannon** [comment]
To be honest I had not considered supporting this use case as I typically handle this behaviour in my applications however I think it makes sense to include your fix. I will include it in the next release, until then I will merge it to the `develop` branch.

**Comment by thomasmodeneis** [comment]
Hi,
So I've just restarted rethinkdb cluster and noticed that app failed to reconnect.
Logs are not conclusive, but reconnection never happens.

When rethinkdb was restarted, queries started to fail with 
`gorethink: EOF`

Then when rethinkdb went back up, queries are now failing with err
`gorethink: write tcp 100.100.11.11:33472->11.111.00.01:28015: write: broken pipe`

Any ideas ?
Cheers.

**Comment by thomasmodeneis** [comment]
@dancannon what was the resolution here ? I missed the point.

**Comment by hinshun** [comment]
@thomasmodeneis I ran into this and I found that gorethink uses a library called `fatih/pool` for connection pools. The connections to your rethinkdb cluster had broken pipes due to the restart, so they have become stale... however due to a bug in `fatih/pool` they weren't closed properly so the pool will keep reusing the stale connections.

Fix is to update to this sha or newer: https://github.com/fatih/pool/commit/44696c5bba56ddaeb1e5750a80e2fbab8925d3e4

**Comment by thomasmodeneis** [comment]
@hinshun oh man, thanks for the heads up, this defect is a pain on my servers.
I will check this out asap, thanks again for the tip.

Cheers.
