### ISSUE TITLE
Cursor.Listen() can cause infinite loop

### ISSUE THREAD

**Issue by bakape** [rethinkdb/rethinkdb-go#375]
After 036953c Cursor.Listen() can now cause infinite loops. I have not isolated the conditions yet, but as  the commit modified Cursor.seekCursor, I believe the regression can be found in this commit. 

CPU profile during the infinite loop: 
![iloop](https://cloud.githubusercontent.com/assets/7851952/18810404/b25a6760-829d-11e6-9598-15313af6c952.png)

**Comment by dancannon** [comment]
Oh dear! Thanks for spotting this, I think your assumption that this was caused by `036953c` is correct and I think it should be quite quick to fix.

**Comment by dancannon** [comment]
`v2.2.2` should now fix this issue however I have still not been able to figure out why the cursors are being closed (this is the main issue). Hopefully I will be able to figure out what is going on at some point soon.

**Comment by bakape** [comment]
Before 036953c there used to be crashes with Cursor.Listen and Cursor.Close racing. I did not figure anything out either either, but maybe it is something to do with mutex unlocks in defer statements?
