### ISSUE TITLE
GetAll() does not work on arrays of len 1

### ISSUE THREAD

**Issue by lpalmes** [rethinkdb/rethinkdb-go#377]
Hey dan,

I'm not really sure if this is the way it's supposed to work. I'm not really an expert in rethink, so sorry if i this is the way intended.

If i have an array of multiple keys it works perfectly, if i pass only one key as a string it it works too.
But when i pass an array of a single key like the one below it does not work. 

```
usersId := []string{"da5a344a-eeca-4167-8b41-338dce3e5b47"}

res, err := rethink.Table(UsersTable).
  GetAll(usersId).Run(Session)
```

Thanks for the drivers, amazing work!

**Comment by dancannon** [comment]
(posting answer discussed in Slack)

Spreading the slice in the arguments to `GetAll` should make this work however that will require switching the type of `userId` to `[]interface{}` as otherwise the code will not compile. For example:

``` go
usersId := []interface{}{"da5a344a-eeca-4167-8b41-338dce3e5b47"}

res, err := rethink.Table(UsersTable).GetAll(usersId...).Run(Session)
```
