### ISSUE TITLE
100% CPU usage in seekCursor 

### ISSUE THREAD

**Issue by gusavila92** [rethinkdb/rethinkdb-go#378]
Hello.

I've been experiencing a problem in my server because sometimes the CPU usage goes to 100% and stays there forever. I did a CPU profiling using pprof and this is what I've found:

![capturar](https://cloud.githubusercontent.com/assets/4813974/19411339/8fc42866-92c5-11e6-9d24-bdc17d840fc7.PNG)

This profiling was made having downloaded the commit "Fixes infinite loop, fixes #375".

**Comment by dancannon** [comment]
Hi @gusavila92, sorry you are also seeing this issue, are you able to reliably reproduce it? So far I have not been able to reproduce it which has made fixing the underlying bug rather difficult so any information would be appreciated!

**Comment by gusavila92** [comment]
Hi @dancannon. Unfortunately, I'm not able to reproduce it reliably, it just happens after the server has been running for a while. Do you want me to put a log when the driver reaches an inconsistent state?

**Comment by dancannon** [comment]
Sorry @gusavila92, I have been really busy the last couple of weeks. If you (or anybody else) could have a look into this issue I would really appreciate it.

**Comment by gusavila92** [comment]
I'll take a look at the source code and try to reproduce the bug. I'll get back to you if I found the problem.

**Comment by gusavila92** [comment]
After having read the code for hours, I've noticed that the Cursor is not thread safe. Sorry but I didn't read the documentation for the Cursor. Maybe this error has something to do with this situation, because I'm listening for changes in a child goroutine, while the parent goroutine can close the cursor when is no longer needed. I can't block the parent goroutine waiting for changes, that's why I need to close the cursor when the parent goroutine needs to be destroyed to avoid a memory leak. Does this make sense to you?

**Comment by dancannon** [comment]
Thanks for reading through the cursor code and trying to get to the bottom of the bug, `Cursor` is intended to be thread safe however the addition of `Skip()` greatly increased the complexity of the code and a couple of bugs have unfortunately slipped through. The use case you mentioned is something that the driver should support so hopefully we can find a solution.

You mentioned you found some places that `Cursor` is not thread safe, would it be possible for you to show me these places?

**Comment by gusavila92** [comment]
For example, while I'm listening for changes in a cursor, the function `fetchMore()` is being executed many times. Every time the function begins, the mutex `c.mu` of the cursor is locked and then is unlocked right before calling the function `c.conn.Query(q)`. The problem here is that if I call `cursor.Close()` while the function `fetchMore()` is calling `c.conn.Query(q)`, the `Close()` function will acquire an exclusive lock over the mutex `c.mu`. When the function `Close()` finish, it will release the lock and then the function `fetchMore()` will acquire the lock again after calling `c.conn.Query(q)`. Then, executing the next iteration of the function `seekCursor()`, the iteration will try to read `len(c.buffer)` and `len(c.responses)`. Because `c.buffer` and `c.responses` are `nil` after having closed the cursor, if you try to read the length of a `nil` slice you will receive 0.

Because you closed the query listening for changes in the `Close()` function, you will end up trying to read inconsistent slices and never progressing over the completion of the function `seekCursor()`.

I also have found that `c.finished` is never changed to `true` in `Close()`, maybe this can resolve the problem.

**Comment by gusavila92** [comment]
I managed to resolve the problem of the 100% CPU usage due to a infinite loop in seekCursor(). The problem was happening because when the cursor was being closed from another thread, sometimes the function seekCursor() wasn't returning a nil value.

I tested this change in our production system, and it has been working properly for 4 days. Before this change, I had to restart the server two times per day.

I created a pull request with this changes, please let me know any questions.

**Comment by thomasmodeneis** [comment]
Really interesting scenario, however as @dancannon mentioned he could not reproduce the error, at least not 13 days ago when he made his last statement.

@gusavila92 would you mind providing updated test cases so we prevent this from happening again ? How would you test this scenario ?

Cheers.

**Comment by gusavila92** [comment]
Hi @thomasmodeneis , thanks for your interest in trying to resolve this bug. I'll try to provide in the following days some new test cases to prevent this bug from happening again. Although, it was very difficult for me to reproduce it in a reliable manner. I just tested it in our production system without any problem so far. I would appreciate any help in these test cases.

**Comment by thomasmodeneis** [comment]
Hi @dancannon what was the reason you closed the ticket ? is this cleared out completely ?
Cheers.

**Comment by dancannon** [comment]
I have merged the fix https://github.com/GoRethink/gorethink/pull/384 which should hopefully fix the issue. If anybody still has any issues feel free to post here.
