### ISSUE TITLE
Use extern function to query

### ISSUE THREAD

**Issue by Fantasim** [rethinkdb/rethinkdb-go#382]
Hi,

I've this query : 

```
curs, _ = r.Table("places").
               Filter(func(customer r.Term) interface{}{
                 return customer.Field("**Name**").
                       Downcase().
                       Match("^" + removeAccent(strings.ToLower(value)))}).Run(sess)
```

and i've this function : 

```
func removeAccent(str string) string {
    t := transform.Chain(norm.NFD, transform.RemoveFunc(isMn), norm.NFC)
    result, _, _ := transform.String(t, str)
    return result
}
```

How can i apply this function on each place's **Name** got by querie to remove all accent for  `Match("^" + removeAccent(strings.ToLower(value)))` work with all name start by value even those with accents ?

Thanks

**Comment by dancannon** [comment]
Sorry for taking so long to respond, unfortunately I don't believe it is possible to do what you are trying to do with GoRethink due to the way that ReQL works. Although you are executing Go functions these functions are actually compiled down to a JSON query object which is executed by RethinkDB.

**Comment by Fantasim** [comment]
Thanks for your answer
