### ISSUE TITLE
Add an example to insert data from JSON string?

### ISSUE THREAD

**Issue by kirillDanshin** [rethinkdb/rethinkdb-go#383]

**Comment by thomasmodeneis** [comment]
Hi @kirillDanshin 

Sorry, this ticket is a bit vague, what is it that you are trying to do again ?
This looks like more of a Golang question rather than GoRethink question.

Correct me if I'm wrong, but you want to marshal a json string into a struct and insert this into rethinkdb ? 
Cheers.

**Comment by kirillDanshin** [comment]
hi @thomasmodeneis 
I want to skip JSON unmarshaling

**Comment by thomasmodeneis** [comment]
Hi @kirillDanshin 
How do you mean skip JSON un marshalling ?
In order for you to get the object and be able to use it with the golang you will be required to transform it into a object, something like this:

```
var rows []interface{}
err := res.All(&rows)
if err != nil {
    // error
}
```

How otherwise are you planning to do this ?
Cheers.

**Comment by kirillDanshin** [comment]
hi @thomasmodeneis 
I mean that I have a JSON string that I read from HTTP POST request. I want to store that JSON as a rethinkdb document without unmarshaling it to a struct/map/anything else.

**Comment by thomasmodeneis** [comment]
In that case, you need to use another programming language.
Maybe https://github.com/neumino/rethinkdbdash is better for your needs.

**Comment by kirillDanshin** [comment]
hmm.
I believe I just need to find the way to do it and publish it on github.

**Comment by thomasmodeneis** [comment]
Well, I guess you could do something like this ?

```
m := map[string]string{}
err := json.Unmarshal([]byte(yourjsongoeshere), &m)
res, err := r.DB("database").Table("table").Insert(m).RunWrite(sess)
```

**Comment by dancannon** [comment]
Something like this might also work...

```go
r.Table("table_name").Insert(r.JSON("yourjsonobjects"))
```

**Comment by thomasmodeneis** [comment]
Thats really handy, what are the performance implications of using such not typed hack ?
