### ISSUE TITLE
how to filter array of values

### ISSUE THREAD

**Issue by selvam347** [rethinkdb/rethinkdb-go#387]
I have a table called cities which has country id as reference key. How can i filter cities with array of country_id like the following.
SELECT * FROM cities WHERE country_id IN (1, 2, 3, 4) [same case](http://stackoverflow.com/questions/25817761/filter-by-list-of-ids-in-rethinkdb)

**Comment by dancannon** [comment]
Hi @selvam347, something like this might work:

```go
r.Table("cities").GetAllByIndex("country_id", r.Args([]interface{1,2,3,4}))
```

Here is some more documentation for this function: https://godoc.org/github.com/dancannon/gorethink#Term.GetAllByIndex

**Comment by selvam347** [comment]
thanks. it's working
