### ISSUE TITLE
goroutine leak when connecting/disconnecting?

### ISSUE THREAD

**Issue by ssoudan** [rethinkdb/rethinkdb-go#388]
Hi, 

I face a goroutine leak when connecting/disconnecting from rethinkdb:

gorethink.Connect()  > Session#Reconnect() > NewCluster() > hostpool.NewEpsilonGreedy() which creates a goroutine with epsilonGreedyDecay().

Because Cluster#Close() doesn't call hp.Close() this goroutine is never stopped.

Looks like a: 	
if c.hp != nil {
	c.hp.Close()
}
in Cluster#Close() does the job. 

Did I miss something?

Thanks,
Sebastien

**Comment by dancannon** [comment]
Hi, thanks for reporting this bug, I have pushed a fix to `develop` and should release it to `master` shortly.
