### ISSUE TITLE
Update nested array

### ISSUE THREAD

**Issue by tudorels** [rethinkdb/rethinkdb-go#391]
Hello, I am new to gorethink, rethinkdb and golang. I try to update an element in array(comments) like this:
`"id": "e63ca11d-181e-43f5-b22a-2440aa446653",
"comments": [
    {
        "from": "John Doe",
	"subject": "My name is even more boring than Bob's"
        "recid": "29fb8e77-4e97-48a5-83d7-2bfbdfc29dc2"
    } ,
    {
        "from": "Captain America",
	"subject": "My name is Captain America"
        "recid": "4ebfe414-55f1-42d6-a911-17ee2d513007"
    } 
] `
I was able to update with javascript in this way with map and branch, but I can't translate the code in gorethink, because I do not yet understand well how it works map and branch together. Bellow is the working example in javascript:
`r.db('mydb').table('posts').get('e63ca11d-181e-43f5-b22a-2440aa446653')
  .update({
    comments: r.row("comments").map((comment) => {
        return r.branch(
            view("recid").eq('4ebfe414-55f1-42d6-a911-17ee2d513007'),
            comment_mod,
            comment
        );
      })
  })
`
where _comment_mod_ is the comment I want to modify. It would be helpful if you could add this example in gorethink documentation.
Thank you!

**Comment by thewraven** [comment]
I have a working example for you, please check it out [here](https://gist.github.com/thewraven/349e5ad6426090a15ad220d9a2a2b730) . If the gorethink users think there's a need for examples, I can cheerfuly help with some of them.

**Comment by tudorels** [comment]
Thank you very much!
It would be helpful.
