### ISSUE TITLE
This project is no longer maintained

### ISSUE THREAD

**Issue by dancannon** [rethinkdb/rethinkdb-go#392]
Unfortunately I have decided to stop maintaining GoRethink, this is due to the following reasons:

 - Over the last few years while I have spent a lot of time maintaining this driver I have not used it very much for my own personal projects.
 - My job has been keeping me very busy lately and I don't have as much time to work on this project as I used to.
 - The company behind RethinkDB has shut down and while I am sure the community will keep the database going it seems like a good time for me to step away from the project.
 - The driver itself is in a relatively good condition and many companies are using the existing version in production.

I hope you understand my decision to step back from the project, if you have any questions or would be interested in take over some of the maintenance of the project please let me know. To make this process easier I have also decided to move the repository to the GoRethink organisation. All existing imports _should_ still work.

Thanks to everybody who got involved with this project over the last ~4 years and helped out, I have truly enjoyed the time I have spent building this library and I hope both RethinkDB and this driver manage to keep going.

**Comment by tudorels** [comment]
Sad to hear that!

**Comment by gusavila92** [comment]
It's very sad to hear that because I've been using this library in our production system without any problems so far.
It would be very cool if I can collaborate maintaining this project, since we have no plans to migrate our entire system to another language. How can I join the group of maintainers for this project?

**Comment by omeid** [comment]
Thanks a lot for the trendimous amount of work you have done to make this project posssible @dancannon and it is really sad that you can no longer maintaine this project, however, it is totally understandable. :)

As I use this driver in production, I am also interested to help with maintaince.

To make it easier to keep the project going forward as a community, I think it would be important to have a Contribution Guidlines, Review Process, and a working CI.

**Comment by kirillDanshin** [comment]
@dancannon hi.
I want to maintain it because I actively use it in almost all my projects.

**Comment by kirillDanshin** [comment]
Is it possible?

**Comment by mklimuk** [comment]
Thanks for all your hard work @dancannon! I'll be glad to help the community as well.

**Comment by ianberinger** [comment]
Sad to hear that, but thanks for your work @dancannon! I'm using this driver for multiple projects in production and would be happy to help maintain it.

**Comment by DeepAnchor** [comment]
Just wanted to add to the chorus... Thanks @dancannon for all the hard work and effort that went into creating and maintaining this driver over the years. This is truly a quality project.

**Comment by dancannon** [comment]
Thanks everybody for all the support, as I said I have really enjoyed working on this project and I hope we can figure out something that works for everybody.

As many people are using this driver in production I want to make sure the transition is as seamless as possible, as such I propose for the time being I will deal with the management of the project (merging PRs and organising any releases) and leave the coding and question answering to anybody who would like to help out. If people are comfortable to get involved with some of the driver internals and would like some more information about how the driver works I would also be happy to do some sessions with whoever is interested and go through the driver and answer any questions.

Just to summarise my number one priority is keeping the quality of the driver as high as possible with as few API breaking changes as possible. If people want to add features to the driver then we can also look into working on those changes if everybody agrees that the change makes sense and doesn't add to much complexity. I hope this all makes sense and thanks again for all the support!

**Comment by kirillDanshin** [comment]
```
If people are comfortable to get involved with some of the driver internals and would like some more information about how the driver works I would also be happy to do some sessions with whoever is interested and go through the driver and answer any questions.
```
@dancannon I'm in.

**Comment by maj-o** [comment]
After many years of software development (over 35) I searched for something new this year. I came across microservices (sorry, have been busy last years) - my first thought has been: this does not work - not for me - not on a single machine - well, in the end it has been a break through in the dependency-chaos-superhero-fight - it just worked.
Then I have been searching for a convinient datastore - I have checked almost anything - maybe rethink is here and there a bit slow - but - but it does its job like expected >> perfect

@dancannon 
Then I checked Your package >> sexy
Thank You !!!

**Comment by thomasmodeneis** [comment]
Hi,

I'm sorry to hear that, I hope we can still get things going around here, this is a great piece of software and will be a big waste to let it go.

I would like to help get things going as I'm using this driver in the core of many of my apps.

I would suggest you change the title of this ticket to something more meaningful like: Contributors wanted, main developer will step down or something like this. From what I could read here, there are some guys available to roll the ball.

**Comment by dancannon** [comment]
As part of bringing new maintainers onto this project I would really appreciate it if anybody that is interested could start reviewing any PRs or fixing any bugs that come up as I think that would be a good way to get involved. As before if anybody has any questions let me know.

**Comment by thomasmodeneis** [comment]
@dancannon I will start working on this no later than this week.
Cheers.

**Comment by xeger** [comment]
@thomasmodeneis and @dancannon - just wanted to confirm that you had an orderly transition of power and that we have a maintainer now? My time is limited, but I am actively using gorethink on a couple projects and would love to help enhance the documentation, triage bugs, or otherwise help ease the maintenance burden.

For instance: we should probably close this issue and update the README if we have a maintainer!

**Comment by CMogilko** [comment]
Can anyone explain the situation? The above conversation told me that some people want to maintain repo, but I still don't see any new maintainers.

**Comment by joseluisq** [comment]
Is there any progress on this?

**Comment by sankethpb** [comment]
hello @dancannon, hello everyone, 
Could you please clarify if this project is still maintained? 
Thank you.

**Comment by dancannon** [comment]
@CMogilko I noticed that you have been contributing a bit lately, would you be interested in becoming an "official" contributor?

**Comment by CMogilko** [comment]
@dancannon I can do this. I need this driver in my work.

**Comment by dancannon** [comment]
Thanks so much! I have added you as a contributor.
