### ISSUE TITLE
How to properly run a nested filter?

### ISSUE THREAD

**Issue by munjalpatel** [rethinkdb/rethinkdb-go#394]
I am trying to run a filter on a property of a nested object for RethinkDB in Golang. But I am sure that I am missing something here. Could you please help me out?

This is the error I am getting:

> (func literal).Eq undefined (type func(gorethink.Term) gorethink.Term has no field or method Eq)

Here is my code:

    type User struct {
    	Id        string `json:"id,omitempty"`
    	FirstName string `json:"firstName,omitempty"`
    	LastName  string `json:"lastName,omitempty"`
    	Email     string `json:"email,omitempty"`
    	Password  string `json:"password,omitempty"`
    	Salt      string `json:"salt,omitempty"`
    }
    
    type UnverifiedUserRequest struct {
    	Id    string `json:"id,omitempty"`
    	Token string `json:"token,omitempty"`
    	User  User   `json:"user,omitempty"`
    }

    db.Table("unverified_requests").Filter(func(row r.Term) r.Term {
	return row.Field("user").Map(func(user r.Term) r.Term {
            return user.Field("email")
        }.Eq(email))
    }).Run(session)

**Comment by thomasmodeneis** [comment]
You are missing the closing ) for the .Map function.
Something like this should at least compile, but it will fail with: Cannot convert STRING to SEQUENCE.
```
r.Table("unverified_requests").Filter(func(row r.Term) r.Term {
			return row.Field("user").Map(func(user r.Term) r.Term {
				return user.Field("email")
			}).Eq("test")
		}).Run(session)
```

I've never seen such composition, map can only be applied to sequences, not single values.

This query will be better written if you create a index for the field email and then use it with GetAllByIndex:

```
r.Table("unverified_requests").GetAllByIndex("email", "john@mail.com").Run(session)
```

Cheers.

**Comment by thewraven** [comment]
I think that the best approach to your query would be using **filter** with a function argument . The documentation of the javascript can be very helpful, you can check it out [here](https://www.rethinkdb.com/api/javascript/filter/) .

I've created a [gist](https://gist.github.com/thewraven/3969e4e624c60bc5809d5ae8d236f012) for your specific question, I hope it works for you
