### ISSUE TITLE
Interface wrapper

### ISSUE THREAD

**Issue by mklimuk** [rethinkdb/rethinkdb-go#395]
It would be really great if we could have an (optional?) interface wrapper over the library as it would make unit testing less of a pain. The API could probably stay intact, we could just define interfaces over some of it's elements (like Session or Term).

**Comment by CMogilko** [comment]
What kind of interfaces do you need? Session already has interface - `QueryExecutor`.
If you need to unittest some query you just pass to `Mock` instead of `QueryExecutor`.
