### ISSUE TITLE
Dependencies link is not correct

### ISSUE THREAD

**Issue by unloop** [rethinkdb/rethinkdb-go#396]
hi,
btw, one of the dependencies link is not correct. repo's link should be github.com/cenkalti/backoff

https://github.com/GoRethink/gorethink/blob/v2.2.2/cluster.go#L11

**Comment by dancannon** [comment]
I believe the user updated their username however the import should still work for the time being. It should be an easy change to updated the import though.

**Comment by dancannon** [comment]
Closed by #397
