### ISSUE TITLE
Filter by field's content contains string

### ISSUE THREAD

**Issue by Fantasim** [rethinkdb/rethinkdb-go#399]
I've some object : 

    {
        "name":  "universite paris sorbonne" ,
        "id":  "548272c9-6615-4e93-aa15-9af0a830c9a2"
    }
    {
        "name":  "universite paris dauphine" ,
        "id":  "943234f3-6615-4e93-aa15-9af0a830c9a2"
    }
    {
        "name":  "universite sorbonne nouvelle" ,
        "id":  "24f477f3-6615-4e93-aa15-9af0a830c9a2"
    }

How can i do if i would like select each object which contain 

> paris dau

 in their name ?

I've tried with that, but it doesn't work.

        curs, _ = r.Table("places").
        Filter(func(customer r.Term) interface{}{
            return customer.Field('name').Downcase().Contains(func (custo r.Term) interface{}{
                return custo.Match(".\\*" + "paris dau" + ".\\*")
            })

any suggest ?

**Comment by Mobilpadde** [comment]
Any success? I'm trying to overcome the same hurdle.

**Comment by graywolf336** [comment]
To anyone wonder in the future:

```go
term = term.Filter(func(record r.Term) interface{} {
    return record.Field("fieldName").Downcase().Match(strings.ToLower("searchTerm"))
})
```
