### ISSUE TITLE
RethinkDB Joins the Linux Foundation!

### ISSUE THREAD

**Issue by thomasmodeneis** [rethinkdb/rethinkdb-go#404]
https://rethinkdb.com/blog/rethinkdb-joins-linux-foundation/

Great news. I have many projects invested in RethinkDB outside of this driver. For many months I was afraid that was all lost. Now, all uncertainty has been removed and we can all start moving forward.
With RethinkDBs move to the Linux Foundation on an ASLv2 license, the sky is clear!

Cheers.

**Comment by eliezedeck** [comment]
What about the future of this driver? @dancannon are you still onboard?

**Comment by leetal** [comment]
He commented with the release of 3.0.0 that he would step back from the role as sole developer of this driver and wanted more help from the community. So i think not... But with that said, nothing is stopping us from contributing to this driver, as long as someone (Dan i think) still holds the wheel and steers the development in the right direction.

**Comment by dancannon** [comment]
@leetal is pretty much correct, I have decided to step down from writing code for gorethink but I will be managing releases and PRs for the time being. As I have mentioned before if anybody would like any help getting involved just let me know and I will try and do my best to help.
