### ISSUE TITLE
concurrently inserting single values is slow

### ISSUE THREAD

**Issue by ekle** [rethinkdb/rethinkdb-go#408]
100 goroutines concurrently inserting single values in a local rethinkdb is very slow on my system.
just around 100 writes/sec.

i found the locking in Session.IsConnected() is the limiting factor in my test.

after i changing it to a RLock i get over 4000 writes/sec.
i think just an RLock should be ok in this function, as there are now writes.

This is the change i made:
https://github.com/alfatraining/gorethink/commit/124ec4b466057e00bc2878091371286af420b387

**Comment by dancannon** [comment]
Thanks for reporting this @ekle, could you please submit a PR?

**Comment by ekle** [comment]
here: #409

**Comment by dancannon** [comment]
Closed by #409
