### ISSUE TITLE
Why Contains in .Filter(func()) is not working and parts of query get ignored?

### ISSUE THREAD

**Issue by goors** [rethinkdb/rethinkdb-go#413]
I am trying to do this:

    r.table(table).filter(
      function (doc) {
        return r.expr(array)
                .contains(doc("name"));
      }
    )

written in golang that is

    rethink.Table(table).GetAllByIndex(index, value).Filter(func(row rethink.Term) interface {}{
    
        return rethink.Expr([]string{}).Contains(row.Field("type"))
    })

I am not sure but it is like rethink.Expr is ignored.
That is first problem.

Second problem is next. If I have query written like this:

    query := rethink.Table(table).GetAllByIndex(index, value)

and then try to do next:

    if some_condition {
       q.Filter(some_filter)
    }
    
    if some_other_condition {
       q.Filter(some_other_filter)
    }

when i print out `q.String()` i got only that first part and everything else is ignored `rethink.Table(table).GetAllByIndex(index, value)`

**Comment by thewraven** [comment]
@goors wasn't this issue resolved by the answer on [stackoverflow?](http://stackoverflow.com/questions/43995683/why-contains-in-filterfunc-is-not-working-in-gorethink-and-parts-of-query-g/44000473#44000473)

**Comment by goors** [comment]
@thewraven yes, closing ....
