### ISSUE TITLE
When rethinkdb sends response as empty array, cursor.IsNil() returns false

### ISSUE THREAD

**Issue by skatiyar** [rethinkdb/rethinkdb-go#415]
For following query
```
r.db('test')
  .table('tokens')
  .getAll('askhjakjhasjkd', {index: 'token'})
  .orderBy('token')
```
If token `askhjakjhasjkd` doesn't exist, rethinkdb sends back empty array. Should `cursor.IsNil()` return `true` or `false` in this case? Ideally I would expect it to be `false`, since no value was found.

**Comment by skatiyar** [comment]
This can be quickly solved by adding
```
if string(response) == "[]" {
     return true
}
```
In [cursor.go:L527](https://github.com/GoRethink/gorethink/blob/master/cursor.go#L527)

But should this be part of cursor behaviour or should be handled at app level?

**Comment by thewraven** [comment]
From the [rethinkdb documentation](https://www.rethinkdb.com/api/javascript/get_all/):
```
While get will either return the document or null when no document with such a primary key value exists, this will return either a one or zero length stream.
```
So I think that the driver is just behaving correctly, according to the rethinkdb spec.

**Comment by skatiyar** [comment]
@thewraven problems come when I try to assert value using `IsNil`, which `returns False`, but calling `cursor.One()` after that, returns an error saying `no rows to scan`. Which seems very counter intuitive.

**Comment by CMogilko** [comment]
`One` reads next value from cursor. `IsNil` tests if the current row is nil. So it isn't correct to test if there is any new values in the cursor with `IsNil`.

**Comment by CMogilko** [comment]
If there are no questions I close the issue.
