### ISSUE TITLE
How to use GetNearest?

### ISSUE THREAD

**Issue by utiq** [rethinkdb/rethinkdb-go#418]
How can I translate this query to gorethink?
```
var secretBase = r.point(-122.422876,37.777128);
r.db('arrively').table('users').getNearest(secretBase,
    {index: 'location', maxResults: 25}
)
```

**Comment by Coccodrillo** [comment]
```
type User struct {
	Loc  types.Point `gorethink:"location"`
	Name string      `gorethink:"name"`
	ID   string      `gorethink:"id"`
}

func main() {

	var rows []*User

	secretBase := types.Point{Lat: -122.422876, Lon: 37.777128}

	res, err := r.
		DB("arrively").
		Table("users").
		GetNearest(
			secretBase,
			r.GetNearestOpts{Index: "location", MaxDist: 1000, MaxResults: 25, Unit: "m"},
		).
		Run(session)
	if err != nil {
		log.Error(err)
	} else if err = res.All(&rows); err != nil {
		log.Error(err)
	}
}
```

Something like this should get you started (I adapted it from my code without running it, so some minor tweaks might be needed). I also added MaxDist and Unit, just so you see where to add those if needed.

**Comment by utiq** [comment]
Thanks @Coccodrillo!, it works like a charm. The only problem is that I cannot chain filters or merges. This is my code:

```
response, err := r.Table("users").GetNearest(
			originPoint,
			r.GetNearestOpts{Index: "location", MaxDist: 10000, MaxResults: 25, Unit: "m"},
  ).Filter(map[string]string{
		"status": "online",
	}).Merge(func(p r.Term) interface{} {
    return map[string]interface{}{
      "vehicle_id": r.Table("vehicles").Get(p.Field("vehicle_id")),
    }
  }).Run(session)
```
Do you know what's going on?

**Comment by Coccodrillo** [comment]
@utiq Check what kind of output you get after GetNearest, it's changed slightly to accommodate geolocation query and you need to extract the document before doing operations. Something like this should do the trick:
```
response, err := r.Table("users").GetNearest(
			originPoint,
			r.GetNearestOpts{Index: "location", MaxDist: 10000, MaxResults: 25, Unit: "m"},
  ).Do(func(doc r.Term) r.Term {
			return doc.Field("doc")
}).Filter(map[string]string{
		"status": "online",
	}).Merge(func(p r.Term) interface{} {
    return map[string]interface{}{
      "vehicle_id": r.Table("vehicles").Get(p.Field("vehicle_id")),
    }
  }).Run(session)
```

Please note I am writing this from memory, you might need to tweak this a bit.

**Comment by CMogilko** [comment]
Are there any other questions?

**Comment by mehmetkose** [comment]
Me! How should I insert records with the Point field?

I tried with struct;
![screen shot 2017-09-05 at 20 18 36](https://user-images.githubusercontent.com/706678/30073705-71e78e34-9277-11e7-9c2b-9c539156d2d1.png)

And like this. But anyway my results are blank.
![screen shot 2017-09-05 at 20 19 17](https://user-images.githubusercontent.com/706678/30073713-8a67e256-9277-11e7-9faf-93df25d03314.png)

![screen shot 2017-09-05 at 20 20 30](https://user-images.githubusercontent.com/706678/30073750-b4d9ec82-9277-11e7-9b20-15c7f98cf410.png)

my index lines like this;
![screen shot 2017-09-05 at 20 21 46](https://user-images.githubusercontent.com/706678/30073801-dfe0138e-9277-11e7-9682-f95084db4d47.png)

and query;
![screen shot 2017-09-05 at 20 23 32](https://user-images.githubusercontent.com/706678/30073884-21babdcc-9278-11e7-9a15-addf30c207a4.png)

and where I can find the tests related with this topic? I saw on v2 but I can't find in v3

**Comment by CMogilko** [comment]
@mehmetkose https://github.com/GoRethink/gorethink/blob/master/internal/reql_tests/reql_geo_indexing_test.go#L295
I'm not very familiar with geo, but quick read it seems to me that code is ok. Are you sure in your data?
