### ISSUE TITLE
Cancelling queries

### ISSUE THREAD

**Issue by CMogilko** [rethinkdb/rethinkdb-go#420]
Is there way to cancel a running query? Are there any plans to use Contexts?

**Comment by CMogilko** [comment]
What about this approach?
I can alter all Term's `Run` methods (`Run`, `RunWrite`, `ReadOne`, `ReadAll`) with passing `context.Context` through arguments. To keep compatibility old methods remains with
`context.WithTimeout(context.Background(), config.ReadTimeout)`. Or context can be passed through `RunOpts`.
Next https://github.com/GoRethink/gorethink/blob/master/connection.go#L144 it's needed to run `readResponse` in a new separate goroutine and return result through channel. And `select` from this channel and `ctx.Done()`.

**Comment by thewraven** [comment]
It can be a nice improvement!

I'm thinking about two ways of implementing it:

1 - Would be cool to have methods in `Term` with methods like:

- `RunWithContext()`
- `RunWriteWithContext()`
- `ReadOneWithContext()`
- `ReadAllWithContext()`

2 - Add a `context.Context` field to [RunOpts](https://godoc.org/gopkg.in/gorethink/gorethink.v3#RunOpts) and friends.

We only have to document that the cancellation approach will complement the 'default timeout' defined on the [ConnectOpts](https://godoc.org/gopkg.in/gorethink/gorethink.v3#ConnectOpts)

**Comment by CMogilko** [comment]
I can do it, but I think that maintainer needs to say which way is preferable.

**Comment by dancannon** [comment]
I am not really "the maintainer" anymore however I think the second method @thewraven makes a bit more sense as it pollutes the API a bit less but is still backwards compatible.
