### ISSUE TITLE
connection fails and driver is not able to recover

### ISSUE THREAD

**Issue by thomasmodeneis** [rethinkdb/rethinkdb-go#421]
Hi,

Yesterday I have updated gorethink to latest: `v3.0.2` `7ab832f7b65573104a555d84a27992ae9ea1f659` But the issue remains.
`gorethink: write tcp 100.100.51.165:42424->85.183.63.117:28015: write: broken pipe`

This makes the app to behave unhealthy and I was wanting to avoid building up defensive code to thread this error, as I believe this should be properly handled inside the driver.

Anyone else experiencing similar issues ?

Issue previously reported on #374.

Cheers.

**Comment by CMogilko** [comment]
I didn't investigate this a lot, may be this is close situation.
If my app is blocked on a `Cursor.Next()` from `Changes()` query and connection got lost, cursor doesn't return any errors. So It seems that my app get stuck forever.

**Comment by CMogilko** [comment]
It seems that gorethink uses fatih/pool fixed version.
@thomasmodeneis Does this bug reproduce?

**Comment by CMogilko** [comment]
connection logic was changed a lot. should not be reproducing.
