### ISSUE TITLE
Get only one proper solution?

### ISSUE THREAD

**Issue by mehmetkose** [rethinkdb/rethinkdb-go#424]
Hi, I'm trying to get only one record from db like this;
![ekran resmi 2017-08-30 14 32 58](https://user-images.githubusercontent.com/706678/29870489-5c71f13e-8d90-11e7-9d98-88fdb715aea9.png)

I'm refreshing the page and this function **sometimes** returning the record but sometimes **not**,
Where I'm doing wrong?

gorethink v3
I'm using slugs as Id

**Comment by CMogilko** [comment]
Do you get error or empty result? Are you sure that it is gorethink-specific and not rethinkdb?
You can use `ReadOne()` instead of `Run()` and `One()` (however it's close inside)

**Comment by mehmetkose** [comment]
it's working like this. I don't know really why, I'm newbie at Golang.
![ekran resmi 2017-08-30 19 35 47](https://user-images.githubusercontent.com/706678/29883944-8125c9d6-8dba-11e7-997e-0c58b4d50969.png)
