### ISSUE TITLE
Geo Example

### ISSUE THREAD

**Issue by mehmetkose** [rethinkdb/rethinkdb-go#426]
Can somebody add working example about geo queries? I mean, inserting, listing etc
Thanks.

**Comment by Coccodrillo** [comment]
@mehmetkose [This](https://github.com/Coccodrillo/rethink_geo_examples) is a short demo I put together for my former coworkers that might point you in the right direction. Also, there used to be a test file which demonstrated this quite well, but it fell out in v2.2.0, you can find it [here](https://github.com/GoRethink/gorethink/blob/v2.1.2/query_geospatial_test.go).

**Comment by mehmetkose** [comment]
Wow that is exactly what I'm looking for. Thank you.

**Comment by mehmetkose** [comment]
well thanks again. I'm closing this issue.
