### ISSUE TITLE
Error in module "query_control"

### ISSUE THREAD

**Issue by Gitart** [rethinkdb/rethinkdb-go#428]
Hi.

In module "query_control.go" in row # 186 error.
You have code :

`
           ResultFormat interface{} `gorethink:"resul_format,omitempty"`
`
Correct code : (need litera  **t**  in word **resul_format**
`
           ResultFormat interface{} `gorethink:"result_format,omitempty"`
`

Fix Please.

**Comment by CMogilko** [comment]
fixed in 3.0.5
