### ISSUE TITLE
Thoughts about v4

### ISSUE THREAD

**Issue by CMogilko** [rethinkdb/rethinkdb-go#430]
Hi, 
Currently I maintain gorethink and I think about some major improvements and refactoring.
I'm not the original author of gorethink and I don't know the history of some decisions made in past. So I decided to ask community about changes.

For a some reason some internal structs and interfaces are public. They are not used by integration tests. So I'm going to make it private unless someone uses it.

Integration tests with real rethinkdb doesn't substitute unit tests, I think gorethink needs more unit tests coverage.

Also I think that integration with [opentracing-go](https://github.com/opentracing/opentracing-go) can be useful for understanding performance of your code. With tracing you can easily see (for example, in Jaeger or Zipkin) the amount of time your API handlers spend on waiting for rethinkdb responses.
But there is a problem. The most evident way to do this -- wrap `QueryExecutor` in a separate package, but it is not enough. `Span` must be started when `Query()` is called and must be finished when `Cursor` is closed. But `Cursor` can't be wrapped because it is a `struct`, not an `interface`.
So the most evident way breaks compatibility. It can be acceptable with growing major version. But it can be achieved without it: I can integrate usage of opentracing-go into gorethink itself. Or add not-go-way method to `Cursor` -- `SetClosedCallback()` to close `Span` (however stdlib uses it [sometimes](https://golang.org/pkg/net/http/#Server.RegisterOnShutdown)).

I created a mini [questionnaire](https://goo.gl/forms/EOj2DlOQv1V91HDf2).

What do you think about it? Any other suggestions? Please share your opinion.

**Comment by kofalt** [comment]
Hello! :slightly_smiling_face: 

Do you have some examples of which structs you intend to hide? Counter-intuitively, it can be better to leave structs public (I believe Kubernetes and some similar projects do this). Exposing the internals a bit can be good if you wish to modify or interact with the behavior in some way, rather than necessitating a fork. I don't have very strong opinions on it though.

Personally, I like the idea of tracing but it would be nice to opt-in to importing it via a different package. This would make it such that gorethink users who don't need / want tracing wouldn't have to have that import.

Thanks for all you do!

**Comment by CMogilko** [comment]
@kofalt I intend to hide `Connection`, `Cluster`, `Node`, `Pool`, `Session`. Every `struct` except Opts and `Term` If we keep them public, we can't modify gorethink implementation normally.
User must use `Connect()`, `QueryExecutor`, `Term`, `Cursor` and opts. And nothing else. I don't see any good reason to use `Node` manually, for example. Any configurations or interactions with behavior need to be moved to `QueryExecutor`'s methods or various Opts. Perfectly, `Cursor` must be an interface too.

About opt-in tracing, there are 2 options: change `Cursor` to an interface or add special method. I like first, but if community is against changing the interface...

**Comment by dancannon** [comment]
I just wanted to start off by thanking @CMogilko for the work he has been doing on the library recently, it is great to see somebody driving the project forwards!

To answer your first question my gut feeling is that making some currently exposed structs internal does not really add much but could break existing code bases. That being said if you need to change the API of these "internal structs" then making them internal could make sense for the future.

Regarding the testing, they were always something I wanted to spend more time on however I never had the time to properly look into them so ended up writing the generated integration tests instead as I felt this would help more in the long run. I was also not really a fan of the testing library used however this was something I ported over from the old Go RethinkDB library. If I were to start again I would probably have more of a focus on writing more go-like unit tests.

Tracing could also be a great addition to the library, I think changing the interface could be a good option if the upgrade path is simple/doesn't affect too many users. However I am not sure about a span being "closed" when the cursor is closed, that does not feel correct to me. I imagined each query/request being a different span, this could make the implementation quite a bit simpler.

I hope my notes help, I think everything you have written already makes sense however my last comment would be that avoiding API changes wherever possible makes everybody's lives easier in my opinion. I also wanted to mention again how much I appreciate all the work you are doing.

**Comment by CMogilko** [comment]
Some features are implemented in v4, I avoided breaking compatibility this time, but at least increasing unit test coverage can require make interfaces from structs in future. v4 is a draft release, so I will publish stable v4.0.1 after some testing.
