### ISSUE TITLE
Sync() should return Synced?

### ISSUE THREAD

**Issue by savely-krasovsky** [rethinkdb/rethinkdb-go#432]
From [docs](https://www.rethinkdb.com/api/javascript/sync/):
`If successful, the operation returns an object: {synced: 1}.`
So I do request:
`res, err := r.Table("users").Sync().RunWrite(session)`
but in res object there is no `Synced` field. Is it okay?

**Comment by CMogilko** [comment]
I suppose that you shouldn't use `RunWrite`, try `ReadOne`. `RunWrite` is used only for queries that actually writes something.

**Comment by savely-krasovsky** [comment]
@CMogilko I tried this code:
```golang
var res r.Response
err := r.Table("users").Sync().ReadOne(&res, session)
```
Not working :(
![image](https://user-images.githubusercontent.com/5345489/34275970-847ade56-e6b0-11e7-8753-5add72226867.png)

**Comment by CMogilko** [comment]
@L11R `r.Response` is internal type you shouldn't use it in any cases. (This is the reason I think that such types should be private). 
Try to use:
```go
var res struct {
  Synced int `gorethink:"synced"`
}
r.Table("users").Sync().ReadOne(&res, session)
```
Or you can just make `var res map[string]interface{}` or just `var res interface{}`

**Comment by savely-krasovsky** [comment]
@CMogilko ohhh. Apparently I said stupidly. Need more sleep. Always made a separate type before...
Thanks for help. Problem resolved.
