### ISSUE TITLE
c.hp.Close  undefined

### ISSUE THREAD

**Issue by nicolasStevenin** [rethinkdb/rethinkdb-go#436]
Hi,

When i try to test your project in the release 3.0.5, it fails with 
./cluster.go:162:6: c.hp.Close undefined (type hostpool.HostPool has no field or method Close)

The project "github.com/hailocab/go-hostpool" didn't change since 2 years...
Thank you for your help

**Comment by CMogilko** [comment]
hi,
may it be that your local version of hostpool is older?
https://github.com/hailocab/go-hostpool/blob/master/hostpool.go#L55
it has `Close` method and my local version builds with hostpool master.

**Comment by nicolasStevenin** [comment]
Ok thanks ! I didn't choose this package because unit test fails but it seems i have no choice...
