### ISSUE TITLE
gorethink: dial tcp: lookup http on 127.0.0.11:53: server misbehaving

### ISSUE THREAD

**Issue by zwhitchcox** [rethinkdb/rethinkdb-go#439]
So, I'm trying to run GoRethink with docker, but I get this error when trying to connect. I'm not sure if it's a problem with this package or the docker image.

```
gorethink: dial tcp: lookup http on 127.0.0.11:53: server misbehaving
```

This is my docker compose config:

```
  db: 
    image: rethinkdb
    volumes:
      - .:/data
```

And I'm just trying to run the first example

```go
func Example() {
  session, err := r.Connect(r.ConnectOpts{
    Address: "http://db:28015",
  })  
  if err != nil {
    log.Fatalln(err)
  }
  res, err := r.Expr("Hello World").Run(session)
  if err != nil {
    log.Fatalln(err)
  }

  var response string
  err = res.One(&response)
  if err != nil {
    log.Fatalln(err)
  }
  fmt.Println(response)
}
```

**Comment by zwhitchcox** [comment]
Have verified, when I use run gorethink outside of the docker container, with rethinkdb running, it still can't connect and says the same error.

**Comment by zwhitchcox** [comment]
Have confirmed the node package is working. Maybe it's something with how I constructed the url? It was a variable in the example, but I don't see how it could be any different than what I used. When I run outside docker, I use `http://localhost:28015`, and when I used the NodeJS package, I use `{host: 'localhost', port: 28015}`, so it looks like there is a bug in `GoRethink` to me

**Comment by CMogilko** [comment]
check your DNS, `dial tcp: lookup http on 127.0.0.11:53: server misbehaving` it seems that golang `net.Dial` can't resolve your url because of DNS problems

**Comment by zwhitchcox** [comment]
Ok, I got it working on localhost by omitting 'http://' from the url supplied to address...still don't know why it's not working in docker

**Comment by zwhitchcox** [comment]
Ok, actually, it's working now, after omitting `http://` from the URL on the docker machine too.

**Comment by CMogilko** [comment]
it is true because rethinkdb protocol is not a http. hm, bad example...

**Comment by Leevandr** [comment]
panic: Post "https://api.telegram.org/bot`mykey`/getMe": dial tcp: lookup api.telegram.org on 127.0.0.11:53: server misbehaving

Can you please tell me what to do?
key - true
network connect in my server - true
ports open
