### ISSUE TITLE
.Exec memory leak ?

### ISSUE THREAD

**Issue by arsssen** [rethinkdb/rethinkdb-go#451]
Consider the following code:

```go
package main

import r "gopkg.in/rethinkdb/rethinkdb-go.v5"


func main() {
	session, err := r.Connect(r.ConnectOpts{Address: "localhost:28015"})
	if err != nil {
		return
	}
	execOpts := r.ExecOpts{NoReply: true}
	insertOpts := r.InsertOpts{Conflict: "update"}
	t := r.DB("test_db").Table("test_table")

	for {
		err = t.Insert(r.JSON(`{"id":"xxx", "a": 1}`), insertOpts).Exec(session, execOpts)
		if err != nil {
			return
		}
	}

}
```

when running this for around 1-2 minutes memory usage reaches 15GB

when using `.Run` instead of `.Exec` memory usage stays at ~10MB

Is there a memory leak here or I'm doing something wrong ?

**Comment by CMogilko** [comment]
It's connection leak. It seems that `Exec` doesn't close cursor or something. I need to investigate this.

**Comment by arsssen** [comment]
Thank you.

Is there any workaround ATM ? We have a huge amount of writes and `Run` (even with durability:soft) is too slow for that.

**Comment by CMogilko** [comment]
Try to parse json into go `map[string]interface{}` on the client side, it seems that server's `r.JSON` doesn't so effective. Also batch inserts are much faster. For example insert array of 1000 documents in a single query.

**Comment by arsssen** [comment]
thanks a lot!
