### ISSUE TITLE
How can i check on insert if  document exists or not in go rethinkdb?Please help

### ISSUE THREAD

**Issue by qousarbashir** [rethinkdb/rethinkdb-go#456]

**Comment by CMogilko** [comment]
Like in js-driver. `get(id).eq(null)`. Or try to read and check `r.ErrEmptyResult`.

**Comment by qousarbashir** [comment]
Hey @CMogilko Thanks.I figure out the solution for this.Can you please help me in the below scenario:
I have two documents 
![screenshot 1](https://user-images.githubusercontent.com/28569707/51655012-bc02e900-1fc0-11e9-981b-bbf89611ea92.png)
Based on accountType I want to update the verificationFee and contactNo.
SO if accountType=BUYER i will update in Buyer document and if accountType=Seller i will update seller document .
I am new to rethink.Using Golang.

**Comment by CMogilko** [comment]
In the most cases solutions are converted from js (rethink web data explorer) to golang as is. one to one. 
If you want to update one document, Buyer or Seller, you can use `filter`:
```golang
var accountType string = "BUYER"
var contactNo string = "123456789"
var verificationFee int = 550

r.Table().Filter(func(doc r.Term) r.Term {
   return doc.Field("accountType").Eq(accountType)
}).Update(func(doc r.Term) interface{}{
   return map[string]interface{}{
      "contactNo": contactNo,
      "verificationFee": verificationFee,
   }
}).RunWrite()
```
If you want to use index, try `GetAllByIndex` instead of `filter`

**Comment by qousarbashir** [comment]
@CMogilko  Thanks a lot.Hope all is good at your end
One more help Please.
Have a Table "user" which contains the below data:
![screenshot 2](https://user-images.githubusercontent.com/28569707/51979919-73fa2f80-24b4-11e9-8a9c-dea1e33b8f78.png)
I need the total count of Array elements and based on that i will access the last element of array.
I run the query r.table("user")("Employee").count().
Which gives me count=1 while as there are 3 elements in an array.Please Help

**Comment by CMogilko** [comment]
`("Employee")` is like `.pluck("Employee")`, so you still get a document list, in your case it contains a single document.
You need to use `.map()`

Also, Github issues are not the way to ask many different questions. Use official slack https://rethinkdb.slack.com/ for questions
