### ISSUE TITLE
Sort of race condition happening

### ISSUE THREAD

**Issue by racerxdl** [rethinkdb/rethinkdb-go#457]
On a project I'm doing, I put a test to test the creation / initialization of table indexes.

For some reason, it gives a sort of race condition when creating a table.

I use this call for initializing the tables:
https://github.com/quan-to/remote-signer/blob/develop/database/databaseManager.go#L59-L129

If I ran it twice, the second time doesn't detect the created table, try to create again and *successfully* creates it, leading to a duplicate table inside RethinkDB.

```
panic: rethinkdb: Table `qrs_test.gpgKey` is ambiguous; there are multiple tables with that name. in:
r.Table("gpgKey").IndexList().CoerceTo("array")
```

The test routine run on travis, single RethinkDB Instance so its not server-side race conditions. That also does not happen if I write the same snippet in nodejs.

I'm not sure what's happening there, besides that, it works normally. I already tried following solutions:

```go
r.Table(v.TableName).Wait(r.WaitOpts{ Timeout: 0 }).Exec(conn)
r.Table(v.TableName).IndexWait().Exec(conn)
```

The only solution that really works is to put a 5 second sleep for every table create, and a 10 second sleep after everything.

Any idea if I'm doing something wrong, or its a bug in rethinkdb-go?

Extras:
The error some times varies from table not found, duplicate table and even database not found. For example:
https://travis-ci.org/quan-to/remote-signer/jobs/490678159#L960-L961

**Comment by racerxdl** [comment]
This might be related: https://github.com/rethinkdb/rethinkdb/issues/4898

Not sure though since I use mutex for initializing the database. Even reducing MaxOpen / InitialCap to 1 doesn't solve the issue.

**Comment by racerxdl** [comment]
Ok so as a workaround, this works:

```go
func StringIndexOf(v string, a []string) int {
	for i, vo := range a {
		if vo == v {
			return i
		}
	}

	return -1
}

func GetDatabases() []string {
	dbLog.Debug("Listing databases")
	var conn = GetConnection()

	c, err := r.DBList().CoerceTo("array").Run(conn)

	if err != nil {
		panic(err)
	}

	z, err := c.Interface()

	if err != nil {
		panic(err)
	}

	var dbsI = z.([]interface{})
	var dbs = make([]string, len(dbsI))

	for i, v := range dbsI {
		dbs[i] = v.(string)
	}

	return dbs
}
func GetTableIndexes(tableName string) []string {
	dbLog.Debug("Listing table indexes")
	var conn = GetConnection()

	c, err := r.Table(tableName).IndexList().CoerceTo("array").Run(conn)

	if err != nil {
		panic(err)
	}

	z, err := c.Interface()

	if err != nil {
		panic(err)
	}

	var idxI = z.([]interface{})
	var idx = make([]string, len(idxI))

	for i, v := range idxI {
		idx[i] = v.(string)
	}

	return idx
}
func GetTables() []string {
	dbLog.Debug("Listing tables")
	var conn = GetConnection()

	c, err := r.TableList().CoerceTo("array").Run(conn)

	if err != nil {
		panic(err)
	}

	z, err := c.Interface()

	if err != nil {
		panic(err)
	}

	var tbsI = z.([]interface{})
	var tbs = make([]string, len(tbsI))

	for i, v := range tbsI {
		tbs[i] = v.(string)
	}

	return tbs
}


func WaitDatabaseCreate(database string) {
		dbs := GetDatabases()
		for StringIndexOf(database, dbs) == -1 {
			time.Sleep(1 * time.Second)
			dbs = GetDatabases()
		}
}

func WaitTableCreate(table string) {
		tables := GetTables()
		for StringIndexOf(table, tables) == -1 {
			time.Sleep(1 * time.Second)
			tables = GetTables()
		}
}

func WaitTableIndexCreate(table, index string) {
		indexes := GetTableIndexes(table)
		for StringIndexOf(index, indexes) == -1 {
			time.Sleep(1 * time.Second)
			indexes = GetTableIndexes(table)
		}
}
```

Then on every creation of index or table, I call the respective wait. Thats horrible, but I'm not sure what it happens.

**Comment by CMogilko** [comment]
Hello,
Yes, it is server's problem, not go-driver.
But why do you need to create the same table concurrently?

**Comment by racerxdl** [comment]
I dont need to and I'm not creating it concurrently. I even tried a mutex to lock everything while the tables are being created.

The thing happens if I call _sequentially_ table creation. For example, if I try to create the table, wait a bit and check again, it says it isn't created even when Wait returned.

**Comment by CMogilko** [comment]
I couldn't reproduce your case. I tried this:
```
r.DB("test").TableCreate("123").Exec(session)
r.DB("test").Table("123").Wait().Exec(session)
var lst []string
r.DB("test").TableList().ReadAll(&lst, session)
```
And `lst` contains `123` always. 

Which version of rethinkdb do you use?

**Comment by CMogilko** [comment]
@racerxdl is this issue actual?

**Comment by racerxdl** [comment]
@CMogilko I just found out that it was because some of the RethinkDB calls needs to be explicity closed. I think that was causing the issues, since when I properly closed everything the tests were running fine.

Just commenting this in case someone has this issue in the future.
