### ISSUE TITLE
res.One(&row) expecting slice

### ISSUE THREAD

**Issue by bjpine** [rethinkdb/rethinkdb-go#459]
```
var row interface{}
res.One(&row)
```

Results in:

`panic: result argument must be a slice address`

Unexpected behaviour as not matching documentation on README

**Comment by CMogilko** [comment]
@pynoable hi, I can't reproduce this, see unittest https://github.com/rethinkdb/rethinkdb-go/blob/develop/cursor_test.go#L12
Can you specify more details?

**Comment by bjpine** [comment]
Unable to reproduce myself now.
