### ISSUE TITLE
ChangeResponse, type field

### ISSUE THREAD

**Issue by nonotest** [rethinkdb/rethinkdb-go#463]
Hello,

thanks for the wonderful work..

Just came a cross the need to use `IncludeTypes` in a changefeed and noticed that
the current `ChangeReponse` struct does not include the `Type` field.
It is pretty trivial to add the new field so I was wondering if there is maybe an issue with doing so? if not happy to submit a pr with the small change..

thanks!

```
type ChangeResponse struct {
	NewValue interface{} `rethinkdb:"new_val,omitempty"`
	OldValue interface{} `rethinkdb:"old_val,omitempty"`
	State    string      `rethinkdb:"state,omitempty"`
	Error    string      `rethinkdb:"error,omitempty"`
	Type     string      `rethinkdb:"type,omitempty"` <--------
}
```

**Comment by CMogilko** [comment]
Hello @nonotest 
Yeah, field is missed, you are welcome to pr.

**Comment by nonotest** [comment]
ok here: https://github.com/rethinkdb/rethinkdb-go/pull/464 thanks!
