### ISSUE TITLE
How to use join

### ISSUE THREAD

**Issue by voidshard** [rethinkdb/rethinkdb-go#469]
Hey guys, 

I'm trying to figure out how to use inner join but I'm not sure what args it's expecting and can't see an example of it's use -
```
(t Term) InnerJoin(args ...interface{}) Term
```

To explain simply, I have a struct
```
type Sprite struct {
  Id string
  X int
  Y int
}
```
And I want to do a single query that given a Sprite.Id returns all Sprites in the same table within some radius of the given Sprite. (I assume InnerJoin would do this? Is there a better option?).

I can of course do this in two steps, but then I can't do a .Changes() which .. would be a bit unfortunate ..

**Comment by CMogilko** [comment]
Hey,
It's straight forward like js-driver: https://rethinkdb.com/api/javascript/eq_join
first example converts to golang:
```
r.Table("players").InnerJoin("gameId", r.Table("games"))
```
