### ISSUE TITLE
go mod path

### ISSUE THREAD

**Issue by sain801028** [rethinkdb/rethinkdb-go#484]
I use 6.1.1 update 6.2.0

go get: gopkg.in/rethinkdb/rethinkdb-go.v6@v6.2.0 requires
        gopkg.in/cenkalti/backoff.v4@v4.0.0: parsing go.mod:
        module declares its path as: github.com/cenkalti/backoff/v4
                but was required as: gopkg.in/cenkalti/backoff.v4

**Comment by sain801028** [comment]
I use go1.14

go get gopkg.in/rethinkdb/rethinkdb-go.v6
go: gopkg.in/rethinkdb/rethinkdb-go.v6 upgrade => v6.2.0
go get: gopkg.in/rethinkdb/rethinkdb-go.v6@v6.2.0 requires
        gopkg.in/cenkalti/backoff.v4@v4.0.0: parsing go.mod:
        module declares its path as: github.com/cenkalti/backoff/v4
                but was required as: gopkg.in/cenkalti/backoff.v4

**Comment by sain801028** [comment]
go get gopkg.in/cenkalti/backoff.v4
go get: gopkg.in/cenkalti/backoff.v4@v4.0.0: parsing go.mod:
        module declares its path as: github.com/cenkalti/backoff/v4
                but was required as: gopkg.in/cenkalti/backoff.v4

**Comment by CMogilko** [comment]
should be fixed in 6.2.1
https://github.com/rethinkdb/rethinkdb-go/pull/485
