### ISSUE TITLE
Maintenance rethinkdb/rethinkdb-go

### ISSUE THREAD

**Issue by DanyHenriquez** [rethinkdb/rethinkdb-go#507]
I would like to take over updating and maintaining the `rethinkdb/rethinkdb-go`. At this moment there seems to be no reliable update mechanism and it seems abandoned. I want to change that.

First PR is already there so we can make some progress. After that i will check what more i can do there.

**Comment by gabor-boros** [comment]
@DanyHenriquez I'm a little bit late on this. Are you still interested?

**Comment by DanyHenriquez** [comment]
> @DanyHenriquez I'm a little bit late on this. Are you still interested?

@gabor-boros 
Hello. I have not been checking my issues for a while, but I would be interested in maintaining the repo and doing updates.

**Comment by gabor-boros** [comment]
@DanyHenriquez Then I'd be happy to collaborate with you. I'll go through the open PRs this week and review them. If you need any help/info/resource/etc, just let me know.

At the moment, `CMogilko` and I are in the GitHub team that can update the repo directly. I did not do any maintenance lately (as visible), however, I'm happy to pick up the track again. Also, if you are interested on the long run, I'm happy to give you access to the repo as a maintainer after some PRs, so you don't have to hassle with forks.

**Comment by CMogilko** [comment]
I do not work with rethinkdb anymore, so no time to do maintenance, sorry.

**Comment by DanyHenriquez** [comment]
@gabor-boros @CMogilko 

I will work on some PR's and try to resolve some issues next week.

**Comment by PooyaEimandar** [comment]
Hi @DanyHenriquez , what is the status of this project?
Can we use it with the [latest version of rethinkDB](https://github.com/rethinkdb/rethinkdb/releases)?

**Comment by majst01** [comment]
@DanyHenriquez would also help here, already have some fork which updated the whole codebase a bit

https://github.com/majst01/rethinkdb-go/tree/go-1.22

**Comment by DanyHenriquez** [comment]
@majst01 Its great to have an updated code base, but would it not be better to merge it all back to this repository? 

Then we have one source of truth in stead of forks.

I'm willing to help, but I'm not willing to help with maintaining a fork of the original unless the original project maintainer is MIA.

Great work nonetheless!

**Comment by majst01** [comment]
> @majst01 Its great to have an updated code base, but would it not be better to merge it all back to this repository?
> 
> Then we have one source of truth in stead of forks.
> 
> I'm willing to help, but I'm not willing to help with maintaining a fork of the original unless the original project maintainer is MIA.
> 
> Great work nonetheless!

Sure, my goal is of course to get this merged, but i first want to test our sw with this before opening PRs. And it should be split into several PRs for better reviewability.

But it seems to me that right now, no one is reviewing PRs.

**Comment by SOG-web** [comment]
@majst01 and @DanyHenriquez please any update on this

**Comment by majst01** [comment]
No response from the maintainer yet to my suggestion.

**Comment by SOG-web** [comment]
> No response from the maintainer yet to my suggestion.

@gabor-boros please any update or can we go ahead to create a maintained fork

@majst01 have tested your updated version, can i install it directly

generally i also wanted to know if this supports serialization and deserialization, I mean can i do something like this 

```go
query := 'r.table(...).filter(...).map(...).serialize()'
r.deserialize(serializedQuery).run()
```

**Comment by majst01** [comment]
> > No response from the maintainer yet to my suggestion.
> 
> @gabor-boros please any update or can we go ahead to create a maintained fork
> 
> @majst01 have tested your updated version, can i install it directly

just add a replace in your go.mod 
```
replace gopkg.in/rethinkdb/rethinkdb-go.v6 => github.com/majst01/rethinkdb-go go-1.22
```

> 
> generally i also wanted to know if this supports serialization and deserialization, I mean can i do something like this
> 
> ```go
> query := 'r.table(...).filter(...).map(...).serialize()'
> r.deserialize(serializedQuery).run()
> ```

I didnt change any functionality.

**Comment by SOG-web** [comment]
> > > No response from the maintainer yet to my suggestion.
> > 
> > 
> > @gabor-boros please any update or can we go ahead to create a maintained fork
> > @majst01 have tested your updated version, can i install it directly
> 
> just add a replace in your go.mod
> 
> ```
> replace gopkg.in/rethinkdb/rethinkdb-go.v6 => github.com/majst01/rethinkdb-go go-1.22
> ```
> 
> > generally i also wanted to know if this supports serialization and deserialization, I mean can i do something like this
> > ```go
> > query := 'r.table(...).filter(...).map(...).serialize()'
> > r.deserialize(serializedQuery).run()
> > ```
> 
> I didnt change any functionality.


`go mod tidy`
`go: serverkit.com/cmd imports
	github.com/majst01/rethinkdb-go: github.com/majst01/rethinkdb-go@v0.0.0-20241004105851-dfd421fe865e: parsing go.mod:
	module declares its path as: gopkg.in/rethinkdb/rethinkdb-go.v6
	        but was required as: github.com/majst01/rethinkdb-go`

mod file 
`github.com/majst01/rethinkdb-go go-1.22  // indirect`

**Comment by SOG-web** [comment]
> > > > No response from the maintainer yet to my suggestion.
> > > 
> > > 
> > > @gabor-boros please any update or can we go ahead to create a maintained fork
> > > @majst01 have tested your updated version, can i install it directly
> > 
> > 
> > just add a replace in your go.mod
> > ```
> > replace gopkg.in/rethinkdb/rethinkdb-go.v6 => github.com/majst01/rethinkdb-go go-1.22
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > > generally i also wanted to know if this supports serialization and deserialization, I mean can i do something like this
> > > ```go
> > > query := 'r.table(...).filter(...).map(...).serialize()'
> > > r.deserialize(serializedQuery).run()
> > > ```
> > 
> > 
> > I didnt change any functionality.
> 
> `go mod tidy` `go: serverkit.com/cmd imports github.com/majst01/rethinkdb-go: github.com/majst01/rethinkdb-go@v0.0.0-20241004105851-dfd421fe865e: parsing go.mod: module declares its path as: gopkg.in/rethinkdb/rethinkdb-go.v6 but was required as: github.com/majst01/rethinkdb-go`
> 
> mod file `github.com/majst01/rethinkdb-go go-1.22 // indirect`

`go mod tidy
go: errors parsing go.mod:
go.mod:23:2: require github.com/majst01/rethinkdb-go: version "v6.2.2" invalid: should be v0 or v1, not v6
`
mod file 
`github.com/majst01/rethinkdb-go v6.2.2 `

**Comment by majst01** [comment]
> > > > > No response from the maintainer yet to my suggestion.
> > > > 
> > > > 
> > > > @gabor-boros please any update or can we go ahead to create a maintained fork
> > > > @majst01 have tested your updated version, can i install it directly
> > > 
> > > 
> > > just add a replace in your go.mod
> > > ```
> > > replace gopkg.in/rethinkdb/rethinkdb-go.v6 => github.com/majst01/rethinkdb-go go-1.22
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > > generally i also wanted to know if this supports serialization and deserialization, I mean can i do something like this
> > > > ```go
> > > > query := 'r.table(...).filter(...).map(...).serialize()'
> > > > r.deserialize(serializedQuery).run()
> > > > ```
> > > 
> > > 
> > > I didnt change any functionality.
> > 
> > 
> > `go mod tidy` `go: serverkit.com/cmd imports github.com/majst01/rethinkdb-go: github.com/majst01/rethinkdb-go@v0.0.0-20241004105851-dfd421fe865e: parsing go.mod: module declares its path as: gopkg.in/rethinkdb/rethinkdb-go.v6 but was required as: github.com/majst01/rethinkdb-go`
> > mod file `github.com/majst01/rethinkdb-go go-1.22 // indirect`
> 
> `go mod tidy go: errors parsing go.mod: go.mod:23:2: require github.com/majst01/rethinkdb-go: version "v6.2.2" invalid: should be v0 or v1, not v6 ` mod file `github.com/majst01/rethinkdb-go v6.2.2 `

OK, my fault, try replacing with a local copy of my branch like so:

```
replace gopkg.in/rethinkdb/rethinkdb-go.v6 => ../rethinkdb-go
```

where the later is the clone of my branch

**Comment by gabor-boros** [comment]
Hey @majst01 and @SOG-web,

Today later I'll take a look at this issue. I'm pretty happy to keep the ball rolling with this repository, though I need input from the community as I'm not using RethinkDB at the moment, hence I don't know the current pain points.

**Comment by SOG-web** [comment]
> Hey @majst01 and @SOG-web,
> 
> Today later I'll take a look at this issue. I'm pretty happy to keep the ball rolling with this repository, though I need input from the community as I'm not using RethinkDB at the moment, hence I don't know the current pain points.

thanks so much, I will sure send input. am currently building a go baas(backend as a service) with it

generally i also wanted to know if this supports serialization and deserialization, I mean can i do something like this

```go
query := 'r.table(...).filter(...).map(...).serialize()'
r.deserialize(serializedQuery).run()
```

**Comment by SOG-web** [comment]
> > Hey @majst01 and @SOG-web,
> > Today later I'll take a look at this issue. I'm pretty happy to keep the ball rolling with this repository, though I need input from the community as I'm not using RethinkDB at the moment, hence I don't know the current pain points.
> 
> thanks so much, I will sure send input. am currently building a go baas(backend as a service) with it
> 
> generally i also wanted to know if this supports serialization and deserialization, I mean can i do something like this
> 
> ```go
> query := 'r.table(...).filter(...).map(...).serialize()'
> r.deserialize(serializedQuery).run()
> ```

if the above is possible, I will be able to use the nodejs driver as a client(frontend) sdk to communicate with the go server

**Comment by SOG-web** [comment]
@majst01 i think you can push the PR now

**Comment by majst01** [comment]
https://github.com/rethinkdb/rethinkdb-go/pull/508

**Comment by SOG-web** [comment]
@gabor-boros Hi, just want to check if you have been able merge the PR from @majst01

**Comment by gabor-boros** [comment]
I can only take a look tomorrow as I'm traveling

**Comment by gabor-boros** [comment]
I took a look at the PR, but need more time to check it in depth. I'll do that tomorrow, and in the meantime, I'm going to close this issue as it is completely off topic now.
